
typedef unsigned long size_t;
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;

typedef int bool;




typedef struct TYPE_4__ TYPE_1__ ;


struct TYPE_4__ {int profile; int flags; int subtitle_header; int subtitle_header_size; } ;
typedef TYPE_1__ AVCodecContext ;


 int VAR_0 ;
 int VAR_1 ;
 int VAR_2 ;
 int VAR_3 ;
 int VAR_4 ;
 int VAR_5 ;
 int VAR_6 ;
 int VAR_7 ;
 int FUNC_0 (int ) ;
 int VAR_8 ;
 int VAR_9 ;
 char* FUNC_1 (int ) ;
 int VAR_10 ;
 int VAR_11 ;


 int VAR_12 ;
 int FUNC_2 (char*,char*,unsigned int,unsigned int,int ,unsigned int,int ,int ,int ,int ,int ,int ,int ,int ,int ) ;
 int FUNC_3 (TYPE_1__*,int ,char*) ;
 unsigned int FUNC_4 (int) ;
 int FUNC_5 (int ) ;

__attribute__((used)) static int FUNC_6(AVCodecContext *VAR_13)
{
    unsigned int VAR_14 = 0;
    unsigned int VAR_15 = 0;
    unsigned int VAR_16 = 0;

    switch (VAR_13->profile) {
    case 129:
        VAR_14 = 960;
        VAR_15 = 540;
        VAR_16 = FUNC_4(VAR_13->profile);
        break;
    case 128:
        VAR_14 = 320;
        VAR_15 = 180;
        VAR_16 = FUNC_4(VAR_13->profile);
        break;
    default:
        FUNC_3(VAR_13, VAR_9, "Unknown or unsupported profile set!\n");
        return FUNC_0(VAR_10);
    }

    VAR_13->subtitle_header = FUNC_2(
             "[Script Info]\r\n"
             "; Script generated by FFmpeg/Lavc%s\r\n"
             "ScriptType: v4.00+\r\n"
             "PlayResX: %d\r\n"
             "PlayResY: %d\r\n"
             "\r\n"
             "[V4+ Styles]\r\n"


             "Format: Name, "
             "Fontname, Fontsize, "
             "PrimaryColour, SecondaryColour, OutlineColour, BackColour, "
             "Bold, Italic, Underline, StrikeOut, "
             "ScaleX, ScaleY, "
             "Spacing, Angle, "
             "BorderStyle, Outline, Shadow, "
             "Alignment, MarginL, MarginR, MarginV, "
             "Encoding\r\n"

             "Style: "
             "Default,"
             "%s,%d,"
             "&H%x,&H%x,&H%x,&H%x,"
             "%d,%d,%d,0,"
             "100,100,"
             "0,0,"
             "%d,1,0,"
             "%d,10,10,10,"
             "0\r\n"

             "\r\n"
             "[Events]\r\n"
             "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\r\n",
             !(VAR_13->flags & VAR_8) ? FUNC_1(VAR_12) : "",
             VAR_14, VAR_15,
             VAR_5, VAR_16, VAR_4,
             VAR_4, VAR_1, VAR_1,
             -VAR_2, -VAR_6, -VAR_7,
             VAR_3, VAR_0);

    if (!VAR_13->subtitle_header)
        return FUNC_0(VAR_11);

    VAR_13->subtitle_header_size = FUNC_5(VAR_13->subtitle_header);

    return 0;
}
