
typedef unsigned long size_t;
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;

typedef int bool;




typedef struct TYPE_3__ TYPE_1__ ;


struct TYPE_3__ {int flags; int subtitle_header; int subtitle_header_size; } ;
typedef TYPE_1__ AVCodecContext ;


 int VAR_0 ;
 int VAR_1 ;
 int FUNC_0 (int ) ;
 int VAR_2 ;
 char* FUNC_1 (int ) ;
 int VAR_3 ;
 int VAR_4 ;
 int FUNC_2 (char*,char*,int ,int ,char const*,int,int,int,int,int,int,int,int,int,int) ;
 int FUNC_3 (int ) ;

int FUNC_4(AVCodecContext *VAR_5,
                           const char *VAR_6, int VAR_7,
                           int VAR_8, int VAR_9,
                           int VAR_10, int VAR_11, int VAR_12,
                           int VAR_13, int VAR_14)
{
    VAR_5->subtitle_header = FUNC_2(
             "[Script Info]\r\n"
             "; Script generated by FFmpeg/Lavc%s\r\n"
             "ScriptType: v4.00+\r\n"
             "PlayResX: %d\r\n"
             "PlayResY: %d\r\n"
             "\r\n"
             "[V4+ Styles]\r\n"


             "Format: Name, "
             "Fontname, Fontsize, "
             "PrimaryColour, SecondaryColour, OutlineColour, BackColour, "
             "Bold, Italic, Underline, StrikeOut, "
             "ScaleX, ScaleY, "
             "Spacing, Angle, "
             "BorderStyle, Outline, Shadow, "
             "Alignment, MarginL, MarginR, MarginV, "
             "Encoding\r\n"

             "Style: "
             "Default,"
             "%s,%d,"
             "&H%x,&H%x,&H%x,&H%x,"
             "%d,%d,%d,0,"
             "100,100,"
             "0,0,"
             "%d,1,0,"
             "%d,10,10,10,"
             "0\r\n"

             "\r\n"
             "[Events]\r\n"
             "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\r\n",
             !(VAR_5->flags & VAR_2) ? FUNC_1(VAR_4) : "",
             VAR_0, VAR_1,
             VAR_6, VAR_7, VAR_8, VAR_8, VAR_9, VAR_9,
             -VAR_10, -VAR_11, -VAR_12, VAR_13, VAR_14);

    if (!VAR_5->subtitle_header)
        return FUNC_0(VAR_3);
    VAR_5->subtitle_header_size = FUNC_3(VAR_5->subtitle_header);
    return 0;
}
