
typedef unsigned long size_t;
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;

typedef int bool;






struct arch_hibernate_hdr_invariants {int dummy; } ;
struct arch_hibernate_hdr {int sleep_cpu_mpidr; int invariants; } ;
typedef int invariants ;


 int VAR_0 ;
 int FUNC_0 (struct arch_hibernate_hdr_invariants*) ;
 int FUNC_1 (int) ;
 int FUNC_2 (int) ;
 int FUNC_3 (int ) ;
 scalar_t__ FUNC_4 (int *,struct arch_hibernate_hdr_invariants*,int) ;
 int FUNC_5 (char*) ;
 int FUNC_6 (char*) ;
 int FUNC_7 (char*,...) ;
 struct arch_hibernate_hdr VAR_1 ;
 int VAR_2 ;

int FUNC_8(void *VAR_3)
{
 int VAR_4;
 struct arch_hibernate_hdr_invariants VAR_5;
 struct arch_hibernate_hdr *VAR_6 = VAR_3;

 FUNC_0(&VAR_5);
 if (FUNC_4(&VAR_6->invariants, &VAR_5, sizeof(VAR_5))) {
  FUNC_5("Hibernate image not generated by this kernel!\n");
  return -VAR_0;
 }

 VAR_2 = FUNC_3(VAR_6->sleep_cpu_mpidr);
 FUNC_7("Hibernated on CPU %d [mpidr:0x%llx]\n", VAR_2,
  VAR_6->sleep_cpu_mpidr);
 if (VAR_2 < 0) {
  FUNC_5("Hibernated on a CPU not known to this kernel!\n");
  VAR_2 = -VAR_0;
  return -VAR_0;
 }
 if (!FUNC_1(VAR_2)) {
  FUNC_7("Hibernated on a CPU that is offline! Bringing CPU up.\n");
  VAR_4 = FUNC_2(VAR_2);
  if (VAR_4) {
   FUNC_6("Failed to bring hibernate-CPU up!\n");
   VAR_2 = -VAR_0;
   return VAR_4;
  }
 }

 VAR_1 = *VAR_6;

 return 0;
}
