
typedef unsigned long size_t;
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;

typedef int bool;
__attribute__((used)) static const char *FUNC_0(unsigned VAR_0)
{
   switch (VAR_0)
   {
      case 176:



         return "retroarch.png";

      case 141:
         return "settings.png";
      case 211:
         return "history.png";
      case 216:
         return "favorites.png";
      case 242:
         return "add-favorite.png";
      case 168:
         return "musics.png";
      case 142:
         return "setting.png";
      case 137:
         return "subsetting.png";
      case 241:
         return "arrow.png";
      case 146:
         return "run.png";
      case 229:
         return "close.png";
      case 151:
         return "resume.png";
      case 230:
         return "clock.png";
      case 234:
         return "battery-full.png";
      case 235:
         return "battery-charging.png";
      case 236:
         return "battery-80.png";
      case 237:
         return "battery-60.png";
      case 238:
         return "battery-40.png";
      case 239:
         return "battery-20.png";
      case 159:
         return "pointer.png";
      case 145:
         return "savestate.png";
      case 178:
         return "loadstate.png";
      case 133:
         return "undo.png";
      case 227:
         return "core-infos.png";
      case 129:
         return "wifi.png";
      case 226:
         return "core-options.png";
      case 192:
         return "core-input-remapping-options.png";
      case 232:
         return "core-cheat-options.png";
      case 220:
         return "core-disk-options.png";
      case 140:
         return "core-shader-options.png";
      case 244:
         return "achievement-list.png";
      case 143:
         return "screenshot.png";
      case 153:
         return "reload.png";
      case 152:
         return "rename.png";
      case 215:
         return "file.png";
      case 214:
         return "folder.png";
      case 128:
         return "zip.png";
      case 169:
         return "music.png";
      case 217:
         return "favorites-content.png";
      case 210:
         return "image.png";
      case 171:
         return "movie.png";
      case 228:
         return "core.png";
      case 155:
         return "database.png";
      case 225:
         return "cursor.png";
      case 135:
         return "on.png";
      case 136:
         return "off.png";
      case 243:
         return "add.png";
      case 181:
         return "key.png";
      case 180:
         return "key-hover.png";
      case 222:
         return "dialog-slice.png";
      case 245:
         return "menu_achievements.png";
      case 240:
         return "menu_audio.png";
      case 219:
         return "menu_drivers.png";
      case 218:
         return "menu_exit.png";
      case 213:
         return "menu_frameskip.png";
      case 212:
         return "menu_help.png";
      case 208:
         return "menu_info.png";
      case 189:
         return "Libretro - Pad.png";
      case 179:
         return "menu_latency.png";
      case 166:
         return "menu_network.png";
      case 158:
         return "menu_power.png";
      case 154:
         return "menu_record.png";
      case 144:
         return "menu_saving.png";
      case 132:
         return "menu_updater.png";
      case 130:
         return "menu_video.png";
      case 172:
         return "menu_mixer.png";
      case 177:
         return "menu_log.png";
      case 164:
         return "menu_osd.png";
      case 134:
         return "menu_ui.png";
      case 131:
         return "menu_user.png";
      case 157:
         return "menu_privacy.png";
      case 160:
         return "menu_playlist.png";
      case 221:
         return "disc.png";
      case 156:
         return "menu_quickmenu.png";
      case 150:
         return "menu_rewind.png";
      case 163:
         return "menu_overlay.png";
      case 162:
         return "menu_override.png";
      case 165:
         return "menu_notifications.png";
      case 138:
         return "menu_stream.png";
      case 139:
         return "menu_shutdown.png";
      case 198:
         return "input_DPAD-U.png";
      case 201:
         return "input_DPAD-D.png";
      case 200:
         return "input_DPAD-L.png";
      case 199:
         return "input_DPAD-R.png";
      case 183:
         return "input_STCK-U.png";
      case 187:
         return "input_STCK-D.png";
      case 186:
         return "input_STCK-L.png";
      case 184:
         return "input_STCK-R.png";
      case 185:
         return "input_STCK-P.png";
      case 202:
         return "input_BTN-U.png";
      case 205:
         return "input_BTN-D.png";
      case 204:
         return "input_BTN-L.png";
      case 203:
         return "input_BTN-R.png";
      case 197:
         return "input_LB.png";
      case 193:
         return "input_RB.png";
      case 195:
         return "input_LT.png";
      case 191:
         return "input_RT.png";
      case 190:
         return "input_SELECT.png";
      case 188:
         return "input_START.png";
      case 207:
         return "input_ADC.png";
      case 206:
         return "input_BIND_ALL.png";
      case 194:
         return "input_MOUSE.png";
      case 196:
         return "input_LGUN.png";
      case 182:
         return "input_TURBO.png";
      case 231:
         return "menu_check.png";
      case 175:
         return "menu_add.png";
      case 233:
         return "menu_brightness.png";
      case 161:
         return "menu_pause.png";
      case 224:
         return "default.png";
      case 223:
         return "default-content.png";
      case 173:
         return "menu_apply_toggle.png";
      case 174:
         return "menu_apply_cog.png";
   }
   return ((void*)0);
}
