
typedef unsigned long size_t;
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;

typedef int bool;
 int VAR_0 ;
 int FUNC_0 (char*) ;

__attribute__((used)) static void
FUNC_1 (char *VAR_1, int VAR_2)
{
  VAR_0++;
  FUNC_0 ("		    GNU GENERAL PUBLIC LICENSE\n");
  FUNC_0 ("		       Version 2, June 1991\n");
  FUNC_0 ("\n");
  FUNC_0 (" Copyright (C) 1989, 1991 Free Software Foundation, Inc.\n");
  FUNC_0 ("                       59 Temple Place, Suite 330, Boston, MA  02111-1307  USA\n");
  FUNC_0 (" Everyone is permitted to copy and distribute verbatim copies\n");
  FUNC_0 (" of this license document, but changing it is not allowed.\n");
  FUNC_0 ("\n");
  FUNC_0 ("			    Preamble\n");
  FUNC_0 ("\n");
  FUNC_0 ("  The licenses for most software are designed to take away your\n");
  FUNC_0 ("freedom to share and change it.  By contrast, the GNU General Public\n");
  FUNC_0 ("License is intended to guarantee your freedom to share and change free\n");
  FUNC_0 ("software--to make sure the software is free for all its users.  This\n");
  FUNC_0 ("General Public License applies to most of the Free Software\n");
  FUNC_0 ("Foundation's software and to any other program whose authors commit to\n");
  FUNC_0 ("using it.  (Some other Free Software Foundation software is covered by\n");
  FUNC_0 ("the GNU Library General Public License instead.)  You can apply it to\n");
  FUNC_0 ("your programs, too.\n");
  FUNC_0 ("\n");
  FUNC_0 ("  When we speak of free software, we are referring to freedom, not\n");
  FUNC_0 ("price.  Our General Public Licenses are designed to make sure that you\n");
  FUNC_0 ("have the freedom to distribute copies of free software (and charge for\n");
  FUNC_0 ("this service if you wish), that you receive source code or can get it\n");
  FUNC_0 ("if you want it, that you can change the software or use pieces of it\n");
  FUNC_0 ("in new free programs; and that you know you can do these things.\n");
  FUNC_0 ("\n");
  FUNC_0 ("  To protect your rights, we need to make restrictions that forbid\n");
  FUNC_0 ("anyone to deny you these rights or to ask you to surrender the rights.\n");
  FUNC_0 ("These restrictions translate to certain responsibilities for you if you\n");
  FUNC_0 ("distribute copies of the software, or if you modify it.\n");
  FUNC_0 ("\n");
  FUNC_0 ("  For example, if you distribute copies of such a program, whether\n");
  FUNC_0 ("gratis or for a fee, you must give the recipients all the rights that\n");
  FUNC_0 ("you have.  You must make sure that they, too, receive or can get the\n");
  FUNC_0 ("source code.  And you must show them these terms so they know their\n");
  FUNC_0 ("rights.\n");
  FUNC_0 ("\n");
  FUNC_0 ("  We protect your rights with two steps: (1) copyright the software, and\n");
  FUNC_0 ("(2) offer you this license which gives you legal permission to copy,\n");
  FUNC_0 ("distribute and/or modify the software.\n");
  FUNC_0 ("\n");
  FUNC_0 ("  Also, for each author's protection and ours, we want to make certain\n");
  FUNC_0 ("that everyone understands that there is no warranty for this free\n");
  FUNC_0 ("software.  If the software is modified by someone else and passed on, we\n");
  FUNC_0 ("want its recipients to know that what they have is not the original, so\n");
  FUNC_0 ("that any problems introduced by others will not reflect on the original\n");
  FUNC_0 ("authors' reputations.\n");
  FUNC_0 ("\n");
  FUNC_0 ("  Finally, any free program is threatened constantly by software\n");
  FUNC_0 ("patents.  We wish to avoid the danger that redistributors of a free\n");
  FUNC_0 ("program will individually obtain patent licenses, in effect making the\n");
  FUNC_0 ("program proprietary.  To prevent this, we have made it clear that any\n");
  FUNC_0 ("patent must be licensed for everyone's free use or not licensed at all.\n");
  FUNC_0 ("\n");
  FUNC_0 ("  The precise terms and conditions for copying, distribution and\n");
  FUNC_0 ("modification follow.\n");
  FUNC_0 ("\n");
  FUNC_0 ("		    GNU GENERAL PUBLIC LICENSE\n");
  FUNC_0 ("   TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION\n");
  FUNC_0 ("\n");
  FUNC_0 ("  0. This License applies to any program or other work which contains\n");
  FUNC_0 ("a notice placed by the copyright holder saying it may be distributed\n");
  FUNC_0 ("under the terms of this General Public License.  The \"Program\", below,\n");
  FUNC_0 ("refers to any such program or work, and a \"work based on the Program\"\n");
  FUNC_0 ("means either the Program or any derivative work under copyright law:\n");
  FUNC_0 ("that is to say, a work containing the Program or a portion of it,\n");
  FUNC_0 ("either verbatim or with modifications and/or translated into another\n");
  FUNC_0 ("language.  (Hereinafter, translation is included without limitation in\n");
  FUNC_0 ("the term \"modification\".)  Each licensee is addressed as \"you\".\n");
  FUNC_0 ("\n");
  FUNC_0 ("Activities other than copying, distribution and modification are not\n");
  FUNC_0 ("covered by this License; they are outside its scope.  The act of\n");
  FUNC_0 ("running the Program is not restricted, and the output from the Program\n");
  FUNC_0 ("is covered only if its contents constitute a work based on the\n");
  FUNC_0 ("Program (independent of having been made by running the Program).\n");
  FUNC_0 ("Whether that is true depends on what the Program does.\n");
  FUNC_0 ("\n");
  FUNC_0 ("  1. You may copy and distribute verbatim copies of the Program's\n");
  FUNC_0 ("source code as you receive it, in any medium, provided that you\n");
  FUNC_0 ("conspicuously and appropriately publish on each copy an appropriate\n");
  FUNC_0 ("copyright notice and disclaimer of warranty; keep intact all the\n");
  FUNC_0 ("notices that refer to this License and to the absence of any warranty;\n");
  FUNC_0 ("and give any other recipients of the Program a copy of this License\n");
  FUNC_0 ("along with the Program.\n");
  FUNC_0 ("\n");
  FUNC_0 ("You may charge a fee for the physical act of transferring a copy, and\n");
  FUNC_0 ("you may at your option offer warranty protection in exchange for a fee.\n");
  FUNC_0 ("\n");
  FUNC_0 ("  2. You may modify your copy or copies of the Program or any portion\n");
  FUNC_0 ("of it, thus forming a work based on the Program, and copy and\n");
  FUNC_0 ("distribute such modifications or work under the terms of Section 1\n");
  FUNC_0 ("above, provided that you also meet all of these conditions:\n");
  FUNC_0 ("\n");
  FUNC_0 ("    a) You must cause the modified files to carry prominent notices\n");
  FUNC_0 ("    stating that you changed the files and the date of any change.\n");
  FUNC_0 ("\n");
  FUNC_0 ("    b) You must cause any work that you distribute or publish, that in\n");
  FUNC_0 ("    whole or in part contains or is derived from the Program or any\n");
  FUNC_0 ("    part thereof, to be licensed as a whole at no charge to all third\n");
  FUNC_0 ("    parties under the terms of this License.\n");
  FUNC_0 ("\n");
  FUNC_0 ("    c) If the modified program normally reads commands interactively\n");
  FUNC_0 ("    when run, you must cause it, when started running for such\n");
  FUNC_0 ("    interactive use in the most ordinary way, to print or display an\n");
  FUNC_0 ("    announcement including an appropriate copyright notice and a\n");
  FUNC_0 ("    notice that there is no warranty (or else, saying that you provide\n");
  FUNC_0 ("    a warranty) and that users may redistribute the program under\n");
  FUNC_0 ("    these conditions, and telling the user how to view a copy of this\n");
  FUNC_0 ("    License.  (Exception: if the Program itself is interactive but\n");
  FUNC_0 ("    does not normally print such an announcement, your work based on\n");
  FUNC_0 ("    the Program is not required to print an announcement.)\n");
  FUNC_0 ("\n");
  FUNC_0 ("These requirements apply to the modified work as a whole.  If\n");
  FUNC_0 ("identifiable sections of that work are not derived from the Program,\n");
  FUNC_0 ("and can be reasonably considered independent and separate works in\n");
  FUNC_0 ("themselves, then this License, and its terms, do not apply to those\n");
  FUNC_0 ("sections when you distribute them as separate works.  But when you\n");
  FUNC_0 ("distribute the same sections as part of a whole which is a work based\n");
  FUNC_0 ("on the Program, the distribution of the whole must be on the terms of\n");
  FUNC_0 ("this License, whose permissions for other licensees extend to the\n");
  FUNC_0 ("entire whole, and thus to each and every part regardless of who wrote it.\n");
  FUNC_0 ("\n");
  FUNC_0 ("Thus, it is not the intent of this section to claim rights or contest\n");
  FUNC_0 ("your rights to work written entirely by you; rather, the intent is to\n");
  FUNC_0 ("exercise the right to control the distribution of derivative or\n");
  FUNC_0 ("collective works based on the Program.\n");
  FUNC_0 ("\n");
  FUNC_0 ("In addition, mere aggregation of another work not based on the Program\n");
  FUNC_0 ("with the Program (or with a work based on the Program) on a volume of\n");
  FUNC_0 ("a storage or distribution medium does not bring the other work under\n");
  FUNC_0 ("the scope of this License.\n");
  FUNC_0 ("\n");
  FUNC_0 ("  3. You may copy and distribute the Program (or a work based on it,\n");
  FUNC_0 ("under Section 2) in object code or executable form under the terms of\n");
  FUNC_0 ("Sections 1 and 2 above provided that you also do one of the following:\n");
  FUNC_0 ("\n");
  FUNC_0 ("    a) Accompany it with the complete corresponding machine-readable\n");
  FUNC_0 ("    source code, which must be distributed under the terms of Sections\n");
  FUNC_0 ("    1 and 2 above on a medium customarily used for software interchange; or,\n");
  FUNC_0 ("\n");
  FUNC_0 ("    b) Accompany it with a written offer, valid for at least three\n");
  FUNC_0 ("    years, to give any third party, for a charge no more than your\n");
  FUNC_0 ("    cost of physically performing source distribution, a complete\n");
  FUNC_0 ("    machine-readable copy of the corresponding source code, to be\n");
  FUNC_0 ("    distributed under the terms of Sections 1 and 2 above on a medium\n");
  FUNC_0 ("    customarily used for software interchange; or,\n");
  FUNC_0 ("\n");
  FUNC_0 ("    c) Accompany it with the information you received as to the offer\n");
  FUNC_0 ("    to distribute corresponding source code.  (This alternative is\n");
  FUNC_0 ("    allowed only for noncommercial distribution and only if you\n");
  FUNC_0 ("    received the program in object code or executable form with such\n");
  FUNC_0 ("    an offer, in accord with Subsection b above.)\n");
  FUNC_0 ("\n");
  FUNC_0 ("The source code for a work means the preferred form of the work for\n");
  FUNC_0 ("making modifications to it.  For an executable work, complete source\n");
  FUNC_0 ("code means all the source code for all modules it contains, plus any\n");
  FUNC_0 ("associated interface definition files, plus the scripts used to\n");
  FUNC_0 ("control compilation and installation of the executable.  However, as a\n");
  FUNC_0 ("special exception, the source code distributed need not include\n");
  FUNC_0 ("anything that is normally distributed (in either source or binary\n");
  FUNC_0 ("form) with the major components (compiler, kernel, and so on) of the\n");
  FUNC_0 ("operating system on which the executable runs, unless that component\n");
  FUNC_0 ("itself accompanies the executable.\n");
  FUNC_0 ("\n");
  FUNC_0 ("If distribution of executable or object code is made by offering\n");
  FUNC_0 ("access to copy from a designated place, then offering equivalent\n");
  FUNC_0 ("access to copy the source code from the same place counts as\n");
  FUNC_0 ("distribution of the source code, even though third parties are not\n");
  FUNC_0 ("compelled to copy the source along with the object code.\n");
  FUNC_0 ("\n");
  FUNC_0 ("  4. You may not copy, modify, sublicense, or distribute the Program\n");
  FUNC_0 ("except as expressly provided under this License.  Any attempt\n");
  FUNC_0 ("otherwise to copy, modify, sublicense or distribute the Program is\n");
  FUNC_0 ("void, and will automatically terminate your rights under this License.\n");
  FUNC_0 ("However, parties who have received copies, or rights, from you under\n");
  FUNC_0 ("this License will not have their licenses terminated so long as such\n");
  FUNC_0 ("parties remain in full compliance.\n");
  FUNC_0 ("\n");
  FUNC_0 ("  5. You are not required to accept this License, since you have not\n");
  FUNC_0 ("signed it.  However, nothing else grants you permission to modify or\n");
  FUNC_0 ("distribute the Program or its derivative works.  These actions are\n");
  FUNC_0 ("prohibited by law if you do not accept this License.  Therefore, by\n");
  FUNC_0 ("modifying or distributing the Program (or any work based on the\n");
  FUNC_0 ("Program), you indicate your acceptance of this License to do so, and\n");
  FUNC_0 ("all its terms and conditions for copying, distributing or modifying\n");
  FUNC_0 ("the Program or works based on it.\n");
  FUNC_0 ("\n");
  FUNC_0 ("  6. Each time you redistribute the Program (or any work based on the\n");
  FUNC_0 ("Program), the recipient automatically receives a license from the\n");
  FUNC_0 ("original licensor to copy, distribute or modify the Program subject to\n");
  FUNC_0 ("these terms and conditions.  You may not impose any further\n");
  FUNC_0 ("restrictions on the recipients' exercise of the rights granted herein.\n");
  FUNC_0 ("You are not responsible for enforcing compliance by third parties to\n");
  FUNC_0 ("this License.\n");
  FUNC_0 ("\n");
  FUNC_0 ("  7. If, as a consequence of a court judgment or allegation of patent\n");
  FUNC_0 ("infringement or for any other reason (not limited to patent issues),\n");
  FUNC_0 ("conditions are imposed on you (whether by court order, agreement or\n");
  FUNC_0 ("otherwise) that contradict the conditions of this License, they do not\n");
  FUNC_0 ("excuse you from the conditions of this License.  If you cannot\n");
  FUNC_0 ("distribute so as to satisfy simultaneously your obligations under this\n");
  FUNC_0 ("License and any other pertinent obligations, then as a consequence you\n");
  FUNC_0 ("may not distribute the Program at all.  For example, if a patent\n");
  FUNC_0 ("license would not permit royalty-free redistribution of the Program by\n");
  FUNC_0 ("all those who receive copies directly or indirectly through you, then\n");
  FUNC_0 ("the only way you could satisfy both it and this License would be to\n");
  FUNC_0 ("refrain entirely from distribution of the Program.\n");
  FUNC_0 ("\n");
  FUNC_0 ("If any portion of this section is held invalid or unenforceable under\n");
  FUNC_0 ("any particular circumstance, the balance of the section is intended to\n");
  FUNC_0 ("apply and the section as a whole is intended to apply in other\n");
  FUNC_0 ("circumstances.\n");
  FUNC_0 ("\n");
  FUNC_0 ("It is not the purpose of this section to induce you to infringe any\n");
  FUNC_0 ("patents or other property right claims or to contest validity of any\n");
  FUNC_0 ("such claims; this section has the sole purpose of protecting the\n");
  FUNC_0 ("integrity of the free software distribution system, which is\n");
  FUNC_0 ("implemented by public license practices.  Many people have made\n");
  FUNC_0 ("generous contributions to the wide range of software distributed\n");
  FUNC_0 ("through that system in reliance on consistent application of that\n");
  FUNC_0 ("system; it is up to the author/donor to decide if he or she is willing\n");
  FUNC_0 ("to distribute software through any other system and a licensee cannot\n");
  FUNC_0 ("impose that choice.\n");
  FUNC_0 ("\n");
  FUNC_0 ("This section is intended to make thoroughly clear what is believed to\n");
  FUNC_0 ("be a consequence of the rest of this License.\n");
  FUNC_0 ("\n");
  FUNC_0 ("  8. If the distribution and/or use of the Program is restricted in\n");
  FUNC_0 ("certain countries either by patents or by copyrighted interfaces, the\n");
  FUNC_0 ("original copyright holder who places the Program under this License\n");
  FUNC_0 ("may add an explicit geographical distribution limitation excluding\n");
  FUNC_0 ("those countries, so that distribution is permitted only in or among\n");
  FUNC_0 ("countries not thus excluded.  In such case, this License incorporates\n");
  FUNC_0 ("the limitation as if written in the body of this License.\n");
  FUNC_0 ("\n");
  FUNC_0 ("  9. The Free Software Foundation may publish revised and/or new versions\n");
  FUNC_0 ("of the General Public License from time to time.  Such new versions will\n");
  FUNC_0 ("be similar in spirit to the present version, but may differ in detail to\n");
  FUNC_0 ("address new problems or concerns.\n");
  FUNC_0 ("\n");
  FUNC_0 ("Each version is given a distinguishing version number.  If the Program\n");
  FUNC_0 ("specifies a version number of this License which applies to it and \"any\n");
  FUNC_0 ("later version\", you have the option of following the terms and conditions\n");
  FUNC_0 ("either of that version or of any later version published by the Free\n");
  FUNC_0 ("Software Foundation.  If the Program does not specify a version number of\n");
  FUNC_0 ("this License, you may choose any version ever published by the Free Software\n");
  FUNC_0 ("Foundation.\n");
  FUNC_0 ("\n");
  FUNC_0 ("  10. If you wish to incorporate parts of the Program into other free\n");
  FUNC_0 ("programs whose distribution conditions are different, write to the author\n");
  FUNC_0 ("to ask for permission.  For software which is copyrighted by the Free\n");
  FUNC_0 ("Software Foundation, write to the Free Software Foundation; we sometimes\n");
  FUNC_0 ("make exceptions for this.  Our decision will be guided by the two goals\n");
  FUNC_0 ("of preserving the free status of all derivatives of our free software and\n");
  FUNC_0 ("of promoting the sharing and reuse of software generally.\n");
  FUNC_0 ("\n");
  VAR_0--;
}
