
typedef unsigned long size_t;
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;

typedef int bool;
__attribute__((used)) static char *
FUNC_0 (unsigned VAR_0)
{
  switch (VAR_0)
    {
    case 275:
      return "DW_OP_addr";
    case 226:
      return "DW_OP_deref";
    case 235:
      return "DW_OP_const1u";
    case 236:
      return "DW_OP_const1s";
    case 233:
      return "DW_OP_const2u";
    case 234:
      return "DW_OP_const2s";
    case 231:
      return "DW_OP_const4u";
    case 232:
      return "DW_OP_const4s";
    case 229:
      return "DW_OP_const8u";
    case 230:
      return "DW_OP_const8s";
    case 227:
      return "DW_OP_constu";
    case 228:
      return "DW_OP_consts";
    case 222:
      return "DW_OP_dup";
    case 223:
      return "DW_OP_drop";
    case 175:
      return "DW_OP_over";
    case 174:
      return "DW_OP_pick";
    case 131:
      return "DW_OP_swap";
    case 136:
      return "DW_OP_rot";
    case 130:
      return "DW_OP_xderef";
    case 276:
      return "DW_OP_abs";
    case 274:
      return "DW_OP_and";
    case 224:
      return "DW_OP_div";
    case 183:
      return "DW_OP_minus";
    case 182:
      return "DW_OP_mod";
    case 181:
      return "DW_OP_mul";
    case 179:
      return "DW_OP_neg";
    case 177:
      return "DW_OP_not";
    case 176:
      return "DW_OP_or";
    case 172:
      return "DW_OP_plus";
    case 171:
      return "DW_OP_plus_uconst";
    case 135:
      return "DW_OP_shl";
    case 134:
      return "DW_OP_shr";
    case 133:
      return "DW_OP_shra";
    case 128:
      return "DW_OP_xor";
    case 273:
      return "DW_OP_bra";
    case 221:
      return "DW_OP_eq";
    case 219:
      return "DW_OP_ge";
    case 218:
      return "DW_OP_gt";
    case 217:
      return "DW_OP_le";
    case 184:
      return "DW_OP_lt";
    case 180:
      return "DW_OP_ne";
    case 132:
      return "DW_OP_skip";
    case 216:
      return "DW_OP_lit0";
    case 215:
      return "DW_OP_lit1";
    case 204:
      return "DW_OP_lit2";
    case 193:
      return "DW_OP_lit3";
    case 190:
      return "DW_OP_lit4";
    case 189:
      return "DW_OP_lit5";
    case 188:
      return "DW_OP_lit6";
    case 187:
      return "DW_OP_lit7";
    case 186:
      return "DW_OP_lit8";
    case 185:
      return "DW_OP_lit9";
    case 214:
      return "DW_OP_lit10";
    case 213:
      return "DW_OP_lit11";
    case 212:
      return "DW_OP_lit12";
    case 211:
      return "DW_OP_lit13";
    case 210:
      return "DW_OP_lit14";
    case 209:
      return "DW_OP_lit15";
    case 208:
      return "DW_OP_lit16";
    case 207:
      return "DW_OP_lit17";
    case 206:
      return "DW_OP_lit18";
    case 205:
      return "DW_OP_lit19";
    case 203:
      return "DW_OP_lit20";
    case 202:
      return "DW_OP_lit21";
    case 201:
      return "DW_OP_lit22";
    case 200:
      return "DW_OP_lit23";
    case 199:
      return "DW_OP_lit24";
    case 198:
      return "DW_OP_lit25";
    case 197:
      return "DW_OP_lit26";
    case 196:
      return "DW_OP_lit27";
    case 195:
      return "DW_OP_lit28";
    case 194:
      return "DW_OP_lit29";
    case 192:
      return "DW_OP_lit30";
    case 191:
      return "DW_OP_lit31";
    case 169:
      return "DW_OP_reg0";
    case 168:
      return "DW_OP_reg1";
    case 157:
      return "DW_OP_reg2";
    case 146:
      return "DW_OP_reg3";
    case 143:
      return "DW_OP_reg4";
    case 142:
      return "DW_OP_reg5";
    case 141:
      return "DW_OP_reg6";
    case 140:
      return "DW_OP_reg7";
    case 139:
      return "DW_OP_reg8";
    case 138:
      return "DW_OP_reg9";
    case 167:
      return "DW_OP_reg10";
    case 166:
      return "DW_OP_reg11";
    case 165:
      return "DW_OP_reg12";
    case 164:
      return "DW_OP_reg13";
    case 163:
      return "DW_OP_reg14";
    case 162:
      return "DW_OP_reg15";
    case 161:
      return "DW_OP_reg16";
    case 160:
      return "DW_OP_reg17";
    case 159:
      return "DW_OP_reg18";
    case 158:
      return "DW_OP_reg19";
    case 156:
      return "DW_OP_reg20";
    case 155:
      return "DW_OP_reg21";
    case 154:
      return "DW_OP_reg22";
    case 153:
      return "DW_OP_reg23";
    case 152:
      return "DW_OP_reg24";
    case 151:
      return "DW_OP_reg25";
    case 150:
      return "DW_OP_reg26";
    case 149:
      return "DW_OP_reg27";
    case 148:
      return "DW_OP_reg28";
    case 147:
      return "DW_OP_reg29";
    case 145:
      return "DW_OP_reg30";
    case 144:
      return "DW_OP_reg31";
    case 272:
      return "DW_OP_breg0";
    case 271:
      return "DW_OP_breg1";
    case 260:
      return "DW_OP_breg2";
    case 249:
      return "DW_OP_breg3";
    case 246:
      return "DW_OP_breg4";
    case 245:
      return "DW_OP_breg5";
    case 244:
      return "DW_OP_breg6";
    case 243:
      return "DW_OP_breg7";
    case 242:
      return "DW_OP_breg8";
    case 241:
      return "DW_OP_breg9";
    case 270:
      return "DW_OP_breg10";
    case 269:
      return "DW_OP_breg11";
    case 268:
      return "DW_OP_breg12";
    case 267:
      return "DW_OP_breg13";
    case 266:
      return "DW_OP_breg14";
    case 265:
      return "DW_OP_breg15";
    case 264:
      return "DW_OP_breg16";
    case 263:
      return "DW_OP_breg17";
    case 262:
      return "DW_OP_breg18";
    case 261:
      return "DW_OP_breg19";
    case 259:
      return "DW_OP_breg20";
    case 258:
      return "DW_OP_breg21";
    case 257:
      return "DW_OP_breg22";
    case 256:
      return "DW_OP_breg23";
    case 255:
      return "DW_OP_breg24";
    case 254:
      return "DW_OP_breg25";
    case 253:
      return "DW_OP_breg26";
    case 252:
      return "DW_OP_breg27";
    case 251:
      return "DW_OP_breg28";
    case 250:
      return "DW_OP_breg29";
    case 248:
      return "DW_OP_breg30";
    case 247:
      return "DW_OP_breg31";
    case 137:
      return "DW_OP_regx";
    case 220:
      return "DW_OP_fbreg";
    case 240:
      return "DW_OP_bregx";
    case 173:
      return "DW_OP_piece";
    case 225:
      return "DW_OP_deref_size";
    case 129:
      return "DW_OP_xderef_size";
    case 178:
      return "DW_OP_nop";

    case 170:
      return "DW_OP_push_object_address";
    case 239:
      return "DW_OP_call2";
    case 238:
      return "DW_OP_call4";
    case 237:
      return "DW_OP_call_ref";

    case 278:
      return "DW_OP_GNU_push_tls_address";
    case 277:
      return "DW_OP_GNU_uninit";
    default:
      return "OP_<unknown>";
    }
}
