
typedef unsigned long size_t;
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;

typedef int bool;




typedef struct TYPE_4__ TYPE_1__ ;


struct cleanup {int dummy; } ;
typedef int bfd ;
struct TYPE_4__ {int to_sections_end; int to_sections; } ;


 int VAR_0 ;
 int VAR_1 ;
 int VAR_2 ;
 int VAR_3 ;
 int VAR_4 ;
 int FUNC_0 (int *,int ) ;
 int VAR_5 ;
 char* FUNC_1 (int *) ;
 int FUNC_2 (int *) ;
 char* FUNC_3 (int ) ;
 int * FUNC_4 (char*,int ,int) ;
 int FUNC_5 () ;
 char* FUNC_6 (int *) ;
 int FUNC_7 (int *,char*) ;
 int FUNC_8 (int *,int ,int ) ;
 scalar_t__ FUNC_9 (int *,int *,int *) ;
 int FUNC_10 (int ,int*,char*,int ) ;
 char* FUNC_11 (int ,char*,char*,int *) ;
 int * VAR_6 ;
 int FUNC_12 (char*) ;
 int VAR_7 ;
 TYPE_1__ VAR_8 ;
 int VAR_9 ;
 int VAR_10 ;
 int VAR_11 ;
 int FUNC_13 (struct cleanup*) ;
 int FUNC_14 (char*,...) ;
 int VAR_12 ;
 int FUNC_15 () ;
 int FUNC_16 (int ) ;
 int FUNC_17 (int *) ;
 int FUNC_18 (int *) ;
 int FUNC_19 () ;
 int VAR_13 ;
 int FUNC_20 () ;
 struct cleanup* FUNC_21 (int (*) (char*),char*) ;
 int FUNC_22 (int *) ;
 int FUNC_23 (char*,int,int ) ;
 int FUNC_24 (char*) ;
 int FUNC_25 (int ,int ,int) ;
 int FUNC_26 (char*,...) ;
 int FUNC_27 (TYPE_1__*) ;
 int FUNC_28 (int ) ;
 int FUNC_29 (int *) ;
 int FUNC_30 (int *) ;
 int VAR_14 ;
 int FUNC_31 (int) ;
 int VAR_15 ;
 int FUNC_32 (int) ;
 int FUNC_33 (int) ;
 int FUNC_34 (int ) ;
 char* FUNC_35 (char*) ;
 int FUNC_36 (TYPE_1__*) ;
 int FUNC_37 () ;
 int FUNC_38 (char*,int ) ;
 scalar_t__ VAR_16 ;
 int FUNC_39 (char*) ;

__attribute__((used)) static void
FUNC_40 (char *VAR_17, int VAR_18)
{
  const char *VAR_19;
  int VAR_20;
  struct cleanup *VAR_21;
  char *VAR_22;
  bfd *VAR_23;
  int VAR_24;
  int VAR_25;

  FUNC_32 (VAR_18);
  if (!VAR_17)
    {
      FUNC_14 (VAR_6 ?
      "No core file specified.  (Use `detach' to stop debugging a core file.)"
      : "No core file specified.");
    }

  VAR_17 = FUNC_35 (VAR_17);
  if (VAR_17[0] != '/')
    {
      VAR_22 = FUNC_11 (VAR_10, "/", VAR_17, ((void*)0));
      FUNC_39 (VAR_17);
      VAR_17 = VAR_22;
    }

  VAR_21 = FUNC_21 (FUNC_39, VAR_17);

  VAR_25 = FUNC_23 (VAR_17, VAR_0 | ( VAR_16 ? VAR_2 : VAR_1 ), 0);
  if (VAR_25 < 0)
    FUNC_24 (VAR_17);

  VAR_23 = FUNC_4 (VAR_17, VAR_13, VAR_25);
  if (VAR_23 == ((void*)0))
    FUNC_24 (VAR_17);

  if (!FUNC_0 (VAR_23, VAR_5) &&
      !FUNC_17 (VAR_23))
    {




      FUNC_22 (VAR_23);
      FUNC_14 ("\"%s\" is not a core dump: %s",
      VAR_17, FUNC_3 (FUNC_5 ()));
    }



  FUNC_13 (VAR_21);
  FUNC_36 (&VAR_8);
  VAR_6 = VAR_23;
  VAR_21 = FUNC_21 (FUNC_12, 0 );







  VAR_7 = FUNC_18 (VAR_6);


  VAR_9 = FUNC_30 (VAR_6);

  FUNC_37 ();


  if (FUNC_9 (VAR_6, &VAR_8.to_sections,
      &VAR_8.to_sections_end))
    FUNC_14 ("\"%s\": Can't find sections: %s",
    FUNC_6 (VAR_6), FUNC_3 (FUNC_5 ()));





  if (!VAR_12)
    FUNC_29 (VAR_6);

  VAR_24 = !FUNC_27 (&VAR_8);
  FUNC_13 (VAR_21);

  VAR_19 = FUNC_1 (VAR_6);
  if (VAR_19)
    FUNC_26 ("Core was generated by `%s'.\n", VAR_19);

  VAR_20 = FUNC_2 (VAR_6);
  if (VAR_20 > 0)




    FUNC_26 ("Program terminated with signal %d, %s.\n", VAR_20,
       FUNC_34 (FUNC_33 (VAR_20)));



  FUNC_20 ();
  FUNC_8 (VAR_6, VAR_4,
    FUNC_7 (VAR_6, ".reg"));

  if (VAR_24)
    {

      FUNC_31 (-1);
      FUNC_15 ();
      FUNC_28 (FUNC_19 ());
      FUNC_25 (VAR_11,
    FUNC_16 (VAR_11), 1);
    }
  else
    {
      FUNC_38 (
  "you won't be able to access this core file until you terminate\nyour %s; do ``info files''", VAR_15);

    }
}
