
typedef unsigned long size_t;
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;

typedef int bool;






typedef int vec3_t ;
typedef int entity_t ;
typedef int bspShader_t ;
typedef int bspModel_t ;
typedef int FILE ;


 int FUNC_0 (int *,int *,int,int ) ;
 int FUNC_1 (int *,int *,int) ;
 int FUNC_2 (char*,char*) ;
 int FUNC_3 (char*,char*) ;
 int FUNC_4 (int *,char*,int ) ;
 int FUNC_5 (char*) ;
 int FUNC_6 (char*,...) ;
 char* FUNC_7 (int *,char*) ;
 int FUNC_8 (int ) ;
 int FUNC_9 (char const*) ;
 int * VAR_0 ;
 int * VAR_1 ;
 int * VAR_2 ;
 int FUNC_10 (int *) ;
 int * FUNC_11 (char*,char*) ;
 int FUNC_12 (int *,char*,...) ;
 int VAR_3 ;
 int VAR_4 ;
 int FUNC_13 (char*,char*) ;
 int FUNC_14 (char*,char*) ;

int FUNC_15( char *VAR_5 ){
 int VAR_6, VAR_7;
 FILE *VAR_8;
 bspShader_t *VAR_9;
 bspModel_t *VAR_10;
 entity_t *VAR_11;
 vec3_t VAR_12;
 const char *VAR_13;
 char VAR_14[ 1024 ], VAR_15[ 1024 ];



 FUNC_6( "--- Convert BSP to ASE ---\n" );


 FUNC_14( VAR_14, VAR_5 );
 FUNC_5( VAR_14 );
 FUNC_13( VAR_14, ".ase" );
 FUNC_6( "writing %s\n", VAR_14 );

 FUNC_3( VAR_5, VAR_15 );
 FUNC_13( VAR_15, ".bsp" );


 VAR_8 = FUNC_11( VAR_14, "wb" );
 if ( VAR_8 == ((void*)0) ) {
  FUNC_2( "Open failed on %s\n", VAR_14 );
 }


 FUNC_12( VAR_8, "*3DSMAX_ASCIIEXPORT\t200\r\n" );
 FUNC_12( VAR_8, "*COMMENT\t\"Generated by Q3Map2 (ydnar) -convert -format ase\"\r\n" );
 FUNC_12( VAR_8, "*SCENE\t{\r\n" );
 FUNC_12( VAR_8, "\t*SCENE_FILENAME\t\"%s\"\r\n", VAR_15 );
 FUNC_12( VAR_8, "\t*SCENE_FIRSTFRAME\t0\r\n" );
 FUNC_12( VAR_8, "\t*SCENE_LASTFRAME\t100\r\n" );
 FUNC_12( VAR_8, "\t*SCENE_FRAMESPEED\t30\r\n" );
 FUNC_12( VAR_8, "\t*SCENE_TICKSPERFRAME\t160\r\n" );
 FUNC_12( VAR_8, "\t*SCENE_BACKGROUND_STATIC\t0.0000\t0.0000\t0.0000\r\n" );
 FUNC_12( VAR_8, "\t*SCENE_AMBIENT_STATIC\t0.0000\t0.0000\t0.0000\r\n" );
 FUNC_12( VAR_8, "}\r\n" );


 FUNC_12( VAR_8, "*MATERIAL_LIST\t{\r\n" );
 FUNC_12( VAR_8, "\t*MATERIAL_COUNT\t%d\r\n", VAR_3 );
 for ( VAR_6 = 0; VAR_6 < VAR_3; VAR_6++ )
 {
  VAR_9 = &VAR_1[ VAR_6 ];
  FUNC_1( VAR_8, VAR_9, VAR_6 );
 }
 FUNC_12( VAR_8, "}\r\n" );


 for ( VAR_6 = 0; VAR_6 < VAR_4; VAR_6++ )
 {

  VAR_11 = &VAR_2[ VAR_6 ];
  if ( VAR_6 == 0 ) {
   VAR_7 = 0;
  }
  else
  {
   VAR_13 = FUNC_7( VAR_11, "model" );
   if ( VAR_13[ 0 ] != '*' ) {
    continue;
   }
   VAR_7 = FUNC_9( VAR_13 + 1 );
  }
  VAR_10 = &VAR_0[ VAR_7 ];


  VAR_13 = FUNC_7( VAR_11, "origin" );
  if ( VAR_13[ 0 ] == '\0' ) {
   FUNC_8( VAR_12 );
  }
  else{
   FUNC_4( VAR_11, "origin", VAR_12 );
  }


  FUNC_0( VAR_8, VAR_10, VAR_7, VAR_12 );
 }


 FUNC_10( VAR_8 );


 return 0;
}
