
typedef unsigned long size_t;
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;

typedef int bool;






typedef int vec3_t ;
typedef int entity_t ;
typedef int bspModel_t ;
typedef int FILE ;


 int FUNC_0 (int *,int *) ;
 int FUNC_1 (int *,int *,int,int ) ;
 int FUNC_2 (char*,char*) ;
 int FUNC_3 (char*,char*) ;
 int FUNC_4 (int *,char*,int ) ;
 int FUNC_5 (char*) ;
 int FUNC_6 (char*,...) ;
 char* FUNC_7 (int *,char*) ;
 int FUNC_8 (int ) ;
 int FUNC_9 (char const*) ;
 int * VAR_0 ;
 int * VAR_1 ;
 int FUNC_10 (int *) ;
 int * FUNC_11 (char*,char*) ;
 int FUNC_12 (int *,char*,...) ;
 int VAR_2 ;
 int FUNC_13 (char*,char*) ;
 int FUNC_14 (char*,char*) ;

int FUNC_15( char *VAR_3 ){
 int VAR_4, VAR_5;
 FILE *VAR_6;
 bspModel_t *VAR_7;
 entity_t *VAR_8;
 vec3_t VAR_9;
 const char *VAR_10;
 char VAR_11[ 1024 ], VAR_12[ 1024 ];



 FUNC_6( "--- Convert BSP to MAP ---\n" );


 FUNC_14( VAR_11, VAR_3 );
 FUNC_5( VAR_11 );
 FUNC_13( VAR_11, "_converted.map" );
 FUNC_6( "writing %s\n", VAR_11 );

 FUNC_3( VAR_3, VAR_12 );
 FUNC_13( VAR_12, ".bsp" );


 VAR_6 = FUNC_11( VAR_11, "wb" );
 if ( VAR_6 == ((void*)0) ) {
  FUNC_2( "Open failed on %s\n", VAR_11 );
 }


 FUNC_12( VAR_6, "// Generated by Q3Map2 (ydnar) -convert -format map\n" );


 for ( VAR_4 = 0; VAR_4 < VAR_2; VAR_4++ )
 {

  VAR_8 = &VAR_1[ VAR_4 ];


  FUNC_12( VAR_6, "// entity %d\n", VAR_4 );
  FUNC_12( VAR_6, "{\n" );


  FUNC_0( VAR_6, VAR_8 );
  FUNC_12( VAR_6, "\n" );


  if ( VAR_4 == 0 ) {
   VAR_5 = 0;
  }
  else
  {
   VAR_10 = FUNC_7( VAR_8, "model" );
   if ( VAR_10[ 0 ] == '*' ) {
    VAR_5 = FUNC_9( VAR_10 + 1 );
   }
   else{
    VAR_5 = -1;
   }
  }


  if ( VAR_5 >= 0 ) {

   VAR_7 = &VAR_0[ VAR_5 ];


   VAR_10 = FUNC_7( VAR_8, "origin" );
   if ( VAR_10[ 0 ] == '\0' ) {
    FUNC_8( VAR_9 );
   }
   else{
    FUNC_4( VAR_8, "origin", VAR_9 );
   }


   FUNC_1( VAR_6, VAR_7, VAR_5, VAR_9 );
  }


  FUNC_12( VAR_6, "}\n\n" );
 }


 FUNC_10( VAR_6 );


 return 0;
}
