
typedef unsigned long size_t;
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;

typedef int bool;






typedef int time_t ;
typedef int FILE ;


 int FUNC_0 (char*,char*) ;
 int VAR_0 ;
 char* FUNC_1 (int *) ;
 int FUNC_2 (int *) ;
 int FUNC_3 (int *) ;
 int * FUNC_4 (char*,char*) ;
 int FUNC_5 (int *,char*,...) ;
 int FUNC_6 (char,int *) ;
 int FUNC_7 (char*,int *) ;
 int * VAR_1 ;
 int FUNC_8 (int *) ;

int FUNC_9 (int VAR_2, char **VAR_3)
{
  FILE *VAR_4;
  FILE *VAR_5 = VAR_1;
  time_t VAR_6 = FUNC_8 (((void*)0));
  int VAR_7, VAR_8;

  if (VAR_2 != 2)
     FUNC_0 ("Usage: %s bin-file [> result]", VAR_3[0]);

  if ((VAR_4 = FUNC_4(VAR_3[1],"rb")) == ((void*)0))
     FUNC_0 ("Cannot open %s\n", VAR_3[1]);

  FUNC_5 (VAR_5,
           "/* data statements for file %s at %.24s */\n"
           "/* Generated by BIN2C, G. Vanem 1995 */\n",
           VAR_3[1], FUNC_1(&VAR_6));

  VAR_8 = 0;
  while ((VAR_7 = FUNC_3(VAR_4)) != VAR_0)
  {
    if (VAR_8++ % 12 == 0)
       FUNC_7 ("\n  ", VAR_5);
    FUNC_5 (VAR_5, "0x%02X,", VAR_7);
  }
  FUNC_6 ('\n', VAR_5);
  FUNC_2 (VAR_4);
  return (0);
}
