
typedef unsigned long size_t;
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;

typedef int bool;






struct snd_info_entry {struct hdspm* private_data; } ;
struct snd_info_buffer {int dummy; } ;
struct hdspm {int max_channels_in; int * port_names_in; } ;


 int FUNC_0 (struct snd_info_buffer*,char*,...) ;

__attribute__((used)) static void FUNC_1(struct snd_info_entry *VAR_0,
     struct snd_info_buffer *VAR_1)
{
 struct hdspm *VAR_2 = VAR_0->private_data;
 int VAR_3;

 FUNC_0(VAR_1, "# generated by hdspm\n");

 for (VAR_3 = 0; VAR_3 < VAR_2->max_channels_in; VAR_3++) {
  FUNC_0(VAR_1, "%d=%s\n", VAR_3+1, VAR_2->port_names_in[VAR_3]);
 }
}
