
typedef unsigned long size_t;
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;

typedef int bool;






typedef int FOLDER ;


 int FUNC_0 (int *,char*) ;
 int VAR_0 ;
 int VAR_1 ;
 int VAR_2 ;
 int VAR_3 ;
 int VAR_4 ;
 int VAR_5 ;
 int VAR_6 ;
 int VAR_7 ;
 int VAR_8 ;
 int VAR_9 ;
 int VAR_10 ;
 int VAR_11 ;
 int VAR_12 ;
 int VAR_13 ;
 int VAR_14 ;
 int VAR_15 ;
 int VAR_16 ;
 int VAR_17 ;
 int VAR_18 ;
 int VAR_19 ;
 int VAR_20 ;
 int FUNC_1 (int ) ;
 int FUNC_2 (int ,int ) ;

void FUNC_3(FOLDER *VAR_21)
{
 FUNC_2(VAR_10, FUNC_0(VAR_21, "MAX_SEND_SOCKET_QUEUE_SIZE"));
 FUNC_2(VAR_13, FUNC_0(VAR_21, "MIN_SEND_SOCKET_QUEUE_SIZE"));
 FUNC_2(VAR_9, FUNC_0(VAR_21, "MAX_SEND_SOCKET_QUEUE_NUM"));
 FUNC_2(VAR_15, FUNC_0(VAR_21, "SELECT_TIME"));
 FUNC_2(VAR_16, FUNC_0(VAR_21, "SELECT_TIME_FOR_NAT"));
 FUNC_2(VAR_11, FUNC_0(VAR_21, "MAX_STORED_QUEUE_NUM"));
 FUNC_2(VAR_5, FUNC_0(VAR_21, "MAX_BUFFERING_PACKET_SIZE"));
 FUNC_2(VAR_1, FUNC_0(VAR_21, "HUB_ARP_SEND_INTERVAL"));
 FUNC_2(VAR_4, FUNC_0(VAR_21, "MAC_TABLE_EXPIRE_TIME"));
 FUNC_2(VAR_2, FUNC_0(VAR_21, "IP_TABLE_EXPIRE_TIME"));
 FUNC_2(VAR_3, FUNC_0(VAR_21, "IP_TABLE_EXPIRE_TIME_DHCP"));
 FUNC_2(VAR_17, FUNC_0(VAR_21, "STORM_CHECK_SPAN"));
 FUNC_2(VAR_19, FUNC_0(VAR_21, "STORM_DISCARD_VALUE_START"));
 FUNC_2(VAR_18, FUNC_0(VAR_21, "STORM_DISCARD_VALUE_END"));
 FUNC_2(VAR_8, FUNC_0(VAR_21, "MAX_MAC_TABLES"));
 FUNC_2(VAR_7, FUNC_0(VAR_21, "MAX_IP_TABLES"));
 FUNC_2(VAR_6, FUNC_0(VAR_21, "MAX_HUB_LINKS"));
 FUNC_2(VAR_12, FUNC_0(VAR_21, "MEM_FIFO_REALLOC_MEM_SIZE"));
 FUNC_2(VAR_14, FUNC_0(VAR_21, "QUEUE_BUDGET"));
 FUNC_2(VAR_0, FUNC_0(VAR_21, "FIFO_BUDGET"));

 FUNC_1(VAR_20);
}
