
typedef unsigned long size_t;
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;

typedef int bool;






typedef int SSL_CTX ;


 int FUNC_0 (int *) ;
 int FUNC_1 (int *) ;
 int * FUNC_2 (char const*,char*) ;
 int FUNC_3 (int ,char*,char const*) ;
 int FUNC_4 (int *,char*) ;
 scalar_t__ FUNC_5 (int *) ;
 int FUNC_6 (int *,int ) ;
 int VAR_0 ;
 int * VAR_1 ;
 int VAR_2 ;

int FUNC_7(SSL_CTX *VAR_3, const char *VAR_4)
{

    FUNC_1(VAR_1);
    VAR_1 = ((void*)0);

    if (VAR_3 == ((void*)0) || VAR_4 == ((void*)0)) {

        return 0;
    }






    VAR_1 = FUNC_2(VAR_4, "a");
    if (VAR_1 == ((void*)0)) {
        FUNC_3(VAR_0, "Error writing keylog file %s\n", VAR_4);
        return 1;
    }


    if (FUNC_5(VAR_1) == 0) {
        FUNC_4(VAR_1,
                 "# SSL/TLS secrets log file, generated by OpenSSL\n");
        (void)FUNC_0(VAR_1);
    }
    FUNC_6(VAR_3, VAR_2);
    return 0;
}
