
typedef unsigned long size_t;
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;

typedef int bool;






typedef scalar_t__ PFNGLVERTEXWEIGHTHVNVPROC ;
typedef scalar_t__ PFNGLVERTEXWEIGHTHNVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIBS4HVNVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIBS3HVNVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIBS2HVNVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIBS1HVNVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIB4HVNVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIB4HNVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIB3HVNVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIB3HNVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIB2HVNVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIB2HNVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIB1HVNVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIB1HNVPROC ;
typedef scalar_t__ PFNGLVERTEX4HVNVPROC ;
typedef scalar_t__ PFNGLVERTEX4HNVPROC ;
typedef scalar_t__ PFNGLVERTEX3HVNVPROC ;
typedef scalar_t__ PFNGLVERTEX3HNVPROC ;
typedef scalar_t__ PFNGLVERTEX2HVNVPROC ;
typedef scalar_t__ PFNGLVERTEX2HNVPROC ;
typedef scalar_t__ PFNGLTEXCOORD4HVNVPROC ;
typedef scalar_t__ PFNGLTEXCOORD4HNVPROC ;
typedef scalar_t__ PFNGLTEXCOORD3HVNVPROC ;
typedef scalar_t__ PFNGLTEXCOORD3HNVPROC ;
typedef scalar_t__ PFNGLTEXCOORD2HVNVPROC ;
typedef scalar_t__ PFNGLTEXCOORD2HNVPROC ;
typedef scalar_t__ PFNGLTEXCOORD1HVNVPROC ;
typedef scalar_t__ PFNGLTEXCOORD1HNVPROC ;
typedef scalar_t__ PFNGLSECONDARYCOLOR3HVNVPROC ;
typedef scalar_t__ PFNGLSECONDARYCOLOR3HNVPROC ;
typedef scalar_t__ PFNGLNORMAL3HVNVPROC ;
typedef scalar_t__ PFNGLNORMAL3HNVPROC ;
typedef scalar_t__ PFNGLMULTITEXCOORD4HVNVPROC ;
typedef scalar_t__ PFNGLMULTITEXCOORD4HNVPROC ;
typedef scalar_t__ PFNGLMULTITEXCOORD3HVNVPROC ;
typedef scalar_t__ PFNGLMULTITEXCOORD3HNVPROC ;
typedef scalar_t__ PFNGLMULTITEXCOORD2HVNVPROC ;
typedef scalar_t__ PFNGLMULTITEXCOORD2HNVPROC ;
typedef scalar_t__ PFNGLMULTITEXCOORD1HVNVPROC ;
typedef scalar_t__ PFNGLMULTITEXCOORD1HNVPROC ;
typedef scalar_t__ PFNGLFOGCOORDHVNVPROC ;
typedef scalar_t__ PFNGLFOGCOORDHNVPROC ;
typedef scalar_t__ PFNGLCOLOR4HVNVPROC ;
typedef scalar_t__ PFNGLCOLOR4HNVPROC ;
typedef scalar_t__ PFNGLCOLOR3HVNVPROC ;
typedef scalar_t__ PFNGLCOLOR3HNVPROC ;


 scalar_t__ FUNC_0 (char*) ;
 scalar_t__ VAR_0 ;
 scalar_t__ VAR_1 ;
 scalar_t__ VAR_2 ;
 scalar_t__ VAR_3 ;
 scalar_t__ VAR_4 ;
 scalar_t__ VAR_5 ;
 scalar_t__ VAR_6 ;
 scalar_t__ VAR_7 ;
 scalar_t__ VAR_8 ;
 scalar_t__ VAR_9 ;
 scalar_t__ VAR_10 ;
 scalar_t__ VAR_11 ;
 scalar_t__ VAR_12 ;
 scalar_t__ VAR_13 ;
 scalar_t__ VAR_14 ;
 scalar_t__ VAR_15 ;
 scalar_t__ VAR_16 ;
 scalar_t__ VAR_17 ;
 scalar_t__ VAR_18 ;
 scalar_t__ VAR_19 ;
 scalar_t__ VAR_20 ;
 scalar_t__ VAR_21 ;
 scalar_t__ VAR_22 ;
 scalar_t__ VAR_23 ;
 scalar_t__ VAR_24 ;
 scalar_t__ VAR_25 ;
 scalar_t__ VAR_26 ;
 scalar_t__ VAR_27 ;
 scalar_t__ VAR_28 ;
 scalar_t__ VAR_29 ;
 scalar_t__ VAR_30 ;
 scalar_t__ VAR_31 ;
 scalar_t__ VAR_32 ;
 scalar_t__ VAR_33 ;
 scalar_t__ VAR_34 ;
 scalar_t__ VAR_35 ;
 scalar_t__ VAR_36 ;
 scalar_t__ VAR_37 ;
 scalar_t__ VAR_38 ;
 scalar_t__ VAR_39 ;
 scalar_t__ VAR_40 ;
 scalar_t__ VAR_41 ;
 scalar_t__ VAR_42 ;
 scalar_t__ VAR_43 ;
 scalar_t__ VAR_44 ;
 scalar_t__ VAR_45 ;

__attribute__((used)) static int FUNC_1()
{
 int VAR_46 = 0;
 VAR_0 = (PFNGLCOLOR3HNVPROC)FUNC_0("glColor3hNV");
 if(!VAR_0) ++VAR_46;
 VAR_1 = (PFNGLCOLOR3HVNVPROC)FUNC_0("glColor3hvNV");
 if(!VAR_1) ++VAR_46;
 VAR_2 = (PFNGLCOLOR4HNVPROC)FUNC_0("glColor4hNV");
 if(!VAR_2) ++VAR_46;
 VAR_3 = (PFNGLCOLOR4HVNVPROC)FUNC_0("glColor4hvNV");
 if(!VAR_3) ++VAR_46;
 VAR_4 = (PFNGLFOGCOORDHNVPROC)FUNC_0("glFogCoordhNV");
 if(!VAR_4) ++VAR_46;
 VAR_5 = (PFNGLFOGCOORDHVNVPROC)FUNC_0("glFogCoordhvNV");
 if(!VAR_5) ++VAR_46;
 VAR_6 = (PFNGLMULTITEXCOORD1HNVPROC)FUNC_0("glMultiTexCoord1hNV");
 if(!VAR_6) ++VAR_46;
 VAR_7 = (PFNGLMULTITEXCOORD1HVNVPROC)FUNC_0("glMultiTexCoord1hvNV");
 if(!VAR_7) ++VAR_46;
 VAR_8 = (PFNGLMULTITEXCOORD2HNVPROC)FUNC_0("glMultiTexCoord2hNV");
 if(!VAR_8) ++VAR_46;
 VAR_9 = (PFNGLMULTITEXCOORD2HVNVPROC)FUNC_0("glMultiTexCoord2hvNV");
 if(!VAR_9) ++VAR_46;
 VAR_10 = (PFNGLMULTITEXCOORD3HNVPROC)FUNC_0("glMultiTexCoord3hNV");
 if(!VAR_10) ++VAR_46;
 VAR_11 = (PFNGLMULTITEXCOORD3HVNVPROC)FUNC_0("glMultiTexCoord3hvNV");
 if(!VAR_11) ++VAR_46;
 VAR_12 = (PFNGLMULTITEXCOORD4HNVPROC)FUNC_0("glMultiTexCoord4hNV");
 if(!VAR_12) ++VAR_46;
 VAR_13 = (PFNGLMULTITEXCOORD4HVNVPROC)FUNC_0("glMultiTexCoord4hvNV");
 if(!VAR_13) ++VAR_46;
 VAR_14 = (PFNGLNORMAL3HNVPROC)FUNC_0("glNormal3hNV");
 if(!VAR_14) ++VAR_46;
 VAR_15 = (PFNGLNORMAL3HVNVPROC)FUNC_0("glNormal3hvNV");
 if(!VAR_15) ++VAR_46;
 VAR_16 = (PFNGLSECONDARYCOLOR3HNVPROC)FUNC_0("glSecondaryColor3hNV");
 if(!VAR_16) ++VAR_46;
 VAR_17 = (PFNGLSECONDARYCOLOR3HVNVPROC)FUNC_0("glSecondaryColor3hvNV");
 if(!VAR_17) ++VAR_46;
 VAR_18 = (PFNGLTEXCOORD1HNVPROC)FUNC_0("glTexCoord1hNV");
 if(!VAR_18) ++VAR_46;
 VAR_19 = (PFNGLTEXCOORD1HVNVPROC)FUNC_0("glTexCoord1hvNV");
 if(!VAR_19) ++VAR_46;
 VAR_20 = (PFNGLTEXCOORD2HNVPROC)FUNC_0("glTexCoord2hNV");
 if(!VAR_20) ++VAR_46;
 VAR_21 = (PFNGLTEXCOORD2HVNVPROC)FUNC_0("glTexCoord2hvNV");
 if(!VAR_21) ++VAR_46;
 VAR_22 = (PFNGLTEXCOORD3HNVPROC)FUNC_0("glTexCoord3hNV");
 if(!VAR_22) ++VAR_46;
 VAR_23 = (PFNGLTEXCOORD3HVNVPROC)FUNC_0("glTexCoord3hvNV");
 if(!VAR_23) ++VAR_46;
 VAR_24 = (PFNGLTEXCOORD4HNVPROC)FUNC_0("glTexCoord4hNV");
 if(!VAR_24) ++VAR_46;
 VAR_25 = (PFNGLTEXCOORD4HVNVPROC)FUNC_0("glTexCoord4hvNV");
 if(!VAR_25) ++VAR_46;
 VAR_26 = (PFNGLVERTEX2HNVPROC)FUNC_0("glVertex2hNV");
 if(!VAR_26) ++VAR_46;
 VAR_27 = (PFNGLVERTEX2HVNVPROC)FUNC_0("glVertex2hvNV");
 if(!VAR_27) ++VAR_46;
 VAR_28 = (PFNGLVERTEX3HNVPROC)FUNC_0("glVertex3hNV");
 if(!VAR_28) ++VAR_46;
 VAR_29 = (PFNGLVERTEX3HVNVPROC)FUNC_0("glVertex3hvNV");
 if(!VAR_29) ++VAR_46;
 VAR_30 = (PFNGLVERTEX4HNVPROC)FUNC_0("glVertex4hNV");
 if(!VAR_30) ++VAR_46;
 VAR_31 = (PFNGLVERTEX4HVNVPROC)FUNC_0("glVertex4hvNV");
 if(!VAR_31) ++VAR_46;
 VAR_32 = (PFNGLVERTEXATTRIB1HNVPROC)FUNC_0("glVertexAttrib1hNV");
 if(!VAR_32) ++VAR_46;
 VAR_33 = (PFNGLVERTEXATTRIB1HVNVPROC)FUNC_0("glVertexAttrib1hvNV");
 if(!VAR_33) ++VAR_46;
 VAR_34 = (PFNGLVERTEXATTRIB2HNVPROC)FUNC_0("glVertexAttrib2hNV");
 if(!VAR_34) ++VAR_46;
 VAR_35 = (PFNGLVERTEXATTRIB2HVNVPROC)FUNC_0("glVertexAttrib2hvNV");
 if(!VAR_35) ++VAR_46;
 VAR_36 = (PFNGLVERTEXATTRIB3HNVPROC)FUNC_0("glVertexAttrib3hNV");
 if(!VAR_36) ++VAR_46;
 VAR_37 = (PFNGLVERTEXATTRIB3HVNVPROC)FUNC_0("glVertexAttrib3hvNV");
 if(!VAR_37) ++VAR_46;
 VAR_38 = (PFNGLVERTEXATTRIB4HNVPROC)FUNC_0("glVertexAttrib4hNV");
 if(!VAR_38) ++VAR_46;
 VAR_39 = (PFNGLVERTEXATTRIB4HVNVPROC)FUNC_0("glVertexAttrib4hvNV");
 if(!VAR_39) ++VAR_46;
 VAR_40 = (PFNGLVERTEXATTRIBS1HVNVPROC)FUNC_0("glVertexAttribs1hvNV");
 if(!VAR_40) ++VAR_46;
 VAR_41 = (PFNGLVERTEXATTRIBS2HVNVPROC)FUNC_0("glVertexAttribs2hvNV");
 if(!VAR_41) ++VAR_46;
 VAR_42 = (PFNGLVERTEXATTRIBS3HVNVPROC)FUNC_0("glVertexAttribs3hvNV");
 if(!VAR_42) ++VAR_46;
 VAR_43 = (PFNGLVERTEXATTRIBS4HVNVPROC)FUNC_0("glVertexAttribs4hvNV");
 if(!VAR_43) ++VAR_46;
 VAR_44 = (PFNGLVERTEXWEIGHTHNVPROC)FUNC_0("glVertexWeighthNV");
 if(!VAR_44) ++VAR_46;
 VAR_45 = (PFNGLVERTEXWEIGHTHVNVPROC)FUNC_0("glVertexWeighthvNV");
 if(!VAR_45) ++VAR_46;
 return VAR_46;
}
