
typedef unsigned long size_t;
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;

typedef int bool;






typedef scalar_t__ PFNGLVIEWPORTPROC ;
typedef scalar_t__ PFNGLTEXPARAMETERIVPROC ;
typedef scalar_t__ PFNGLTEXPARAMETERIPROC ;
typedef scalar_t__ PFNGLTEXPARAMETERFVPROC ;
typedef scalar_t__ PFNGLTEXPARAMETERFPROC ;
typedef scalar_t__ PFNGLTEXIMAGE2DPROC ;
typedef scalar_t__ PFNGLTEXIMAGE1DPROC ;
typedef scalar_t__ PFNGLSTENCILOPPROC ;
typedef scalar_t__ PFNGLSTENCILMASKPROC ;
typedef scalar_t__ PFNGLSTENCILFUNCPROC ;
typedef scalar_t__ PFNGLSCISSORPROC ;
typedef scalar_t__ PFNGLREADPIXELSPROC ;
typedef scalar_t__ PFNGLREADBUFFERPROC ;
typedef scalar_t__ PFNGLPOLYGONMODEPROC ;
typedef scalar_t__ PFNGLPOINTSIZEPROC ;
typedef scalar_t__ PFNGLPIXELSTOREIPROC ;
typedef scalar_t__ PFNGLPIXELSTOREFPROC ;
typedef scalar_t__ PFNGLLOGICOPPROC ;
typedef scalar_t__ PFNGLLINEWIDTHPROC ;
typedef scalar_t__ PFNGLISENABLEDPROC ;
typedef scalar_t__ PFNGLHINTPROC ;
typedef scalar_t__ PFNGLGETTEXPARAMETERIVPROC ;
typedef scalar_t__ PFNGLGETTEXPARAMETERFVPROC ;
typedef scalar_t__ PFNGLGETTEXLEVELPARAMETERIVPROC ;
typedef scalar_t__ PFNGLGETTEXLEVELPARAMETERFVPROC ;
typedef scalar_t__ PFNGLGETTEXIMAGEPROC ;
typedef scalar_t__ PFNGLGETSTRINGPROC ;
typedef scalar_t__ PFNGLGETINTEGERVPROC ;
typedef scalar_t__ PFNGLGETFLOATVPROC ;
typedef scalar_t__ PFNGLGETERRORPROC ;
typedef scalar_t__ PFNGLGETDOUBLEVPROC ;
typedef scalar_t__ PFNGLGETBOOLEANVPROC ;
typedef scalar_t__ PFNGLFRONTFACEPROC ;
typedef scalar_t__ PFNGLFLUSHPROC ;
typedef scalar_t__ PFNGLFINISHPROC ;
typedef scalar_t__ PFNGLENABLEPROC ;
typedef scalar_t__ PFNGLDRAWBUFFERPROC ;
typedef scalar_t__ PFNGLDISABLEPROC ;
typedef scalar_t__ PFNGLDEPTHRANGEPROC ;
typedef scalar_t__ PFNGLDEPTHMASKPROC ;
typedef scalar_t__ PFNGLDEPTHFUNCPROC ;
typedef scalar_t__ PFNGLCULLFACEPROC ;
typedef scalar_t__ PFNGLCOLORMASKPROC ;
typedef scalar_t__ PFNGLCLEARSTENCILPROC ;
typedef scalar_t__ PFNGLCLEARPROC ;
typedef scalar_t__ PFNGLCLEARDEPTHPROC ;
typedef scalar_t__ PFNGLCLEARCOLORPROC ;
typedef scalar_t__ PFNGLBLENDFUNCPROC ;


 scalar_t__ FUNC_0 (char*) ;
 scalar_t__ VAR_0 ;
 scalar_t__ VAR_1 ;
 scalar_t__ VAR_2 ;
 scalar_t__ VAR_3 ;
 scalar_t__ VAR_4 ;
 scalar_t__ VAR_5 ;
 scalar_t__ VAR_6 ;
 scalar_t__ VAR_7 ;
 scalar_t__ VAR_8 ;
 scalar_t__ VAR_9 ;
 scalar_t__ VAR_10 ;
 scalar_t__ VAR_11 ;
 scalar_t__ VAR_12 ;
 scalar_t__ VAR_13 ;
 scalar_t__ VAR_14 ;
 scalar_t__ VAR_15 ;
 scalar_t__ VAR_16 ;
 scalar_t__ VAR_17 ;
 scalar_t__ VAR_18 ;
 scalar_t__ VAR_19 ;
 scalar_t__ VAR_20 ;
 scalar_t__ VAR_21 ;
 scalar_t__ VAR_22 ;
 scalar_t__ VAR_23 ;
 scalar_t__ VAR_24 ;
 scalar_t__ VAR_25 ;
 scalar_t__ VAR_26 ;
 scalar_t__ VAR_27 ;
 scalar_t__ VAR_28 ;
 scalar_t__ VAR_29 ;
 scalar_t__ VAR_30 ;
 scalar_t__ VAR_31 ;
 scalar_t__ VAR_32 ;
 scalar_t__ VAR_33 ;
 scalar_t__ VAR_34 ;
 scalar_t__ VAR_35 ;
 scalar_t__ VAR_36 ;
 scalar_t__ VAR_37 ;
 scalar_t__ VAR_38 ;
 scalar_t__ VAR_39 ;
 scalar_t__ VAR_40 ;
 scalar_t__ VAR_41 ;
 scalar_t__ VAR_42 ;
 scalar_t__ VAR_43 ;
 scalar_t__ VAR_44 ;
 scalar_t__ VAR_45 ;
 scalar_t__ VAR_46 ;
 scalar_t__ VAR_47 ;

__attribute__((used)) static int FUNC_1()
{
 int VAR_48 = 0;
 VAR_0 = (PFNGLBLENDFUNCPROC)FUNC_0("glBlendFunc");
 if(!VAR_0) ++VAR_48;
 VAR_1 = (PFNGLCLEARPROC)FUNC_0("glClear");
 if(!VAR_1) ++VAR_48;
 VAR_2 = (PFNGLCLEARCOLORPROC)FUNC_0("glClearColor");
 if(!VAR_2) ++VAR_48;
 VAR_3 = (PFNGLCLEARDEPTHPROC)FUNC_0("glClearDepth");
 if(!VAR_3) ++VAR_48;
 VAR_4 = (PFNGLCLEARSTENCILPROC)FUNC_0("glClearStencil");
 if(!VAR_4) ++VAR_48;
 VAR_5 = (PFNGLCOLORMASKPROC)FUNC_0("glColorMask");
 if(!VAR_5) ++VAR_48;
 VAR_6 = (PFNGLCULLFACEPROC)FUNC_0("glCullFace");
 if(!VAR_6) ++VAR_48;
 VAR_7 = (PFNGLDEPTHFUNCPROC)FUNC_0("glDepthFunc");
 if(!VAR_7) ++VAR_48;
 VAR_8 = (PFNGLDEPTHMASKPROC)FUNC_0("glDepthMask");
 if(!VAR_8) ++VAR_48;
 VAR_9 = (PFNGLDEPTHRANGEPROC)FUNC_0("glDepthRange");
 if(!VAR_9) ++VAR_48;
 VAR_10 = (PFNGLDISABLEPROC)FUNC_0("glDisable");
 if(!VAR_10) ++VAR_48;
 VAR_11 = (PFNGLDRAWBUFFERPROC)FUNC_0("glDrawBuffer");
 if(!VAR_11) ++VAR_48;
 VAR_12 = (PFNGLENABLEPROC)FUNC_0("glEnable");
 if(!VAR_12) ++VAR_48;
 VAR_13 = (PFNGLFINISHPROC)FUNC_0("glFinish");
 if(!VAR_13) ++VAR_48;
 VAR_14 = (PFNGLFLUSHPROC)FUNC_0("glFlush");
 if(!VAR_14) ++VAR_48;
 VAR_15 = (PFNGLFRONTFACEPROC)FUNC_0("glFrontFace");
 if(!VAR_15) ++VAR_48;
 VAR_16 = (PFNGLGETBOOLEANVPROC)FUNC_0("glGetBooleanv");
 if(!VAR_16) ++VAR_48;
 VAR_17 = (PFNGLGETDOUBLEVPROC)FUNC_0("glGetDoublev");
 if(!VAR_17) ++VAR_48;
 VAR_18 = (PFNGLGETERRORPROC)FUNC_0("glGetError");
 if(!VAR_18) ++VAR_48;
 VAR_19 = (PFNGLGETFLOATVPROC)FUNC_0("glGetFloatv");
 if(!VAR_19) ++VAR_48;
 VAR_20 = (PFNGLGETINTEGERVPROC)FUNC_0("glGetIntegerv");
 if(!VAR_20) ++VAR_48;
 VAR_21 = (PFNGLGETSTRINGPROC)FUNC_0("glGetString");
 if(!VAR_21) ++VAR_48;
 VAR_22 = (PFNGLGETTEXIMAGEPROC)FUNC_0("glGetTexImage");
 if(!VAR_22) ++VAR_48;
 VAR_23 = (PFNGLGETTEXLEVELPARAMETERFVPROC)FUNC_0("glGetTexLevelParameterfv");
 if(!VAR_23) ++VAR_48;
 VAR_24 = (PFNGLGETTEXLEVELPARAMETERIVPROC)FUNC_0("glGetTexLevelParameteriv");
 if(!VAR_24) ++VAR_48;
 VAR_25 = (PFNGLGETTEXPARAMETERFVPROC)FUNC_0("glGetTexParameterfv");
 if(!VAR_25) ++VAR_48;
 VAR_26 = (PFNGLGETTEXPARAMETERIVPROC)FUNC_0("glGetTexParameteriv");
 if(!VAR_26) ++VAR_48;
 VAR_27 = (PFNGLHINTPROC)FUNC_0("glHint");
 if(!VAR_27) ++VAR_48;
 VAR_28 = (PFNGLISENABLEDPROC)FUNC_0("glIsEnabled");
 if(!VAR_28) ++VAR_48;
 VAR_29 = (PFNGLLINEWIDTHPROC)FUNC_0("glLineWidth");
 if(!VAR_29) ++VAR_48;
 VAR_30 = (PFNGLLOGICOPPROC)FUNC_0("glLogicOp");
 if(!VAR_30) ++VAR_48;
 VAR_31 = (PFNGLPIXELSTOREFPROC)FUNC_0("glPixelStoref");
 if(!VAR_31) ++VAR_48;
 VAR_32 = (PFNGLPIXELSTOREIPROC)FUNC_0("glPixelStorei");
 if(!VAR_32) ++VAR_48;
 VAR_33 = (PFNGLPOINTSIZEPROC)FUNC_0("glPointSize");
 if(!VAR_33) ++VAR_48;
 VAR_34 = (PFNGLPOLYGONMODEPROC)FUNC_0("glPolygonMode");
 if(!VAR_34) ++VAR_48;
 VAR_35 = (PFNGLREADBUFFERPROC)FUNC_0("glReadBuffer");
 if(!VAR_35) ++VAR_48;
 VAR_36 = (PFNGLREADPIXELSPROC)FUNC_0("glReadPixels");
 if(!VAR_36) ++VAR_48;
 VAR_37 = (PFNGLSCISSORPROC)FUNC_0("glScissor");
 if(!VAR_37) ++VAR_48;
 VAR_38 = (PFNGLSTENCILFUNCPROC)FUNC_0("glStencilFunc");
 if(!VAR_38) ++VAR_48;
 VAR_39 = (PFNGLSTENCILMASKPROC)FUNC_0("glStencilMask");
 if(!VAR_39) ++VAR_48;
 VAR_40 = (PFNGLSTENCILOPPROC)FUNC_0("glStencilOp");
 if(!VAR_40) ++VAR_48;
 VAR_41 = (PFNGLTEXIMAGE1DPROC)FUNC_0("glTexImage1D");
 if(!VAR_41) ++VAR_48;
 VAR_42 = (PFNGLTEXIMAGE2DPROC)FUNC_0("glTexImage2D");
 if(!VAR_42) ++VAR_48;
 VAR_43 = (PFNGLTEXPARAMETERFPROC)FUNC_0("glTexParameterf");
 if(!VAR_43) ++VAR_48;
 VAR_44 = (PFNGLTEXPARAMETERFVPROC)FUNC_0("glTexParameterfv");
 if(!VAR_44) ++VAR_48;
 VAR_45 = (PFNGLTEXPARAMETERIPROC)FUNC_0("glTexParameteri");
 if(!VAR_45) ++VAR_48;
 VAR_46 = (PFNGLTEXPARAMETERIVPROC)FUNC_0("glTexParameteriv");
 if(!VAR_46) ++VAR_48;
 VAR_47 = (PFNGLVIEWPORTPROC)FUNC_0("glViewport");
 if(!VAR_47) ++VAR_48;
 return VAR_48;
}
