
typedef unsigned long size_t;
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;

typedef int bool;






typedef scalar_t__ PFNGLVERTEXP4UIVPROC ;
typedef scalar_t__ PFNGLVERTEXP4UIPROC ;
typedef scalar_t__ PFNGLVERTEXP3UIVPROC ;
typedef scalar_t__ PFNGLVERTEXP3UIPROC ;
typedef scalar_t__ PFNGLVERTEXP2UIVPROC ;
typedef scalar_t__ PFNGLVERTEXP2UIPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIBP4UIVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIBP4UIPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIBP3UIVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIBP3UIPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIBP2UIVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIBP2UIPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIBP1UIVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIBP1UIPROC ;
typedef scalar_t__ PFNGLTEXCOORDP4UIVPROC ;
typedef scalar_t__ PFNGLTEXCOORDP4UIPROC ;
typedef scalar_t__ PFNGLTEXCOORDP3UIVPROC ;
typedef scalar_t__ PFNGLTEXCOORDP3UIPROC ;
typedef scalar_t__ PFNGLTEXCOORDP2UIVPROC ;
typedef scalar_t__ PFNGLTEXCOORDP2UIPROC ;
typedef scalar_t__ PFNGLTEXCOORDP1UIVPROC ;
typedef scalar_t__ PFNGLTEXCOORDP1UIPROC ;
typedef scalar_t__ PFNGLSECONDARYCOLORP3UIVPROC ;
typedef scalar_t__ PFNGLSECONDARYCOLORP3UIPROC ;
typedef scalar_t__ PFNGLNORMALP3UIVPROC ;
typedef scalar_t__ PFNGLNORMALP3UIPROC ;
typedef scalar_t__ PFNGLMULTITEXCOORDP4UIVPROC ;
typedef scalar_t__ PFNGLMULTITEXCOORDP4UIPROC ;
typedef scalar_t__ PFNGLMULTITEXCOORDP3UIVPROC ;
typedef scalar_t__ PFNGLMULTITEXCOORDP3UIPROC ;
typedef scalar_t__ PFNGLMULTITEXCOORDP2UIVPROC ;
typedef scalar_t__ PFNGLMULTITEXCOORDP2UIPROC ;
typedef scalar_t__ PFNGLMULTITEXCOORDP1UIVPROC ;
typedef scalar_t__ PFNGLMULTITEXCOORDP1UIPROC ;
typedef scalar_t__ PFNGLCOLORP4UIVPROC ;
typedef scalar_t__ PFNGLCOLORP4UIPROC ;
typedef scalar_t__ PFNGLCOLORP3UIVPROC ;
typedef scalar_t__ PFNGLCOLORP3UIPROC ;


 scalar_t__ FUNC_0 (char*) ;
 scalar_t__ VAR_0 ;
 scalar_t__ VAR_1 ;
 scalar_t__ VAR_2 ;
 scalar_t__ VAR_3 ;
 scalar_t__ VAR_4 ;
 scalar_t__ VAR_5 ;
 scalar_t__ VAR_6 ;
 scalar_t__ VAR_7 ;
 scalar_t__ VAR_8 ;
 scalar_t__ VAR_9 ;
 scalar_t__ VAR_10 ;
 scalar_t__ VAR_11 ;
 scalar_t__ VAR_12 ;
 scalar_t__ VAR_13 ;
 scalar_t__ VAR_14 ;
 scalar_t__ VAR_15 ;
 scalar_t__ VAR_16 ;
 scalar_t__ VAR_17 ;
 scalar_t__ VAR_18 ;
 scalar_t__ VAR_19 ;
 scalar_t__ VAR_20 ;
 scalar_t__ VAR_21 ;
 scalar_t__ VAR_22 ;
 scalar_t__ VAR_23 ;
 scalar_t__ VAR_24 ;
 scalar_t__ VAR_25 ;
 scalar_t__ VAR_26 ;
 scalar_t__ VAR_27 ;
 scalar_t__ VAR_28 ;
 scalar_t__ VAR_29 ;
 scalar_t__ VAR_30 ;
 scalar_t__ VAR_31 ;
 scalar_t__ VAR_32 ;
 scalar_t__ VAR_33 ;
 scalar_t__ VAR_34 ;
 scalar_t__ VAR_35 ;
 scalar_t__ VAR_36 ;
 scalar_t__ VAR_37 ;

__attribute__((used)) static int FUNC_1()
{
 int VAR_38 = 0;
 VAR_0 = (PFNGLCOLORP3UIPROC)FUNC_0("glColorP3ui");
 if(!VAR_0) ++VAR_38;
 VAR_1 = (PFNGLCOLORP3UIVPROC)FUNC_0("glColorP3uiv");
 if(!VAR_1) ++VAR_38;
 VAR_2 = (PFNGLCOLORP4UIPROC)FUNC_0("glColorP4ui");
 if(!VAR_2) ++VAR_38;
 VAR_3 = (PFNGLCOLORP4UIVPROC)FUNC_0("glColorP4uiv");
 if(!VAR_3) ++VAR_38;
 VAR_4 = (PFNGLMULTITEXCOORDP1UIPROC)FUNC_0("glMultiTexCoordP1ui");
 if(!VAR_4) ++VAR_38;
 VAR_5 = (PFNGLMULTITEXCOORDP1UIVPROC)FUNC_0("glMultiTexCoordP1uiv");
 if(!VAR_5) ++VAR_38;
 VAR_6 = (PFNGLMULTITEXCOORDP2UIPROC)FUNC_0("glMultiTexCoordP2ui");
 if(!VAR_6) ++VAR_38;
 VAR_7 = (PFNGLMULTITEXCOORDP2UIVPROC)FUNC_0("glMultiTexCoordP2uiv");
 if(!VAR_7) ++VAR_38;
 VAR_8 = (PFNGLMULTITEXCOORDP3UIPROC)FUNC_0("glMultiTexCoordP3ui");
 if(!VAR_8) ++VAR_38;
 VAR_9 = (PFNGLMULTITEXCOORDP3UIVPROC)FUNC_0("glMultiTexCoordP3uiv");
 if(!VAR_9) ++VAR_38;
 VAR_10 = (PFNGLMULTITEXCOORDP4UIPROC)FUNC_0("glMultiTexCoordP4ui");
 if(!VAR_10) ++VAR_38;
 VAR_11 = (PFNGLMULTITEXCOORDP4UIVPROC)FUNC_0("glMultiTexCoordP4uiv");
 if(!VAR_11) ++VAR_38;
 VAR_12 = (PFNGLNORMALP3UIPROC)FUNC_0("glNormalP3ui");
 if(!VAR_12) ++VAR_38;
 VAR_13 = (PFNGLNORMALP3UIVPROC)FUNC_0("glNormalP3uiv");
 if(!VAR_13) ++VAR_38;
 VAR_14 = (PFNGLSECONDARYCOLORP3UIPROC)FUNC_0("glSecondaryColorP3ui");
 if(!VAR_14) ++VAR_38;
 VAR_15 = (PFNGLSECONDARYCOLORP3UIVPROC)FUNC_0("glSecondaryColorP3uiv");
 if(!VAR_15) ++VAR_38;
 VAR_16 = (PFNGLTEXCOORDP1UIPROC)FUNC_0("glTexCoordP1ui");
 if(!VAR_16) ++VAR_38;
 VAR_17 = (PFNGLTEXCOORDP1UIVPROC)FUNC_0("glTexCoordP1uiv");
 if(!VAR_17) ++VAR_38;
 VAR_18 = (PFNGLTEXCOORDP2UIPROC)FUNC_0("glTexCoordP2ui");
 if(!VAR_18) ++VAR_38;
 VAR_19 = (PFNGLTEXCOORDP2UIVPROC)FUNC_0("glTexCoordP2uiv");
 if(!VAR_19) ++VAR_38;
 VAR_20 = (PFNGLTEXCOORDP3UIPROC)FUNC_0("glTexCoordP3ui");
 if(!VAR_20) ++VAR_38;
 VAR_21 = (PFNGLTEXCOORDP3UIVPROC)FUNC_0("glTexCoordP3uiv");
 if(!VAR_21) ++VAR_38;
 VAR_22 = (PFNGLTEXCOORDP4UIPROC)FUNC_0("glTexCoordP4ui");
 if(!VAR_22) ++VAR_38;
 VAR_23 = (PFNGLTEXCOORDP4UIVPROC)FUNC_0("glTexCoordP4uiv");
 if(!VAR_23) ++VAR_38;
 VAR_24 = (PFNGLVERTEXATTRIBP1UIPROC)FUNC_0("glVertexAttribP1ui");
 if(!VAR_24) ++VAR_38;
 VAR_25 = (PFNGLVERTEXATTRIBP1UIVPROC)FUNC_0("glVertexAttribP1uiv");
 if(!VAR_25) ++VAR_38;
 VAR_26 = (PFNGLVERTEXATTRIBP2UIPROC)FUNC_0("glVertexAttribP2ui");
 if(!VAR_26) ++VAR_38;
 VAR_27 = (PFNGLVERTEXATTRIBP2UIVPROC)FUNC_0("glVertexAttribP2uiv");
 if(!VAR_27) ++VAR_38;
 VAR_28 = (PFNGLVERTEXATTRIBP3UIPROC)FUNC_0("glVertexAttribP3ui");
 if(!VAR_28) ++VAR_38;
 VAR_29 = (PFNGLVERTEXATTRIBP3UIVPROC)FUNC_0("glVertexAttribP3uiv");
 if(!VAR_29) ++VAR_38;
 VAR_30 = (PFNGLVERTEXATTRIBP4UIPROC)FUNC_0("glVertexAttribP4ui");
 if(!VAR_30) ++VAR_38;
 VAR_31 = (PFNGLVERTEXATTRIBP4UIVPROC)FUNC_0("glVertexAttribP4uiv");
 if(!VAR_31) ++VAR_38;
 VAR_32 = (PFNGLVERTEXP2UIPROC)FUNC_0("glVertexP2ui");
 if(!VAR_32) ++VAR_38;
 VAR_33 = (PFNGLVERTEXP2UIVPROC)FUNC_0("glVertexP2uiv");
 if(!VAR_33) ++VAR_38;
 VAR_34 = (PFNGLVERTEXP3UIPROC)FUNC_0("glVertexP3ui");
 if(!VAR_34) ++VAR_38;
 VAR_35 = (PFNGLVERTEXP3UIVPROC)FUNC_0("glVertexP3uiv");
 if(!VAR_35) ++VAR_38;
 VAR_36 = (PFNGLVERTEXP4UIPROC)FUNC_0("glVertexP4ui");
 if(!VAR_36) ++VAR_38;
 VAR_37 = (PFNGLVERTEXP4UIVPROC)FUNC_0("glVertexP4uiv");
 if(!VAR_37) ++VAR_38;
 return VAR_38;
}
