
typedef unsigned long size_t;
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;

typedef int bool;






typedef scalar_t__ PFNGLVERTEXATTRIBS4UBVNVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIBS4SVNVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIBS4FVNVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIBS4DVNVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIBS3SVNVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIBS3FVNVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIBS3DVNVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIBS2SVNVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIBS2FVNVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIBS2DVNVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIBS1SVNVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIBS1FVNVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIBS1DVNVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIBPOINTERNVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIB4UBVNVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIB4UBNVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIB4SVNVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIB4SNVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIB4FVNVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIB4FNVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIB4DVNVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIB4DNVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIB3SVNVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIB3SNVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIB3FVNVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIB3FNVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIB3DVNVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIB3DNVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIB2SVNVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIB2SNVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIB2FVNVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIB2FNVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIB2DVNVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIB2DNVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIB1SVNVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIB1SNVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIB1FVNVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIB1FNVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIB1DVNVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIB1DNVPROC ;
typedef scalar_t__ PFNGLTRACKMATRIXNVPROC ;
typedef scalar_t__ PFNGLREQUESTRESIDENTPROGRAMSNVPROC ;
typedef scalar_t__ PFNGLPROGRAMPARAMETERS4FVNVPROC ;
typedef scalar_t__ PFNGLPROGRAMPARAMETERS4DVNVPROC ;
typedef scalar_t__ PFNGLPROGRAMPARAMETER4FVNVPROC ;
typedef scalar_t__ PFNGLPROGRAMPARAMETER4FNVPROC ;
typedef scalar_t__ PFNGLPROGRAMPARAMETER4DVNVPROC ;
typedef scalar_t__ PFNGLPROGRAMPARAMETER4DNVPROC ;
typedef scalar_t__ PFNGLLOADPROGRAMNVPROC ;
typedef scalar_t__ PFNGLISPROGRAMNVPROC ;
typedef scalar_t__ PFNGLGETVERTEXATTRIBPOINTERVNVPROC ;
typedef scalar_t__ PFNGLGETVERTEXATTRIBIVNVPROC ;
typedef scalar_t__ PFNGLGETVERTEXATTRIBFVNVPROC ;
typedef scalar_t__ PFNGLGETVERTEXATTRIBDVNVPROC ;
typedef scalar_t__ PFNGLGETTRACKMATRIXIVNVPROC ;
typedef scalar_t__ PFNGLGETPROGRAMSTRINGNVPROC ;
typedef scalar_t__ PFNGLGETPROGRAMPARAMETERFVNVPROC ;
typedef scalar_t__ PFNGLGETPROGRAMPARAMETERDVNVPROC ;
typedef scalar_t__ PFNGLGETPROGRAMIVNVPROC ;
typedef scalar_t__ PFNGLGENPROGRAMSNVPROC ;
typedef scalar_t__ PFNGLEXECUTEPROGRAMNVPROC ;
typedef scalar_t__ PFNGLDELETEPROGRAMSNVPROC ;
typedef scalar_t__ PFNGLBINDPROGRAMNVPROC ;
typedef scalar_t__ PFNGLAREPROGRAMSRESIDENTNVPROC ;


 scalar_t__ FUNC_0 (char*) ;
 scalar_t__ VAR_0 ;
 scalar_t__ VAR_1 ;
 scalar_t__ VAR_2 ;
 scalar_t__ VAR_3 ;
 scalar_t__ VAR_4 ;
 scalar_t__ VAR_5 ;
 scalar_t__ VAR_6 ;
 scalar_t__ VAR_7 ;
 scalar_t__ VAR_8 ;
 scalar_t__ VAR_9 ;
 scalar_t__ VAR_10 ;
 scalar_t__ VAR_11 ;
 scalar_t__ VAR_12 ;
 scalar_t__ VAR_13 ;
 scalar_t__ VAR_14 ;
 scalar_t__ VAR_15 ;
 scalar_t__ VAR_16 ;
 scalar_t__ VAR_17 ;
 scalar_t__ VAR_18 ;
 scalar_t__ VAR_19 ;
 scalar_t__ VAR_20 ;
 scalar_t__ VAR_21 ;
 scalar_t__ VAR_22 ;
 scalar_t__ VAR_23 ;
 scalar_t__ VAR_24 ;
 scalar_t__ VAR_25 ;
 scalar_t__ VAR_26 ;
 scalar_t__ VAR_27 ;
 scalar_t__ VAR_28 ;
 scalar_t__ VAR_29 ;
 scalar_t__ VAR_30 ;
 scalar_t__ VAR_31 ;
 scalar_t__ VAR_32 ;
 scalar_t__ VAR_33 ;
 scalar_t__ VAR_34 ;
 scalar_t__ VAR_35 ;
 scalar_t__ VAR_36 ;
 scalar_t__ VAR_37 ;
 scalar_t__ VAR_38 ;
 scalar_t__ VAR_39 ;
 scalar_t__ VAR_40 ;
 scalar_t__ VAR_41 ;
 scalar_t__ VAR_42 ;
 scalar_t__ VAR_43 ;
 scalar_t__ VAR_44 ;
 scalar_t__ VAR_45 ;
 scalar_t__ VAR_46 ;
 scalar_t__ VAR_47 ;
 scalar_t__ VAR_48 ;
 scalar_t__ VAR_49 ;
 scalar_t__ VAR_50 ;
 scalar_t__ VAR_51 ;
 scalar_t__ VAR_52 ;
 scalar_t__ VAR_53 ;
 scalar_t__ VAR_54 ;
 scalar_t__ VAR_55 ;
 scalar_t__ VAR_56 ;
 scalar_t__ VAR_57 ;
 scalar_t__ VAR_58 ;
 scalar_t__ VAR_59 ;
 scalar_t__ VAR_60 ;
 scalar_t__ VAR_61 ;
 scalar_t__ VAR_62 ;
 scalar_t__ VAR_63 ;

__attribute__((used)) static int FUNC_1()
{
 int VAR_64 = 0;
 VAR_0 = (PFNGLAREPROGRAMSRESIDENTNVPROC)FUNC_0("glAreProgramsResidentNV");
 if(!VAR_0) ++VAR_64;
 VAR_1 = (PFNGLBINDPROGRAMNVPROC)FUNC_0("glBindProgramNV");
 if(!VAR_1) ++VAR_64;
 VAR_2 = (PFNGLDELETEPROGRAMSNVPROC)FUNC_0("glDeleteProgramsNV");
 if(!VAR_2) ++VAR_64;
 VAR_3 = (PFNGLEXECUTEPROGRAMNVPROC)FUNC_0("glExecuteProgramNV");
 if(!VAR_3) ++VAR_64;
 VAR_4 = (PFNGLGENPROGRAMSNVPROC)FUNC_0("glGenProgramsNV");
 if(!VAR_4) ++VAR_64;
 VAR_5 = (PFNGLGETPROGRAMPARAMETERDVNVPROC)FUNC_0("glGetProgramParameterdvNV");
 if(!VAR_5) ++VAR_64;
 VAR_6 = (PFNGLGETPROGRAMPARAMETERFVNVPROC)FUNC_0("glGetProgramParameterfvNV");
 if(!VAR_6) ++VAR_64;
 VAR_7 = (PFNGLGETPROGRAMSTRINGNVPROC)FUNC_0("glGetProgramStringNV");
 if(!VAR_7) ++VAR_64;
 VAR_8 = (PFNGLGETPROGRAMIVNVPROC)FUNC_0("glGetProgramivNV");
 if(!VAR_8) ++VAR_64;
 VAR_9 = (PFNGLGETTRACKMATRIXIVNVPROC)FUNC_0("glGetTrackMatrixivNV");
 if(!VAR_9) ++VAR_64;
 VAR_10 = (PFNGLGETVERTEXATTRIBPOINTERVNVPROC)FUNC_0("glGetVertexAttribPointervNV");
 if(!VAR_10) ++VAR_64;
 VAR_11 = (PFNGLGETVERTEXATTRIBDVNVPROC)FUNC_0("glGetVertexAttribdvNV");
 if(!VAR_11) ++VAR_64;
 VAR_12 = (PFNGLGETVERTEXATTRIBFVNVPROC)FUNC_0("glGetVertexAttribfvNV");
 if(!VAR_12) ++VAR_64;
 VAR_13 = (PFNGLGETVERTEXATTRIBIVNVPROC)FUNC_0("glGetVertexAttribivNV");
 if(!VAR_13) ++VAR_64;
 VAR_14 = (PFNGLISPROGRAMNVPROC)FUNC_0("glIsProgramNV");
 if(!VAR_14) ++VAR_64;
 VAR_15 = (PFNGLLOADPROGRAMNVPROC)FUNC_0("glLoadProgramNV");
 if(!VAR_15) ++VAR_64;
 VAR_16 = (PFNGLPROGRAMPARAMETER4DNVPROC)FUNC_0("glProgramParameter4dNV");
 if(!VAR_16) ++VAR_64;
 VAR_17 = (PFNGLPROGRAMPARAMETER4DVNVPROC)FUNC_0("glProgramParameter4dvNV");
 if(!VAR_17) ++VAR_64;
 VAR_18 = (PFNGLPROGRAMPARAMETER4FNVPROC)FUNC_0("glProgramParameter4fNV");
 if(!VAR_18) ++VAR_64;
 VAR_19 = (PFNGLPROGRAMPARAMETER4FVNVPROC)FUNC_0("glProgramParameter4fvNV");
 if(!VAR_19) ++VAR_64;
 VAR_20 = (PFNGLPROGRAMPARAMETERS4DVNVPROC)FUNC_0("glProgramParameters4dvNV");
 if(!VAR_20) ++VAR_64;
 VAR_21 = (PFNGLPROGRAMPARAMETERS4FVNVPROC)FUNC_0("glProgramParameters4fvNV");
 if(!VAR_21) ++VAR_64;
 VAR_22 = (PFNGLREQUESTRESIDENTPROGRAMSNVPROC)FUNC_0("glRequestResidentProgramsNV");
 if(!VAR_22) ++VAR_64;
 VAR_23 = (PFNGLTRACKMATRIXNVPROC)FUNC_0("glTrackMatrixNV");
 if(!VAR_23) ++VAR_64;
 VAR_24 = (PFNGLVERTEXATTRIB1DNVPROC)FUNC_0("glVertexAttrib1dNV");
 if(!VAR_24) ++VAR_64;
 VAR_25 = (PFNGLVERTEXATTRIB1DVNVPROC)FUNC_0("glVertexAttrib1dvNV");
 if(!VAR_25) ++VAR_64;
 VAR_26 = (PFNGLVERTEXATTRIB1FNVPROC)FUNC_0("glVertexAttrib1fNV");
 if(!VAR_26) ++VAR_64;
 VAR_27 = (PFNGLVERTEXATTRIB1FVNVPROC)FUNC_0("glVertexAttrib1fvNV");
 if(!VAR_27) ++VAR_64;
 VAR_28 = (PFNGLVERTEXATTRIB1SNVPROC)FUNC_0("glVertexAttrib1sNV");
 if(!VAR_28) ++VAR_64;
 VAR_29 = (PFNGLVERTEXATTRIB1SVNVPROC)FUNC_0("glVertexAttrib1svNV");
 if(!VAR_29) ++VAR_64;
 VAR_30 = (PFNGLVERTEXATTRIB2DNVPROC)FUNC_0("glVertexAttrib2dNV");
 if(!VAR_30) ++VAR_64;
 VAR_31 = (PFNGLVERTEXATTRIB2DVNVPROC)FUNC_0("glVertexAttrib2dvNV");
 if(!VAR_31) ++VAR_64;
 VAR_32 = (PFNGLVERTEXATTRIB2FNVPROC)FUNC_0("glVertexAttrib2fNV");
 if(!VAR_32) ++VAR_64;
 VAR_33 = (PFNGLVERTEXATTRIB2FVNVPROC)FUNC_0("glVertexAttrib2fvNV");
 if(!VAR_33) ++VAR_64;
 VAR_34 = (PFNGLVERTEXATTRIB2SNVPROC)FUNC_0("glVertexAttrib2sNV");
 if(!VAR_34) ++VAR_64;
 VAR_35 = (PFNGLVERTEXATTRIB2SVNVPROC)FUNC_0("glVertexAttrib2svNV");
 if(!VAR_35) ++VAR_64;
 VAR_36 = (PFNGLVERTEXATTRIB3DNVPROC)FUNC_0("glVertexAttrib3dNV");
 if(!VAR_36) ++VAR_64;
 VAR_37 = (PFNGLVERTEXATTRIB3DVNVPROC)FUNC_0("glVertexAttrib3dvNV");
 if(!VAR_37) ++VAR_64;
 VAR_38 = (PFNGLVERTEXATTRIB3FNVPROC)FUNC_0("glVertexAttrib3fNV");
 if(!VAR_38) ++VAR_64;
 VAR_39 = (PFNGLVERTEXATTRIB3FVNVPROC)FUNC_0("glVertexAttrib3fvNV");
 if(!VAR_39) ++VAR_64;
 VAR_40 = (PFNGLVERTEXATTRIB3SNVPROC)FUNC_0("glVertexAttrib3sNV");
 if(!VAR_40) ++VAR_64;
 VAR_41 = (PFNGLVERTEXATTRIB3SVNVPROC)FUNC_0("glVertexAttrib3svNV");
 if(!VAR_41) ++VAR_64;
 VAR_42 = (PFNGLVERTEXATTRIB4DNVPROC)FUNC_0("glVertexAttrib4dNV");
 if(!VAR_42) ++VAR_64;
 VAR_43 = (PFNGLVERTEXATTRIB4DVNVPROC)FUNC_0("glVertexAttrib4dvNV");
 if(!VAR_43) ++VAR_64;
 VAR_44 = (PFNGLVERTEXATTRIB4FNVPROC)FUNC_0("glVertexAttrib4fNV");
 if(!VAR_44) ++VAR_64;
 VAR_45 = (PFNGLVERTEXATTRIB4FVNVPROC)FUNC_0("glVertexAttrib4fvNV");
 if(!VAR_45) ++VAR_64;
 VAR_46 = (PFNGLVERTEXATTRIB4SNVPROC)FUNC_0("glVertexAttrib4sNV");
 if(!VAR_46) ++VAR_64;
 VAR_47 = (PFNGLVERTEXATTRIB4SVNVPROC)FUNC_0("glVertexAttrib4svNV");
 if(!VAR_47) ++VAR_64;
 VAR_48 = (PFNGLVERTEXATTRIB4UBNVPROC)FUNC_0("glVertexAttrib4ubNV");
 if(!VAR_48) ++VAR_64;
 VAR_49 = (PFNGLVERTEXATTRIB4UBVNVPROC)FUNC_0("glVertexAttrib4ubvNV");
 if(!VAR_49) ++VAR_64;
 VAR_50 = (PFNGLVERTEXATTRIBPOINTERNVPROC)FUNC_0("glVertexAttribPointerNV");
 if(!VAR_50) ++VAR_64;
 VAR_51 = (PFNGLVERTEXATTRIBS1DVNVPROC)FUNC_0("glVertexAttribs1dvNV");
 if(!VAR_51) ++VAR_64;
 VAR_52 = (PFNGLVERTEXATTRIBS1FVNVPROC)FUNC_0("glVertexAttribs1fvNV");
 if(!VAR_52) ++VAR_64;
 VAR_53 = (PFNGLVERTEXATTRIBS1SVNVPROC)FUNC_0("glVertexAttribs1svNV");
 if(!VAR_53) ++VAR_64;
 VAR_54 = (PFNGLVERTEXATTRIBS2DVNVPROC)FUNC_0("glVertexAttribs2dvNV");
 if(!VAR_54) ++VAR_64;
 VAR_55 = (PFNGLVERTEXATTRIBS2FVNVPROC)FUNC_0("glVertexAttribs2fvNV");
 if(!VAR_55) ++VAR_64;
 VAR_56 = (PFNGLVERTEXATTRIBS2SVNVPROC)FUNC_0("glVertexAttribs2svNV");
 if(!VAR_56) ++VAR_64;
 VAR_57 = (PFNGLVERTEXATTRIBS3DVNVPROC)FUNC_0("glVertexAttribs3dvNV");
 if(!VAR_57) ++VAR_64;
 VAR_58 = (PFNGLVERTEXATTRIBS3FVNVPROC)FUNC_0("glVertexAttribs3fvNV");
 if(!VAR_58) ++VAR_64;
 VAR_59 = (PFNGLVERTEXATTRIBS3SVNVPROC)FUNC_0("glVertexAttribs3svNV");
 if(!VAR_59) ++VAR_64;
 VAR_60 = (PFNGLVERTEXATTRIBS4DVNVPROC)FUNC_0("glVertexAttribs4dvNV");
 if(!VAR_60) ++VAR_64;
 VAR_61 = (PFNGLVERTEXATTRIBS4FVNVPROC)FUNC_0("glVertexAttribs4fvNV");
 if(!VAR_61) ++VAR_64;
 VAR_62 = (PFNGLVERTEXATTRIBS4SVNVPROC)FUNC_0("glVertexAttribs4svNV");
 if(!VAR_62) ++VAR_64;
 VAR_63 = (PFNGLVERTEXATTRIBS4UBVNVPROC)FUNC_0("glVertexAttribs4ubvNV");
 if(!VAR_63) ++VAR_64;
 return VAR_64;
}
