
typedef unsigned long size_t;
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;

typedef int bool;






typedef scalar_t__ PFNGLMULTTRANSPOSEMATRIXFPROC ;
typedef scalar_t__ PFNGLMULTTRANSPOSEMATRIXDPROC ;
typedef scalar_t__ PFNGLMULTITEXCOORD4SVPROC ;
typedef scalar_t__ PFNGLMULTITEXCOORD4SPROC ;
typedef scalar_t__ PFNGLMULTITEXCOORD4IVPROC ;
typedef scalar_t__ PFNGLMULTITEXCOORD4IPROC ;
typedef scalar_t__ PFNGLMULTITEXCOORD4FVPROC ;
typedef scalar_t__ PFNGLMULTITEXCOORD4FPROC ;
typedef scalar_t__ PFNGLMULTITEXCOORD4DVPROC ;
typedef scalar_t__ PFNGLMULTITEXCOORD4DPROC ;
typedef scalar_t__ PFNGLMULTITEXCOORD3SVPROC ;
typedef scalar_t__ PFNGLMULTITEXCOORD3SPROC ;
typedef scalar_t__ PFNGLMULTITEXCOORD3IVPROC ;
typedef scalar_t__ PFNGLMULTITEXCOORD3IPROC ;
typedef scalar_t__ PFNGLMULTITEXCOORD3FVPROC ;
typedef scalar_t__ PFNGLMULTITEXCOORD3FPROC ;
typedef scalar_t__ PFNGLMULTITEXCOORD3DVPROC ;
typedef scalar_t__ PFNGLMULTITEXCOORD3DPROC ;
typedef scalar_t__ PFNGLMULTITEXCOORD2SVPROC ;
typedef scalar_t__ PFNGLMULTITEXCOORD2SPROC ;
typedef scalar_t__ PFNGLMULTITEXCOORD2IVPROC ;
typedef scalar_t__ PFNGLMULTITEXCOORD2IPROC ;
typedef scalar_t__ PFNGLMULTITEXCOORD2FVPROC ;
typedef scalar_t__ PFNGLMULTITEXCOORD2FPROC ;
typedef scalar_t__ PFNGLMULTITEXCOORD2DVPROC ;
typedef scalar_t__ PFNGLMULTITEXCOORD2DPROC ;
typedef scalar_t__ PFNGLMULTITEXCOORD1SVPROC ;
typedef scalar_t__ PFNGLMULTITEXCOORD1SPROC ;
typedef scalar_t__ PFNGLMULTITEXCOORD1IVPROC ;
typedef scalar_t__ PFNGLMULTITEXCOORD1IPROC ;
typedef scalar_t__ PFNGLMULTITEXCOORD1FVPROC ;
typedef scalar_t__ PFNGLMULTITEXCOORD1FPROC ;
typedef scalar_t__ PFNGLMULTITEXCOORD1DVPROC ;
typedef scalar_t__ PFNGLMULTITEXCOORD1DPROC ;
typedef scalar_t__ PFNGLLOADTRANSPOSEMATRIXFPROC ;
typedef scalar_t__ PFNGLLOADTRANSPOSEMATRIXDPROC ;
typedef scalar_t__ PFNGLCLIENTACTIVETEXTUREPROC ;


 scalar_t__ FUNC_0 (char*) ;
 scalar_t__ VAR_0 ;
 scalar_t__ VAR_1 ;
 scalar_t__ VAR_2 ;
 scalar_t__ VAR_3 ;
 scalar_t__ VAR_4 ;
 scalar_t__ VAR_5 ;
 scalar_t__ VAR_6 ;
 scalar_t__ VAR_7 ;
 scalar_t__ VAR_8 ;
 scalar_t__ VAR_9 ;
 scalar_t__ VAR_10 ;
 scalar_t__ VAR_11 ;
 scalar_t__ VAR_12 ;
 scalar_t__ VAR_13 ;
 scalar_t__ VAR_14 ;
 scalar_t__ VAR_15 ;
 scalar_t__ VAR_16 ;
 scalar_t__ VAR_17 ;
 scalar_t__ VAR_18 ;
 scalar_t__ VAR_19 ;
 scalar_t__ VAR_20 ;
 scalar_t__ VAR_21 ;
 scalar_t__ VAR_22 ;
 scalar_t__ VAR_23 ;
 scalar_t__ VAR_24 ;
 scalar_t__ VAR_25 ;
 scalar_t__ VAR_26 ;
 scalar_t__ VAR_27 ;
 scalar_t__ VAR_28 ;
 scalar_t__ VAR_29 ;
 scalar_t__ VAR_30 ;
 scalar_t__ VAR_31 ;
 scalar_t__ VAR_32 ;
 scalar_t__ VAR_33 ;
 scalar_t__ VAR_34 ;
 scalar_t__ VAR_35 ;
 scalar_t__ VAR_36 ;

__attribute__((used)) static int FUNC_1()
{
 int VAR_37 = 0;
 VAR_0 = (PFNGLCLIENTACTIVETEXTUREPROC)FUNC_0("glClientActiveTexture");
 if(!VAR_0) ++VAR_37;
 VAR_1 = (PFNGLLOADTRANSPOSEMATRIXDPROC)FUNC_0("glLoadTransposeMatrixd");
 if(!VAR_1) ++VAR_37;
 VAR_2 = (PFNGLLOADTRANSPOSEMATRIXFPROC)FUNC_0("glLoadTransposeMatrixf");
 if(!VAR_2) ++VAR_37;
 VAR_3 = (PFNGLMULTTRANSPOSEMATRIXDPROC)FUNC_0("glMultTransposeMatrixd");
 if(!VAR_3) ++VAR_37;
 VAR_4 = (PFNGLMULTTRANSPOSEMATRIXFPROC)FUNC_0("glMultTransposeMatrixf");
 if(!VAR_4) ++VAR_37;
 VAR_5 = (PFNGLMULTITEXCOORD1DPROC)FUNC_0("glMultiTexCoord1d");
 if(!VAR_5) ++VAR_37;
 VAR_6 = (PFNGLMULTITEXCOORD1DVPROC)FUNC_0("glMultiTexCoord1dv");
 if(!VAR_6) ++VAR_37;
 VAR_7 = (PFNGLMULTITEXCOORD1FPROC)FUNC_0("glMultiTexCoord1f");
 if(!VAR_7) ++VAR_37;
 VAR_8 = (PFNGLMULTITEXCOORD1FVPROC)FUNC_0("glMultiTexCoord1fv");
 if(!VAR_8) ++VAR_37;
 VAR_9 = (PFNGLMULTITEXCOORD1IPROC)FUNC_0("glMultiTexCoord1i");
 if(!VAR_9) ++VAR_37;
 VAR_10 = (PFNGLMULTITEXCOORD1IVPROC)FUNC_0("glMultiTexCoord1iv");
 if(!VAR_10) ++VAR_37;
 VAR_11 = (PFNGLMULTITEXCOORD1SPROC)FUNC_0("glMultiTexCoord1s");
 if(!VAR_11) ++VAR_37;
 VAR_12 = (PFNGLMULTITEXCOORD1SVPROC)FUNC_0("glMultiTexCoord1sv");
 if(!VAR_12) ++VAR_37;
 VAR_13 = (PFNGLMULTITEXCOORD2DPROC)FUNC_0("glMultiTexCoord2d");
 if(!VAR_13) ++VAR_37;
 VAR_14 = (PFNGLMULTITEXCOORD2DVPROC)FUNC_0("glMultiTexCoord2dv");
 if(!VAR_14) ++VAR_37;
 VAR_15 = (PFNGLMULTITEXCOORD2FPROC)FUNC_0("glMultiTexCoord2f");
 if(!VAR_15) ++VAR_37;
 VAR_16 = (PFNGLMULTITEXCOORD2FVPROC)FUNC_0("glMultiTexCoord2fv");
 if(!VAR_16) ++VAR_37;
 VAR_17 = (PFNGLMULTITEXCOORD2IPROC)FUNC_0("glMultiTexCoord2i");
 if(!VAR_17) ++VAR_37;
 VAR_18 = (PFNGLMULTITEXCOORD2IVPROC)FUNC_0("glMultiTexCoord2iv");
 if(!VAR_18) ++VAR_37;
 VAR_19 = (PFNGLMULTITEXCOORD2SPROC)FUNC_0("glMultiTexCoord2s");
 if(!VAR_19) ++VAR_37;
 VAR_20 = (PFNGLMULTITEXCOORD2SVPROC)FUNC_0("glMultiTexCoord2sv");
 if(!VAR_20) ++VAR_37;
 VAR_21 = (PFNGLMULTITEXCOORD3DPROC)FUNC_0("glMultiTexCoord3d");
 if(!VAR_21) ++VAR_37;
 VAR_22 = (PFNGLMULTITEXCOORD3DVPROC)FUNC_0("glMultiTexCoord3dv");
 if(!VAR_22) ++VAR_37;
 VAR_23 = (PFNGLMULTITEXCOORD3FPROC)FUNC_0("glMultiTexCoord3f");
 if(!VAR_23) ++VAR_37;
 VAR_24 = (PFNGLMULTITEXCOORD3FVPROC)FUNC_0("glMultiTexCoord3fv");
 if(!VAR_24) ++VAR_37;
 VAR_25 = (PFNGLMULTITEXCOORD3IPROC)FUNC_0("glMultiTexCoord3i");
 if(!VAR_25) ++VAR_37;
 VAR_26 = (PFNGLMULTITEXCOORD3IVPROC)FUNC_0("glMultiTexCoord3iv");
 if(!VAR_26) ++VAR_37;
 VAR_27 = (PFNGLMULTITEXCOORD3SPROC)FUNC_0("glMultiTexCoord3s");
 if(!VAR_27) ++VAR_37;
 VAR_28 = (PFNGLMULTITEXCOORD3SVPROC)FUNC_0("glMultiTexCoord3sv");
 if(!VAR_28) ++VAR_37;
 VAR_29 = (PFNGLMULTITEXCOORD4DPROC)FUNC_0("glMultiTexCoord4d");
 if(!VAR_29) ++VAR_37;
 VAR_30 = (PFNGLMULTITEXCOORD4DVPROC)FUNC_0("glMultiTexCoord4dv");
 if(!VAR_30) ++VAR_37;
 VAR_31 = (PFNGLMULTITEXCOORD4FPROC)FUNC_0("glMultiTexCoord4f");
 if(!VAR_31) ++VAR_37;
 VAR_32 = (PFNGLMULTITEXCOORD4FVPROC)FUNC_0("glMultiTexCoord4fv");
 if(!VAR_32) ++VAR_37;
 VAR_33 = (PFNGLMULTITEXCOORD4IPROC)FUNC_0("glMultiTexCoord4i");
 if(!VAR_33) ++VAR_37;
 VAR_34 = (PFNGLMULTITEXCOORD4IVPROC)FUNC_0("glMultiTexCoord4iv");
 if(!VAR_34) ++VAR_37;
 VAR_35 = (PFNGLMULTITEXCOORD4SPROC)FUNC_0("glMultiTexCoord4s");
 if(!VAR_35) ++VAR_37;
 VAR_36 = (PFNGLMULTITEXCOORD4SVPROC)FUNC_0("glMultiTexCoord4sv");
 if(!VAR_36) ++VAR_37;
 return VAR_37;
}
