
typedef unsigned long size_t;
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;

typedef int bool;






typedef scalar_t__ PFNGLVERTEXATTRIBPOINTERPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIB4USVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIB4UIVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIB4UBVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIB4SVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIB4SPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIB4NUSVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIB4NUIVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIB4NUBVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIB4NUBPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIB4NSVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIB4NIVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIB4NBVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIB4IVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIB4FVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIB4FPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIB4DVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIB4DPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIB4BVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIB3SVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIB3SPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIB3FVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIB3FPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIB3DVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIB3DPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIB2SVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIB2SPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIB2FVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIB2FPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIB2DVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIB2DPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIB1SVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIB1SPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIB1FVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIB1FPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIB1DVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIB1DPROC ;
typedef scalar_t__ PFNGLVALIDATEPROGRAMPROC ;
typedef scalar_t__ PFNGLUSEPROGRAMPROC ;
typedef scalar_t__ PFNGLUNIFORMMATRIX4FVPROC ;
typedef scalar_t__ PFNGLUNIFORMMATRIX3FVPROC ;
typedef scalar_t__ PFNGLUNIFORMMATRIX2FVPROC ;
typedef scalar_t__ PFNGLUNIFORM4IVPROC ;
typedef scalar_t__ PFNGLUNIFORM4IPROC ;
typedef scalar_t__ PFNGLUNIFORM4FVPROC ;
typedef scalar_t__ PFNGLUNIFORM4FPROC ;
typedef scalar_t__ PFNGLUNIFORM3IVPROC ;
typedef scalar_t__ PFNGLUNIFORM3IPROC ;
typedef scalar_t__ PFNGLUNIFORM3FVPROC ;
typedef scalar_t__ PFNGLUNIFORM3FPROC ;
typedef scalar_t__ PFNGLUNIFORM2IVPROC ;
typedef scalar_t__ PFNGLUNIFORM2IPROC ;
typedef scalar_t__ PFNGLUNIFORM2FVPROC ;
typedef scalar_t__ PFNGLUNIFORM2FPROC ;
typedef scalar_t__ PFNGLUNIFORM1IVPROC ;
typedef scalar_t__ PFNGLUNIFORM1IPROC ;
typedef scalar_t__ PFNGLUNIFORM1FVPROC ;
typedef scalar_t__ PFNGLUNIFORM1FPROC ;
typedef scalar_t__ PFNGLSTENCILOPSEPARATEPROC ;
typedef scalar_t__ PFNGLSTENCILMASKSEPARATEPROC ;
typedef scalar_t__ PFNGLSTENCILFUNCSEPARATEPROC ;
typedef scalar_t__ PFNGLSHADERSOURCEPROC ;
typedef scalar_t__ PFNGLLINKPROGRAMPROC ;
typedef scalar_t__ PFNGLISSHADERPROC ;
typedef scalar_t__ PFNGLISPROGRAMPROC ;
typedef scalar_t__ PFNGLGETVERTEXATTRIBPOINTERVPROC ;
typedef scalar_t__ PFNGLGETVERTEXATTRIBIVPROC ;
typedef scalar_t__ PFNGLGETVERTEXATTRIBFVPROC ;
typedef scalar_t__ PFNGLGETVERTEXATTRIBDVPROC ;
typedef scalar_t__ PFNGLGETUNIFORMLOCATIONPROC ;
typedef scalar_t__ PFNGLGETUNIFORMIVPROC ;
typedef scalar_t__ PFNGLGETUNIFORMFVPROC ;
typedef scalar_t__ PFNGLGETSHADERSOURCEPROC ;
typedef scalar_t__ PFNGLGETSHADERIVPROC ;
typedef scalar_t__ PFNGLGETSHADERINFOLOGPROC ;
typedef scalar_t__ PFNGLGETPROGRAMIVPROC ;
typedef scalar_t__ PFNGLGETPROGRAMINFOLOGPROC ;
typedef scalar_t__ PFNGLGETATTRIBLOCATIONPROC ;
typedef scalar_t__ PFNGLGETATTACHEDSHADERSPROC ;
typedef scalar_t__ PFNGLGETACTIVEUNIFORMPROC ;
typedef scalar_t__ PFNGLGETACTIVEATTRIBPROC ;
typedef scalar_t__ PFNGLENABLEVERTEXATTRIBARRAYPROC ;
typedef scalar_t__ PFNGLDRAWBUFFERSPROC ;
typedef scalar_t__ PFNGLDISABLEVERTEXATTRIBARRAYPROC ;
typedef scalar_t__ PFNGLDETACHSHADERPROC ;
typedef scalar_t__ PFNGLDELETESHADERPROC ;
typedef scalar_t__ PFNGLDELETEPROGRAMPROC ;
typedef scalar_t__ PFNGLCREATESHADERPROC ;
typedef scalar_t__ PFNGLCREATEPROGRAMPROC ;
typedef scalar_t__ PFNGLCOMPILESHADERPROC ;
typedef scalar_t__ PFNGLBLENDEQUATIONSEPARATEPROC ;
typedef scalar_t__ PFNGLBINDATTRIBLOCATIONPROC ;
typedef scalar_t__ PFNGLATTACHSHADERPROC ;


 scalar_t__ FUNC_0 (char*) ;
 scalar_t__ VAR_0 ;
 scalar_t__ VAR_1 ;
 scalar_t__ VAR_2 ;
 scalar_t__ VAR_3 ;
 scalar_t__ VAR_4 ;
 scalar_t__ VAR_5 ;
 scalar_t__ VAR_6 ;
 scalar_t__ VAR_7 ;
 scalar_t__ VAR_8 ;
 scalar_t__ VAR_9 ;
 scalar_t__ VAR_10 ;
 scalar_t__ VAR_11 ;
 scalar_t__ VAR_12 ;
 scalar_t__ VAR_13 ;
 scalar_t__ VAR_14 ;
 scalar_t__ VAR_15 ;
 scalar_t__ VAR_16 ;
 scalar_t__ VAR_17 ;
 scalar_t__ VAR_18 ;
 scalar_t__ VAR_19 ;
 scalar_t__ VAR_20 ;
 scalar_t__ VAR_21 ;
 scalar_t__ VAR_22 ;
 scalar_t__ VAR_23 ;
 scalar_t__ VAR_24 ;
 scalar_t__ VAR_25 ;
 scalar_t__ VAR_26 ;
 scalar_t__ VAR_27 ;
 scalar_t__ VAR_28 ;
 scalar_t__ VAR_29 ;
 scalar_t__ VAR_30 ;
 scalar_t__ VAR_31 ;
 scalar_t__ VAR_32 ;
 scalar_t__ VAR_33 ;
 scalar_t__ VAR_34 ;
 scalar_t__ VAR_35 ;
 scalar_t__ VAR_36 ;
 scalar_t__ VAR_37 ;
 scalar_t__ VAR_38 ;
 scalar_t__ VAR_39 ;
 scalar_t__ VAR_40 ;
 scalar_t__ VAR_41 ;
 scalar_t__ VAR_42 ;
 scalar_t__ VAR_43 ;
 scalar_t__ VAR_44 ;
 scalar_t__ VAR_45 ;
 scalar_t__ VAR_46 ;
 scalar_t__ VAR_47 ;
 scalar_t__ VAR_48 ;
 scalar_t__ VAR_49 ;
 scalar_t__ VAR_50 ;
 scalar_t__ VAR_51 ;
 scalar_t__ VAR_52 ;
 scalar_t__ VAR_53 ;
 scalar_t__ VAR_54 ;
 scalar_t__ VAR_55 ;
 scalar_t__ VAR_56 ;
 scalar_t__ VAR_57 ;
 scalar_t__ VAR_58 ;
 scalar_t__ VAR_59 ;
 scalar_t__ VAR_60 ;
 scalar_t__ VAR_61 ;
 scalar_t__ VAR_62 ;
 scalar_t__ VAR_63 ;
 scalar_t__ VAR_64 ;
 scalar_t__ VAR_65 ;
 scalar_t__ VAR_66 ;
 scalar_t__ VAR_67 ;
 scalar_t__ VAR_68 ;
 scalar_t__ VAR_69 ;
 scalar_t__ VAR_70 ;
 scalar_t__ VAR_71 ;
 scalar_t__ VAR_72 ;
 scalar_t__ VAR_73 ;
 scalar_t__ VAR_74 ;
 scalar_t__ VAR_75 ;
 scalar_t__ VAR_76 ;
 scalar_t__ VAR_77 ;
 scalar_t__ VAR_78 ;
 scalar_t__ VAR_79 ;
 scalar_t__ VAR_80 ;
 scalar_t__ VAR_81 ;
 scalar_t__ VAR_82 ;
 scalar_t__ VAR_83 ;
 scalar_t__ VAR_84 ;
 scalar_t__ VAR_85 ;
 scalar_t__ VAR_86 ;
 scalar_t__ VAR_87 ;
 scalar_t__ VAR_88 ;
 scalar_t__ VAR_89 ;
 scalar_t__ VAR_90 ;
 scalar_t__ VAR_91 ;
 scalar_t__ VAR_92 ;

__attribute__((used)) static int FUNC_1()
{
 int VAR_93 = 0;
 VAR_0 = (PFNGLATTACHSHADERPROC)FUNC_0("glAttachShader");
 if(!VAR_0) ++VAR_93;
 VAR_1 = (PFNGLBINDATTRIBLOCATIONPROC)FUNC_0("glBindAttribLocation");
 if(!VAR_1) ++VAR_93;
 VAR_2 = (PFNGLBLENDEQUATIONSEPARATEPROC)FUNC_0("glBlendEquationSeparate");
 if(!VAR_2) ++VAR_93;
 VAR_3 = (PFNGLCOMPILESHADERPROC)FUNC_0("glCompileShader");
 if(!VAR_3) ++VAR_93;
 VAR_4 = (PFNGLCREATEPROGRAMPROC)FUNC_0("glCreateProgram");
 if(!VAR_4) ++VAR_93;
 VAR_5 = (PFNGLCREATESHADERPROC)FUNC_0("glCreateShader");
 if(!VAR_5) ++VAR_93;
 VAR_6 = (PFNGLDELETEPROGRAMPROC)FUNC_0("glDeleteProgram");
 if(!VAR_6) ++VAR_93;
 VAR_7 = (PFNGLDELETESHADERPROC)FUNC_0("glDeleteShader");
 if(!VAR_7) ++VAR_93;
 VAR_8 = (PFNGLDETACHSHADERPROC)FUNC_0("glDetachShader");
 if(!VAR_8) ++VAR_93;
 VAR_9 = (PFNGLDISABLEVERTEXATTRIBARRAYPROC)FUNC_0("glDisableVertexAttribArray");
 if(!VAR_9) ++VAR_93;
 VAR_10 = (PFNGLDRAWBUFFERSPROC)FUNC_0("glDrawBuffers");
 if(!VAR_10) ++VAR_93;
 VAR_11 = (PFNGLENABLEVERTEXATTRIBARRAYPROC)FUNC_0("glEnableVertexAttribArray");
 if(!VAR_11) ++VAR_93;
 VAR_12 = (PFNGLGETACTIVEATTRIBPROC)FUNC_0("glGetActiveAttrib");
 if(!VAR_12) ++VAR_93;
 VAR_13 = (PFNGLGETACTIVEUNIFORMPROC)FUNC_0("glGetActiveUniform");
 if(!VAR_13) ++VAR_93;
 VAR_14 = (PFNGLGETATTACHEDSHADERSPROC)FUNC_0("glGetAttachedShaders");
 if(!VAR_14) ++VAR_93;
 VAR_15 = (PFNGLGETATTRIBLOCATIONPROC)FUNC_0("glGetAttribLocation");
 if(!VAR_15) ++VAR_93;
 VAR_16 = (PFNGLGETPROGRAMINFOLOGPROC)FUNC_0("glGetProgramInfoLog");
 if(!VAR_16) ++VAR_93;
 VAR_17 = (PFNGLGETPROGRAMIVPROC)FUNC_0("glGetProgramiv");
 if(!VAR_17) ++VAR_93;
 VAR_18 = (PFNGLGETSHADERINFOLOGPROC)FUNC_0("glGetShaderInfoLog");
 if(!VAR_18) ++VAR_93;
 VAR_19 = (PFNGLGETSHADERSOURCEPROC)FUNC_0("glGetShaderSource");
 if(!VAR_19) ++VAR_93;
 VAR_20 = (PFNGLGETSHADERIVPROC)FUNC_0("glGetShaderiv");
 if(!VAR_20) ++VAR_93;
 VAR_21 = (PFNGLGETUNIFORMLOCATIONPROC)FUNC_0("glGetUniformLocation");
 if(!VAR_21) ++VAR_93;
 VAR_22 = (PFNGLGETUNIFORMFVPROC)FUNC_0("glGetUniformfv");
 if(!VAR_22) ++VAR_93;
 VAR_23 = (PFNGLGETUNIFORMIVPROC)FUNC_0("glGetUniformiv");
 if(!VAR_23) ++VAR_93;
 VAR_24 = (PFNGLGETVERTEXATTRIBPOINTERVPROC)FUNC_0("glGetVertexAttribPointerv");
 if(!VAR_24) ++VAR_93;
 VAR_25 = (PFNGLGETVERTEXATTRIBDVPROC)FUNC_0("glGetVertexAttribdv");
 if(!VAR_25) ++VAR_93;
 VAR_26 = (PFNGLGETVERTEXATTRIBFVPROC)FUNC_0("glGetVertexAttribfv");
 if(!VAR_26) ++VAR_93;
 VAR_27 = (PFNGLGETVERTEXATTRIBIVPROC)FUNC_0("glGetVertexAttribiv");
 if(!VAR_27) ++VAR_93;
 VAR_28 = (PFNGLISPROGRAMPROC)FUNC_0("glIsProgram");
 if(!VAR_28) ++VAR_93;
 VAR_29 = (PFNGLISSHADERPROC)FUNC_0("glIsShader");
 if(!VAR_29) ++VAR_93;
 VAR_30 = (PFNGLLINKPROGRAMPROC)FUNC_0("glLinkProgram");
 if(!VAR_30) ++VAR_93;
 VAR_31 = (PFNGLSHADERSOURCEPROC)FUNC_0("glShaderSource");
 if(!VAR_31) ++VAR_93;
 VAR_32 = (PFNGLSTENCILFUNCSEPARATEPROC)FUNC_0("glStencilFuncSeparate");
 if(!VAR_32) ++VAR_93;
 VAR_33 = (PFNGLSTENCILMASKSEPARATEPROC)FUNC_0("glStencilMaskSeparate");
 if(!VAR_33) ++VAR_93;
 VAR_34 = (PFNGLSTENCILOPSEPARATEPROC)FUNC_0("glStencilOpSeparate");
 if(!VAR_34) ++VAR_93;
 VAR_35 = (PFNGLUNIFORM1FPROC)FUNC_0("glUniform1f");
 if(!VAR_35) ++VAR_93;
 VAR_36 = (PFNGLUNIFORM1FVPROC)FUNC_0("glUniform1fv");
 if(!VAR_36) ++VAR_93;
 VAR_37 = (PFNGLUNIFORM1IPROC)FUNC_0("glUniform1i");
 if(!VAR_37) ++VAR_93;
 VAR_38 = (PFNGLUNIFORM1IVPROC)FUNC_0("glUniform1iv");
 if(!VAR_38) ++VAR_93;
 VAR_39 = (PFNGLUNIFORM2FPROC)FUNC_0("glUniform2f");
 if(!VAR_39) ++VAR_93;
 VAR_40 = (PFNGLUNIFORM2FVPROC)FUNC_0("glUniform2fv");
 if(!VAR_40) ++VAR_93;
 VAR_41 = (PFNGLUNIFORM2IPROC)FUNC_0("glUniform2i");
 if(!VAR_41) ++VAR_93;
 VAR_42 = (PFNGLUNIFORM2IVPROC)FUNC_0("glUniform2iv");
 if(!VAR_42) ++VAR_93;
 VAR_43 = (PFNGLUNIFORM3FPROC)FUNC_0("glUniform3f");
 if(!VAR_43) ++VAR_93;
 VAR_44 = (PFNGLUNIFORM3FVPROC)FUNC_0("glUniform3fv");
 if(!VAR_44) ++VAR_93;
 VAR_45 = (PFNGLUNIFORM3IPROC)FUNC_0("glUniform3i");
 if(!VAR_45) ++VAR_93;
 VAR_46 = (PFNGLUNIFORM3IVPROC)FUNC_0("glUniform3iv");
 if(!VAR_46) ++VAR_93;
 VAR_47 = (PFNGLUNIFORM4FPROC)FUNC_0("glUniform4f");
 if(!VAR_47) ++VAR_93;
 VAR_48 = (PFNGLUNIFORM4FVPROC)FUNC_0("glUniform4fv");
 if(!VAR_48) ++VAR_93;
 VAR_49 = (PFNGLUNIFORM4IPROC)FUNC_0("glUniform4i");
 if(!VAR_49) ++VAR_93;
 VAR_50 = (PFNGLUNIFORM4IVPROC)FUNC_0("glUniform4iv");
 if(!VAR_50) ++VAR_93;
 VAR_51 = (PFNGLUNIFORMMATRIX2FVPROC)FUNC_0("glUniformMatrix2fv");
 if(!VAR_51) ++VAR_93;
 VAR_52 = (PFNGLUNIFORMMATRIX3FVPROC)FUNC_0("glUniformMatrix3fv");
 if(!VAR_52) ++VAR_93;
 VAR_53 = (PFNGLUNIFORMMATRIX4FVPROC)FUNC_0("glUniformMatrix4fv");
 if(!VAR_53) ++VAR_93;
 VAR_54 = (PFNGLUSEPROGRAMPROC)FUNC_0("glUseProgram");
 if(!VAR_54) ++VAR_93;
 VAR_55 = (PFNGLVALIDATEPROGRAMPROC)FUNC_0("glValidateProgram");
 if(!VAR_55) ++VAR_93;
 VAR_56 = (PFNGLVERTEXATTRIB1DPROC)FUNC_0("glVertexAttrib1d");
 if(!VAR_56) ++VAR_93;
 VAR_57 = (PFNGLVERTEXATTRIB1DVPROC)FUNC_0("glVertexAttrib1dv");
 if(!VAR_57) ++VAR_93;
 VAR_58 = (PFNGLVERTEXATTRIB1FPROC)FUNC_0("glVertexAttrib1f");
 if(!VAR_58) ++VAR_93;
 VAR_59 = (PFNGLVERTEXATTRIB1FVPROC)FUNC_0("glVertexAttrib1fv");
 if(!VAR_59) ++VAR_93;
 VAR_60 = (PFNGLVERTEXATTRIB1SPROC)FUNC_0("glVertexAttrib1s");
 if(!VAR_60) ++VAR_93;
 VAR_61 = (PFNGLVERTEXATTRIB1SVPROC)FUNC_0("glVertexAttrib1sv");
 if(!VAR_61) ++VAR_93;
 VAR_62 = (PFNGLVERTEXATTRIB2DPROC)FUNC_0("glVertexAttrib2d");
 if(!VAR_62) ++VAR_93;
 VAR_63 = (PFNGLVERTEXATTRIB2DVPROC)FUNC_0("glVertexAttrib2dv");
 if(!VAR_63) ++VAR_93;
 VAR_64 = (PFNGLVERTEXATTRIB2FPROC)FUNC_0("glVertexAttrib2f");
 if(!VAR_64) ++VAR_93;
 VAR_65 = (PFNGLVERTEXATTRIB2FVPROC)FUNC_0("glVertexAttrib2fv");
 if(!VAR_65) ++VAR_93;
 VAR_66 = (PFNGLVERTEXATTRIB2SPROC)FUNC_0("glVertexAttrib2s");
 if(!VAR_66) ++VAR_93;
 VAR_67 = (PFNGLVERTEXATTRIB2SVPROC)FUNC_0("glVertexAttrib2sv");
 if(!VAR_67) ++VAR_93;
 VAR_68 = (PFNGLVERTEXATTRIB3DPROC)FUNC_0("glVertexAttrib3d");
 if(!VAR_68) ++VAR_93;
 VAR_69 = (PFNGLVERTEXATTRIB3DVPROC)FUNC_0("glVertexAttrib3dv");
 if(!VAR_69) ++VAR_93;
 VAR_70 = (PFNGLVERTEXATTRIB3FPROC)FUNC_0("glVertexAttrib3f");
 if(!VAR_70) ++VAR_93;
 VAR_71 = (PFNGLVERTEXATTRIB3FVPROC)FUNC_0("glVertexAttrib3fv");
 if(!VAR_71) ++VAR_93;
 VAR_72 = (PFNGLVERTEXATTRIB3SPROC)FUNC_0("glVertexAttrib3s");
 if(!VAR_72) ++VAR_93;
 VAR_73 = (PFNGLVERTEXATTRIB3SVPROC)FUNC_0("glVertexAttrib3sv");
 if(!VAR_73) ++VAR_93;
 VAR_74 = (PFNGLVERTEXATTRIB4NBVPROC)FUNC_0("glVertexAttrib4Nbv");
 if(!VAR_74) ++VAR_93;
 VAR_75 = (PFNGLVERTEXATTRIB4NIVPROC)FUNC_0("glVertexAttrib4Niv");
 if(!VAR_75) ++VAR_93;
 VAR_76 = (PFNGLVERTEXATTRIB4NSVPROC)FUNC_0("glVertexAttrib4Nsv");
 if(!VAR_76) ++VAR_93;
 VAR_77 = (PFNGLVERTEXATTRIB4NUBPROC)FUNC_0("glVertexAttrib4Nub");
 if(!VAR_77) ++VAR_93;
 VAR_78 = (PFNGLVERTEXATTRIB4NUBVPROC)FUNC_0("glVertexAttrib4Nubv");
 if(!VAR_78) ++VAR_93;
 VAR_79 = (PFNGLVERTEXATTRIB4NUIVPROC)FUNC_0("glVertexAttrib4Nuiv");
 if(!VAR_79) ++VAR_93;
 VAR_80 = (PFNGLVERTEXATTRIB4NUSVPROC)FUNC_0("glVertexAttrib4Nusv");
 if(!VAR_80) ++VAR_93;
 VAR_81 = (PFNGLVERTEXATTRIB4BVPROC)FUNC_0("glVertexAttrib4bv");
 if(!VAR_81) ++VAR_93;
 VAR_82 = (PFNGLVERTEXATTRIB4DPROC)FUNC_0("glVertexAttrib4d");
 if(!VAR_82) ++VAR_93;
 VAR_83 = (PFNGLVERTEXATTRIB4DVPROC)FUNC_0("glVertexAttrib4dv");
 if(!VAR_83) ++VAR_93;
 VAR_84 = (PFNGLVERTEXATTRIB4FPROC)FUNC_0("glVertexAttrib4f");
 if(!VAR_84) ++VAR_93;
 VAR_85 = (PFNGLVERTEXATTRIB4FVPROC)FUNC_0("glVertexAttrib4fv");
 if(!VAR_85) ++VAR_93;
 VAR_86 = (PFNGLVERTEXATTRIB4IVPROC)FUNC_0("glVertexAttrib4iv");
 if(!VAR_86) ++VAR_93;
 VAR_87 = (PFNGLVERTEXATTRIB4SPROC)FUNC_0("glVertexAttrib4s");
 if(!VAR_87) ++VAR_93;
 VAR_88 = (PFNGLVERTEXATTRIB4SVPROC)FUNC_0("glVertexAttrib4sv");
 if(!VAR_88) ++VAR_93;
 VAR_89 = (PFNGLVERTEXATTRIB4UBVPROC)FUNC_0("glVertexAttrib4ubv");
 if(!VAR_89) ++VAR_93;
 VAR_90 = (PFNGLVERTEXATTRIB4UIVPROC)FUNC_0("glVertexAttrib4uiv");
 if(!VAR_90) ++VAR_93;
 VAR_91 = (PFNGLVERTEXATTRIB4USVPROC)FUNC_0("glVertexAttrib4usv");
 if(!VAR_91) ++VAR_93;
 VAR_92 = (PFNGLVERTEXATTRIBPOINTERPROC)FUNC_0("glVertexAttribPointer");
 if(!VAR_92) ++VAR_93;
 return VAR_93;
}
