
typedef unsigned long size_t;
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;

typedef int bool;






typedef scalar_t__ PFNGLVERTEXATTRIBL1UI64VARBPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIBL1UI64ARBPROC ;
typedef scalar_t__ PFNGLUNIFORMHANDLEUI64VARBPROC ;
typedef scalar_t__ PFNGLUNIFORMHANDLEUI64ARBPROC ;
typedef scalar_t__ PFNGLPROGRAMUNIFORMHANDLEUI64VARBPROC ;
typedef scalar_t__ PFNGLPROGRAMUNIFORMHANDLEUI64ARBPROC ;
typedef scalar_t__ PFNGLMAKETEXTUREHANDLERESIDENTARBPROC ;
typedef scalar_t__ PFNGLMAKETEXTUREHANDLENONRESIDENTARBPROC ;
typedef scalar_t__ PFNGLMAKEIMAGEHANDLERESIDENTARBPROC ;
typedef scalar_t__ PFNGLMAKEIMAGEHANDLENONRESIDENTARBPROC ;
typedef scalar_t__ PFNGLISTEXTUREHANDLERESIDENTARBPROC ;
typedef scalar_t__ PFNGLISIMAGEHANDLERESIDENTARBPROC ;
typedef scalar_t__ PFNGLGETVERTEXATTRIBLUI64VARBPROC ;
typedef scalar_t__ PFNGLGETTEXTURESAMPLERHANDLEARBPROC ;
typedef scalar_t__ PFNGLGETTEXTUREHANDLEARBPROC ;
typedef scalar_t__ PFNGLGETIMAGEHANDLEARBPROC ;


 scalar_t__ FUNC_0 (char*) ;
 scalar_t__ VAR_0 ;
 scalar_t__ VAR_1 ;
 scalar_t__ VAR_2 ;
 scalar_t__ VAR_3 ;
 scalar_t__ VAR_4 ;
 scalar_t__ VAR_5 ;
 scalar_t__ VAR_6 ;
 scalar_t__ VAR_7 ;
 scalar_t__ VAR_8 ;
 scalar_t__ VAR_9 ;
 scalar_t__ VAR_10 ;
 scalar_t__ VAR_11 ;
 scalar_t__ VAR_12 ;
 scalar_t__ VAR_13 ;
 scalar_t__ VAR_14 ;
 scalar_t__ VAR_15 ;

__attribute__((used)) static int FUNC_1()
{
 int VAR_16 = 0;
 VAR_0 = (PFNGLGETIMAGEHANDLEARBPROC)FUNC_0("glGetImageHandleARB");
 if(!VAR_0) ++VAR_16;
 VAR_1 = (PFNGLGETTEXTUREHANDLEARBPROC)FUNC_0("glGetTextureHandleARB");
 if(!VAR_1) ++VAR_16;
 VAR_2 = (PFNGLGETTEXTURESAMPLERHANDLEARBPROC)FUNC_0("glGetTextureSamplerHandleARB");
 if(!VAR_2) ++VAR_16;
 VAR_3 = (PFNGLGETVERTEXATTRIBLUI64VARBPROC)FUNC_0("glGetVertexAttribLui64vARB");
 if(!VAR_3) ++VAR_16;
 VAR_4 = (PFNGLISIMAGEHANDLERESIDENTARBPROC)FUNC_0("glIsImageHandleResidentARB");
 if(!VAR_4) ++VAR_16;
 VAR_5 = (PFNGLISTEXTUREHANDLERESIDENTARBPROC)FUNC_0("glIsTextureHandleResidentARB");
 if(!VAR_5) ++VAR_16;
 VAR_6 = (PFNGLMAKEIMAGEHANDLENONRESIDENTARBPROC)FUNC_0("glMakeImageHandleNonResidentARB");
 if(!VAR_6) ++VAR_16;
 VAR_7 = (PFNGLMAKEIMAGEHANDLERESIDENTARBPROC)FUNC_0("glMakeImageHandleResidentARB");
 if(!VAR_7) ++VAR_16;
 VAR_8 = (PFNGLMAKETEXTUREHANDLENONRESIDENTARBPROC)FUNC_0("glMakeTextureHandleNonResidentARB");
 if(!VAR_8) ++VAR_16;
 VAR_9 = (PFNGLMAKETEXTUREHANDLERESIDENTARBPROC)FUNC_0("glMakeTextureHandleResidentARB");
 if(!VAR_9) ++VAR_16;
 VAR_10 = (PFNGLPROGRAMUNIFORMHANDLEUI64ARBPROC)FUNC_0("glProgramUniformHandleui64ARB");
 if(!VAR_10) ++VAR_16;
 VAR_11 = (PFNGLPROGRAMUNIFORMHANDLEUI64VARBPROC)FUNC_0("glProgramUniformHandleui64vARB");
 if(!VAR_11) ++VAR_16;
 VAR_12 = (PFNGLUNIFORMHANDLEUI64ARBPROC)FUNC_0("glUniformHandleui64ARB");
 if(!VAR_12) ++VAR_16;
 VAR_13 = (PFNGLUNIFORMHANDLEUI64VARBPROC)FUNC_0("glUniformHandleui64vARB");
 if(!VAR_13) ++VAR_16;
 VAR_14 = (PFNGLVERTEXATTRIBL1UI64ARBPROC)FUNC_0("glVertexAttribL1ui64ARB");
 if(!VAR_14) ++VAR_16;
 VAR_15 = (PFNGLVERTEXATTRIBL1UI64VARBPROC)FUNC_0("glVertexAttribL1ui64vARB");
 if(!VAR_15) ++VAR_16;
 return VAR_16;
}
