
typedef unsigned long size_t;
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;

typedef int bool;






typedef scalar_t__ PFNGLWEIGHTPATHSNVPROC ;
typedef scalar_t__ PFNGLTRANSFORMPATHNVPROC ;
typedef scalar_t__ PFNGLSTENCILSTROKEPATHNVPROC ;
typedef scalar_t__ PFNGLSTENCILSTROKEPATHINSTANCEDNVPROC ;
typedef scalar_t__ PFNGLSTENCILFILLPATHNVPROC ;
typedef scalar_t__ PFNGLSTENCILFILLPATHINSTANCEDNVPROC ;
typedef scalar_t__ PFNGLPOINTALONGPATHNVPROC ;
typedef scalar_t__ PFNGLPATHTEXGENNVPROC ;
typedef scalar_t__ PFNGLPATHSUBCOORDSNVPROC ;
typedef scalar_t__ PFNGLPATHSUBCOMMANDSNVPROC ;
typedef scalar_t__ PFNGLPATHSTRINGNVPROC ;
typedef scalar_t__ PFNGLPATHSTENCILFUNCNVPROC ;
typedef scalar_t__ PFNGLPATHSTENCILDEPTHOFFSETNVPROC ;
typedef scalar_t__ PFNGLPATHPARAMETERIVNVPROC ;
typedef scalar_t__ PFNGLPATHPARAMETERINVPROC ;
typedef scalar_t__ PFNGLPATHPARAMETERFVNVPROC ;
typedef scalar_t__ PFNGLPATHPARAMETERFNVPROC ;
typedef scalar_t__ PFNGLPATHGLYPHSNVPROC ;
typedef scalar_t__ PFNGLPATHGLYPHRANGENVPROC ;
typedef scalar_t__ PFNGLPATHFOGGENNVPROC ;
typedef scalar_t__ PFNGLPATHDASHARRAYNVPROC ;
typedef scalar_t__ PFNGLPATHCOVERDEPTHFUNCNVPROC ;
typedef scalar_t__ PFNGLPATHCOORDSNVPROC ;
typedef scalar_t__ PFNGLPATHCOMMANDSNVPROC ;
typedef scalar_t__ PFNGLPATHCOLORGENNVPROC ;
typedef scalar_t__ PFNGLISPOINTINSTROKEPATHNVPROC ;
typedef scalar_t__ PFNGLISPOINTINFILLPATHNVPROC ;
typedef scalar_t__ PFNGLISPATHNVPROC ;
typedef scalar_t__ PFNGLINTERPOLATEPATHSNVPROC ;
typedef scalar_t__ PFNGLGETPATHTEXGENIVNVPROC ;
typedef scalar_t__ PFNGLGETPATHTEXGENFVNVPROC ;
typedef scalar_t__ PFNGLGETPATHSPACINGNVPROC ;
typedef scalar_t__ PFNGLGETPATHPARAMETERIVNVPROC ;
typedef scalar_t__ PFNGLGETPATHPARAMETERFVNVPROC ;
typedef scalar_t__ PFNGLGETPATHMETRICSNVPROC ;
typedef scalar_t__ PFNGLGETPATHMETRICRANGENVPROC ;
typedef scalar_t__ PFNGLGETPATHLENGTHNVPROC ;
typedef scalar_t__ PFNGLGETPATHDASHARRAYNVPROC ;
typedef scalar_t__ PFNGLGETPATHCOORDSNVPROC ;
typedef scalar_t__ PFNGLGETPATHCOMMANDSNVPROC ;
typedef scalar_t__ PFNGLGETPATHCOLORGENIVNVPROC ;
typedef scalar_t__ PFNGLGETPATHCOLORGENFVNVPROC ;
typedef scalar_t__ PFNGLGENPATHSNVPROC ;
typedef scalar_t__ PFNGLDELETEPATHSNVPROC ;
typedef scalar_t__ PFNGLCOVERSTROKEPATHNVPROC ;
typedef scalar_t__ PFNGLCOVERSTROKEPATHINSTANCEDNVPROC ;
typedef scalar_t__ PFNGLCOVERFILLPATHNVPROC ;
typedef scalar_t__ PFNGLCOVERFILLPATHINSTANCEDNVPROC ;
typedef scalar_t__ PFNGLCOPYPATHNVPROC ;


 scalar_t__ FUNC_0 (char*) ;
 scalar_t__ VAR_0 ;
 scalar_t__ VAR_1 ;
 scalar_t__ VAR_2 ;
 scalar_t__ VAR_3 ;
 scalar_t__ VAR_4 ;
 scalar_t__ VAR_5 ;
 scalar_t__ VAR_6 ;
 scalar_t__ VAR_7 ;
 scalar_t__ VAR_8 ;
 scalar_t__ VAR_9 ;
 scalar_t__ VAR_10 ;
 scalar_t__ VAR_11 ;
 scalar_t__ VAR_12 ;
 scalar_t__ VAR_13 ;
 scalar_t__ VAR_14 ;
 scalar_t__ VAR_15 ;
 scalar_t__ VAR_16 ;
 scalar_t__ VAR_17 ;
 scalar_t__ VAR_18 ;
 scalar_t__ VAR_19 ;
 scalar_t__ VAR_20 ;
 scalar_t__ VAR_21 ;
 scalar_t__ VAR_22 ;
 scalar_t__ VAR_23 ;
 scalar_t__ VAR_24 ;
 scalar_t__ VAR_25 ;
 scalar_t__ VAR_26 ;
 scalar_t__ VAR_27 ;
 scalar_t__ VAR_28 ;
 scalar_t__ VAR_29 ;
 scalar_t__ VAR_30 ;
 scalar_t__ VAR_31 ;
 scalar_t__ VAR_32 ;
 scalar_t__ VAR_33 ;
 scalar_t__ VAR_34 ;
 scalar_t__ VAR_35 ;
 scalar_t__ VAR_36 ;
 scalar_t__ VAR_37 ;
 scalar_t__ VAR_38 ;
 scalar_t__ VAR_39 ;
 scalar_t__ VAR_40 ;
 scalar_t__ VAR_41 ;
 scalar_t__ VAR_42 ;
 scalar_t__ VAR_43 ;
 scalar_t__ VAR_44 ;
 scalar_t__ VAR_45 ;
 scalar_t__ VAR_46 ;
 scalar_t__ VAR_47 ;
 scalar_t__ VAR_48 ;

__attribute__((used)) static int FUNC_1()
{
 int VAR_49 = 0;
 VAR_0 = (PFNGLCOPYPATHNVPROC)FUNC_0("glCopyPathNV");
 if(!VAR_0) ++VAR_49;
 VAR_1 = (PFNGLCOVERFILLPATHINSTANCEDNVPROC)FUNC_0("glCoverFillPathInstancedNV");
 if(!VAR_1) ++VAR_49;
 VAR_2 = (PFNGLCOVERFILLPATHNVPROC)FUNC_0("glCoverFillPathNV");
 if(!VAR_2) ++VAR_49;
 VAR_3 = (PFNGLCOVERSTROKEPATHINSTANCEDNVPROC)FUNC_0("glCoverStrokePathInstancedNV");
 if(!VAR_3) ++VAR_49;
 VAR_4 = (PFNGLCOVERSTROKEPATHNVPROC)FUNC_0("glCoverStrokePathNV");
 if(!VAR_4) ++VAR_49;
 VAR_5 = (PFNGLDELETEPATHSNVPROC)FUNC_0("glDeletePathsNV");
 if(!VAR_5) ++VAR_49;
 VAR_6 = (PFNGLGENPATHSNVPROC)FUNC_0("glGenPathsNV");
 if(!VAR_6) ++VAR_49;
 VAR_7 = (PFNGLGETPATHCOLORGENFVNVPROC)FUNC_0("glGetPathColorGenfvNV");
 if(!VAR_7) ++VAR_49;
 VAR_8 = (PFNGLGETPATHCOLORGENIVNVPROC)FUNC_0("glGetPathColorGenivNV");
 if(!VAR_8) ++VAR_49;
 VAR_9 = (PFNGLGETPATHCOMMANDSNVPROC)FUNC_0("glGetPathCommandsNV");
 if(!VAR_9) ++VAR_49;
 VAR_10 = (PFNGLGETPATHCOORDSNVPROC)FUNC_0("glGetPathCoordsNV");
 if(!VAR_10) ++VAR_49;
 VAR_11 = (PFNGLGETPATHDASHARRAYNVPROC)FUNC_0("glGetPathDashArrayNV");
 if(!VAR_11) ++VAR_49;
 VAR_12 = (PFNGLGETPATHLENGTHNVPROC)FUNC_0("glGetPathLengthNV");
 if(!VAR_12) ++VAR_49;
 VAR_13 = (PFNGLGETPATHMETRICRANGENVPROC)FUNC_0("glGetPathMetricRangeNV");
 if(!VAR_13) ++VAR_49;
 VAR_14 = (PFNGLGETPATHMETRICSNVPROC)FUNC_0("glGetPathMetricsNV");
 if(!VAR_14) ++VAR_49;
 VAR_15 = (PFNGLGETPATHPARAMETERFVNVPROC)FUNC_0("glGetPathParameterfvNV");
 if(!VAR_15) ++VAR_49;
 VAR_16 = (PFNGLGETPATHPARAMETERIVNVPROC)FUNC_0("glGetPathParameterivNV");
 if(!VAR_16) ++VAR_49;
 VAR_17 = (PFNGLGETPATHSPACINGNVPROC)FUNC_0("glGetPathSpacingNV");
 if(!VAR_17) ++VAR_49;
 VAR_18 = (PFNGLGETPATHTEXGENFVNVPROC)FUNC_0("glGetPathTexGenfvNV");
 if(!VAR_18) ++VAR_49;
 VAR_19 = (PFNGLGETPATHTEXGENIVNVPROC)FUNC_0("glGetPathTexGenivNV");
 if(!VAR_19) ++VAR_49;
 VAR_20 = (PFNGLINTERPOLATEPATHSNVPROC)FUNC_0("glInterpolatePathsNV");
 if(!VAR_20) ++VAR_49;
 VAR_21 = (PFNGLISPATHNVPROC)FUNC_0("glIsPathNV");
 if(!VAR_21) ++VAR_49;
 VAR_22 = (PFNGLISPOINTINFILLPATHNVPROC)FUNC_0("glIsPointInFillPathNV");
 if(!VAR_22) ++VAR_49;
 VAR_23 = (PFNGLISPOINTINSTROKEPATHNVPROC)FUNC_0("glIsPointInStrokePathNV");
 if(!VAR_23) ++VAR_49;
 VAR_24 = (PFNGLPATHCOLORGENNVPROC)FUNC_0("glPathColorGenNV");
 if(!VAR_24) ++VAR_49;
 VAR_25 = (PFNGLPATHCOMMANDSNVPROC)FUNC_0("glPathCommandsNV");
 if(!VAR_25) ++VAR_49;
 VAR_26 = (PFNGLPATHCOORDSNVPROC)FUNC_0("glPathCoordsNV");
 if(!VAR_26) ++VAR_49;
 VAR_27 = (PFNGLPATHCOVERDEPTHFUNCNVPROC)FUNC_0("glPathCoverDepthFuncNV");
 if(!VAR_27) ++VAR_49;
 VAR_28 = (PFNGLPATHDASHARRAYNVPROC)FUNC_0("glPathDashArrayNV");
 if(!VAR_28) ++VAR_49;
 VAR_29 = (PFNGLPATHFOGGENNVPROC)FUNC_0("glPathFogGenNV");
 if(!VAR_29) ++VAR_49;
 VAR_30 = (PFNGLPATHGLYPHRANGENVPROC)FUNC_0("glPathGlyphRangeNV");
 if(!VAR_30) ++VAR_49;
 VAR_31 = (PFNGLPATHGLYPHSNVPROC)FUNC_0("glPathGlyphsNV");
 if(!VAR_31) ++VAR_49;
 VAR_32 = (PFNGLPATHPARAMETERFNVPROC)FUNC_0("glPathParameterfNV");
 if(!VAR_32) ++VAR_49;
 VAR_33 = (PFNGLPATHPARAMETERFVNVPROC)FUNC_0("glPathParameterfvNV");
 if(!VAR_33) ++VAR_49;
 VAR_34 = (PFNGLPATHPARAMETERINVPROC)FUNC_0("glPathParameteriNV");
 if(!VAR_34) ++VAR_49;
 VAR_35 = (PFNGLPATHPARAMETERIVNVPROC)FUNC_0("glPathParameterivNV");
 if(!VAR_35) ++VAR_49;
 VAR_36 = (PFNGLPATHSTENCILDEPTHOFFSETNVPROC)FUNC_0("glPathStencilDepthOffsetNV");
 if(!VAR_36) ++VAR_49;
 VAR_37 = (PFNGLPATHSTENCILFUNCNVPROC)FUNC_0("glPathStencilFuncNV");
 if(!VAR_37) ++VAR_49;
 VAR_38 = (PFNGLPATHSTRINGNVPROC)FUNC_0("glPathStringNV");
 if(!VAR_38) ++VAR_49;
 VAR_39 = (PFNGLPATHSUBCOMMANDSNVPROC)FUNC_0("glPathSubCommandsNV");
 if(!VAR_39) ++VAR_49;
 VAR_40 = (PFNGLPATHSUBCOORDSNVPROC)FUNC_0("glPathSubCoordsNV");
 if(!VAR_40) ++VAR_49;
 VAR_41 = (PFNGLPATHTEXGENNVPROC)FUNC_0("glPathTexGenNV");
 if(!VAR_41) ++VAR_49;
 VAR_42 = (PFNGLPOINTALONGPATHNVPROC)FUNC_0("glPointAlongPathNV");
 if(!VAR_42) ++VAR_49;
 VAR_43 = (PFNGLSTENCILFILLPATHINSTANCEDNVPROC)FUNC_0("glStencilFillPathInstancedNV");
 if(!VAR_43) ++VAR_49;
 VAR_44 = (PFNGLSTENCILFILLPATHNVPROC)FUNC_0("glStencilFillPathNV");
 if(!VAR_44) ++VAR_49;
 VAR_45 = (PFNGLSTENCILSTROKEPATHINSTANCEDNVPROC)FUNC_0("glStencilStrokePathInstancedNV");
 if(!VAR_45) ++VAR_49;
 VAR_46 = (PFNGLSTENCILSTROKEPATHNVPROC)FUNC_0("glStencilStrokePathNV");
 if(!VAR_46) ++VAR_49;
 VAR_47 = (PFNGLTRANSFORMPATHNVPROC)FUNC_0("glTransformPathNV");
 if(!VAR_47) ++VAR_49;
 VAR_48 = (PFNGLWEIGHTPATHSNVPROC)FUNC_0("glWeightPathsNV");
 if(!VAR_48) ++VAR_49;
 return VAR_49;
}
