
typedef unsigned long size_t;
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;

typedef int bool;






typedef scalar_t__ PFNGLWRITEMASKEXTPROC ;
typedef scalar_t__ PFNGLVARIANTUSVEXTPROC ;
typedef scalar_t__ PFNGLVARIANTUIVEXTPROC ;
typedef scalar_t__ PFNGLVARIANTUBVEXTPROC ;
typedef scalar_t__ PFNGLVARIANTSVEXTPROC ;
typedef scalar_t__ PFNGLVARIANTPOINTEREXTPROC ;
typedef scalar_t__ PFNGLVARIANTIVEXTPROC ;
typedef scalar_t__ PFNGLVARIANTFVEXTPROC ;
typedef scalar_t__ PFNGLVARIANTDVEXTPROC ;
typedef scalar_t__ PFNGLVARIANTBVEXTPROC ;
typedef scalar_t__ PFNGLSWIZZLEEXTPROC ;
typedef scalar_t__ PFNGLSHADEROP3EXTPROC ;
typedef scalar_t__ PFNGLSHADEROP2EXTPROC ;
typedef scalar_t__ PFNGLSHADEROP1EXTPROC ;
typedef scalar_t__ PFNGLSETLOCALCONSTANTEXTPROC ;
typedef scalar_t__ PFNGLSETINVARIANTEXTPROC ;
typedef scalar_t__ PFNGLISVARIANTENABLEDEXTPROC ;
typedef scalar_t__ PFNGLINSERTCOMPONENTEXTPROC ;
typedef scalar_t__ PFNGLGETVARIANTPOINTERVEXTPROC ;
typedef scalar_t__ PFNGLGETVARIANTINTEGERVEXTPROC ;
typedef scalar_t__ PFNGLGETVARIANTFLOATVEXTPROC ;
typedef scalar_t__ PFNGLGETVARIANTBOOLEANVEXTPROC ;
typedef scalar_t__ PFNGLGETLOCALCONSTANTINTEGERVEXTPROC ;
typedef scalar_t__ PFNGLGETLOCALCONSTANTFLOATVEXTPROC ;
typedef scalar_t__ PFNGLGETLOCALCONSTANTBOOLEANVEXTPROC ;
typedef scalar_t__ PFNGLGETINVARIANTINTEGERVEXTPROC ;
typedef scalar_t__ PFNGLGETINVARIANTFLOATVEXTPROC ;
typedef scalar_t__ PFNGLGETINVARIANTBOOLEANVEXTPROC ;
typedef scalar_t__ PFNGLGENVERTEXSHADERSEXTPROC ;
typedef scalar_t__ PFNGLGENSYMBOLSEXTPROC ;
typedef scalar_t__ PFNGLEXTRACTCOMPONENTEXTPROC ;
typedef scalar_t__ PFNGLENDVERTEXSHADEREXTPROC ;
typedef scalar_t__ PFNGLENABLEVARIANTCLIENTSTATEEXTPROC ;
typedef scalar_t__ PFNGLDISABLEVARIANTCLIENTSTATEEXTPROC ;
typedef scalar_t__ PFNGLDELETEVERTEXSHADEREXTPROC ;
typedef scalar_t__ PFNGLBINDVERTEXSHADEREXTPROC ;
typedef scalar_t__ PFNGLBINDTEXTUREUNITPARAMETEREXTPROC ;
typedef scalar_t__ PFNGLBINDTEXGENPARAMETEREXTPROC ;
typedef scalar_t__ PFNGLBINDPARAMETEREXTPROC ;
typedef scalar_t__ PFNGLBINDMATERIALPARAMETEREXTPROC ;
typedef scalar_t__ PFNGLBINDLIGHTPARAMETEREXTPROC ;
typedef scalar_t__ PFNGLBEGINVERTEXSHADEREXTPROC ;


 scalar_t__ FUNC_0 (char*) ;
 scalar_t__ VAR_0 ;
 scalar_t__ VAR_1 ;
 scalar_t__ VAR_2 ;
 scalar_t__ VAR_3 ;
 scalar_t__ VAR_4 ;
 scalar_t__ VAR_5 ;
 scalar_t__ VAR_6 ;
 scalar_t__ VAR_7 ;
 scalar_t__ VAR_8 ;
 scalar_t__ VAR_9 ;
 scalar_t__ VAR_10 ;
 scalar_t__ VAR_11 ;
 scalar_t__ VAR_12 ;
 scalar_t__ VAR_13 ;
 scalar_t__ VAR_14 ;
 scalar_t__ VAR_15 ;
 scalar_t__ VAR_16 ;
 scalar_t__ VAR_17 ;
 scalar_t__ VAR_18 ;
 scalar_t__ VAR_19 ;
 scalar_t__ VAR_20 ;
 scalar_t__ VAR_21 ;
 scalar_t__ VAR_22 ;
 scalar_t__ VAR_23 ;
 scalar_t__ VAR_24 ;
 scalar_t__ VAR_25 ;
 scalar_t__ VAR_26 ;
 scalar_t__ VAR_27 ;
 scalar_t__ VAR_28 ;
 scalar_t__ VAR_29 ;
 scalar_t__ VAR_30 ;
 scalar_t__ VAR_31 ;
 scalar_t__ VAR_32 ;
 scalar_t__ VAR_33 ;
 scalar_t__ VAR_34 ;
 scalar_t__ VAR_35 ;
 scalar_t__ VAR_36 ;
 scalar_t__ VAR_37 ;
 scalar_t__ VAR_38 ;
 scalar_t__ VAR_39 ;
 scalar_t__ VAR_40 ;
 scalar_t__ VAR_41 ;

__attribute__((used)) static int FUNC_1()
{
 int VAR_42 = 0;
 VAR_0 = (PFNGLBEGINVERTEXSHADEREXTPROC)FUNC_0("glBeginVertexShaderEXT");
 if(!VAR_0) ++VAR_42;
 VAR_1 = (PFNGLBINDLIGHTPARAMETEREXTPROC)FUNC_0("glBindLightParameterEXT");
 if(!VAR_1) ++VAR_42;
 VAR_2 = (PFNGLBINDMATERIALPARAMETEREXTPROC)FUNC_0("glBindMaterialParameterEXT");
 if(!VAR_2) ++VAR_42;
 VAR_3 = (PFNGLBINDPARAMETEREXTPROC)FUNC_0("glBindParameterEXT");
 if(!VAR_3) ++VAR_42;
 VAR_4 = (PFNGLBINDTEXGENPARAMETEREXTPROC)FUNC_0("glBindTexGenParameterEXT");
 if(!VAR_4) ++VAR_42;
 VAR_5 = (PFNGLBINDTEXTUREUNITPARAMETEREXTPROC)FUNC_0("glBindTextureUnitParameterEXT");
 if(!VAR_5) ++VAR_42;
 VAR_6 = (PFNGLBINDVERTEXSHADEREXTPROC)FUNC_0("glBindVertexShaderEXT");
 if(!VAR_6) ++VAR_42;
 VAR_7 = (PFNGLDELETEVERTEXSHADEREXTPROC)FUNC_0("glDeleteVertexShaderEXT");
 if(!VAR_7) ++VAR_42;
 VAR_8 = (PFNGLDISABLEVARIANTCLIENTSTATEEXTPROC)FUNC_0("glDisableVariantClientStateEXT");
 if(!VAR_8) ++VAR_42;
 VAR_9 = (PFNGLENABLEVARIANTCLIENTSTATEEXTPROC)FUNC_0("glEnableVariantClientStateEXT");
 if(!VAR_9) ++VAR_42;
 VAR_10 = (PFNGLENDVERTEXSHADEREXTPROC)FUNC_0("glEndVertexShaderEXT");
 if(!VAR_10) ++VAR_42;
 VAR_11 = (PFNGLEXTRACTCOMPONENTEXTPROC)FUNC_0("glExtractComponentEXT");
 if(!VAR_11) ++VAR_42;
 VAR_12 = (PFNGLGENSYMBOLSEXTPROC)FUNC_0("glGenSymbolsEXT");
 if(!VAR_12) ++VAR_42;
 VAR_13 = (PFNGLGENVERTEXSHADERSEXTPROC)FUNC_0("glGenVertexShadersEXT");
 if(!VAR_13) ++VAR_42;
 VAR_14 = (PFNGLGETINVARIANTBOOLEANVEXTPROC)FUNC_0("glGetInvariantBooleanvEXT");
 if(!VAR_14) ++VAR_42;
 VAR_15 = (PFNGLGETINVARIANTFLOATVEXTPROC)FUNC_0("glGetInvariantFloatvEXT");
 if(!VAR_15) ++VAR_42;
 VAR_16 = (PFNGLGETINVARIANTINTEGERVEXTPROC)FUNC_0("glGetInvariantIntegervEXT");
 if(!VAR_16) ++VAR_42;
 VAR_17 = (PFNGLGETLOCALCONSTANTBOOLEANVEXTPROC)FUNC_0("glGetLocalConstantBooleanvEXT");
 if(!VAR_17) ++VAR_42;
 VAR_18 = (PFNGLGETLOCALCONSTANTFLOATVEXTPROC)FUNC_0("glGetLocalConstantFloatvEXT");
 if(!VAR_18) ++VAR_42;
 VAR_19 = (PFNGLGETLOCALCONSTANTINTEGERVEXTPROC)FUNC_0("glGetLocalConstantIntegervEXT");
 if(!VAR_19) ++VAR_42;
 VAR_20 = (PFNGLGETVARIANTBOOLEANVEXTPROC)FUNC_0("glGetVariantBooleanvEXT");
 if(!VAR_20) ++VAR_42;
 VAR_21 = (PFNGLGETVARIANTFLOATVEXTPROC)FUNC_0("glGetVariantFloatvEXT");
 if(!VAR_21) ++VAR_42;
 VAR_22 = (PFNGLGETVARIANTINTEGERVEXTPROC)FUNC_0("glGetVariantIntegervEXT");
 if(!VAR_22) ++VAR_42;
 VAR_23 = (PFNGLGETVARIANTPOINTERVEXTPROC)FUNC_0("glGetVariantPointervEXT");
 if(!VAR_23) ++VAR_42;
 VAR_24 = (PFNGLINSERTCOMPONENTEXTPROC)FUNC_0("glInsertComponentEXT");
 if(!VAR_24) ++VAR_42;
 VAR_25 = (PFNGLISVARIANTENABLEDEXTPROC)FUNC_0("glIsVariantEnabledEXT");
 if(!VAR_25) ++VAR_42;
 VAR_26 = (PFNGLSETINVARIANTEXTPROC)FUNC_0("glSetInvariantEXT");
 if(!VAR_26) ++VAR_42;
 VAR_27 = (PFNGLSETLOCALCONSTANTEXTPROC)FUNC_0("glSetLocalConstantEXT");
 if(!VAR_27) ++VAR_42;
 VAR_28 = (PFNGLSHADEROP1EXTPROC)FUNC_0("glShaderOp1EXT");
 if(!VAR_28) ++VAR_42;
 VAR_29 = (PFNGLSHADEROP2EXTPROC)FUNC_0("glShaderOp2EXT");
 if(!VAR_29) ++VAR_42;
 VAR_30 = (PFNGLSHADEROP3EXTPROC)FUNC_0("glShaderOp3EXT");
 if(!VAR_30) ++VAR_42;
 VAR_31 = (PFNGLSWIZZLEEXTPROC)FUNC_0("glSwizzleEXT");
 if(!VAR_31) ++VAR_42;
 VAR_32 = (PFNGLVARIANTPOINTEREXTPROC)FUNC_0("glVariantPointerEXT");
 if(!VAR_32) ++VAR_42;
 VAR_33 = (PFNGLVARIANTBVEXTPROC)FUNC_0("glVariantbvEXT");
 if(!VAR_33) ++VAR_42;
 VAR_34 = (PFNGLVARIANTDVEXTPROC)FUNC_0("glVariantdvEXT");
 if(!VAR_34) ++VAR_42;
 VAR_35 = (PFNGLVARIANTFVEXTPROC)FUNC_0("glVariantfvEXT");
 if(!VAR_35) ++VAR_42;
 VAR_36 = (PFNGLVARIANTIVEXTPROC)FUNC_0("glVariantivEXT");
 if(!VAR_36) ++VAR_42;
 VAR_37 = (PFNGLVARIANTSVEXTPROC)FUNC_0("glVariantsvEXT");
 if(!VAR_37) ++VAR_42;
 VAR_38 = (PFNGLVARIANTUBVEXTPROC)FUNC_0("glVariantubvEXT");
 if(!VAR_38) ++VAR_42;
 VAR_39 = (PFNGLVARIANTUIVEXTPROC)FUNC_0("glVariantuivEXT");
 if(!VAR_39) ++VAR_42;
 VAR_40 = (PFNGLVARIANTUSVEXTPROC)FUNC_0("glVariantusvEXT");
 if(!VAR_40) ++VAR_42;
 VAR_41 = (PFNGLWRITEMASKEXTPROC)FUNC_0("glWriteMaskEXT");
 if(!VAR_41) ++VAR_42;
 return VAR_42;
}
