
typedef unsigned long size_t;
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;

typedef int bool;






typedef scalar_t__ PFNGLVALIDATEPROGRAMARBPROC ;
typedef scalar_t__ PFNGLUSEPROGRAMOBJECTARBPROC ;
typedef scalar_t__ PFNGLUNIFORMMATRIX4FVARBPROC ;
typedef scalar_t__ PFNGLUNIFORMMATRIX3FVARBPROC ;
typedef scalar_t__ PFNGLUNIFORMMATRIX2FVARBPROC ;
typedef scalar_t__ PFNGLUNIFORM4IVARBPROC ;
typedef scalar_t__ PFNGLUNIFORM4IARBPROC ;
typedef scalar_t__ PFNGLUNIFORM4FVARBPROC ;
typedef scalar_t__ PFNGLUNIFORM4FARBPROC ;
typedef scalar_t__ PFNGLUNIFORM3IVARBPROC ;
typedef scalar_t__ PFNGLUNIFORM3IARBPROC ;
typedef scalar_t__ PFNGLUNIFORM3FVARBPROC ;
typedef scalar_t__ PFNGLUNIFORM3FARBPROC ;
typedef scalar_t__ PFNGLUNIFORM2IVARBPROC ;
typedef scalar_t__ PFNGLUNIFORM2IARBPROC ;
typedef scalar_t__ PFNGLUNIFORM2FVARBPROC ;
typedef scalar_t__ PFNGLUNIFORM2FARBPROC ;
typedef scalar_t__ PFNGLUNIFORM1IVARBPROC ;
typedef scalar_t__ PFNGLUNIFORM1IARBPROC ;
typedef scalar_t__ PFNGLUNIFORM1FVARBPROC ;
typedef scalar_t__ PFNGLUNIFORM1FARBPROC ;
typedef scalar_t__ PFNGLSHADERSOURCEARBPROC ;
typedef scalar_t__ PFNGLLINKPROGRAMARBPROC ;
typedef scalar_t__ PFNGLGETUNIFORMLOCATIONARBPROC ;
typedef scalar_t__ PFNGLGETUNIFORMIVARBPROC ;
typedef scalar_t__ PFNGLGETUNIFORMFVARBPROC ;
typedef scalar_t__ PFNGLGETSHADERSOURCEARBPROC ;
typedef scalar_t__ PFNGLGETOBJECTPARAMETERIVARBPROC ;
typedef scalar_t__ PFNGLGETOBJECTPARAMETERFVARBPROC ;
typedef scalar_t__ PFNGLGETINFOLOGARBPROC ;
typedef scalar_t__ PFNGLGETHANDLEARBPROC ;
typedef scalar_t__ PFNGLGETATTACHEDOBJECTSARBPROC ;
typedef scalar_t__ PFNGLGETACTIVEUNIFORMARBPROC ;
typedef scalar_t__ PFNGLDETACHOBJECTARBPROC ;
typedef scalar_t__ PFNGLDELETEOBJECTARBPROC ;
typedef scalar_t__ PFNGLCREATESHADEROBJECTARBPROC ;
typedef scalar_t__ PFNGLCREATEPROGRAMOBJECTARBPROC ;
typedef scalar_t__ PFNGLCOMPILESHADERARBPROC ;
typedef scalar_t__ PFNGLATTACHOBJECTARBPROC ;


 scalar_t__ FUNC_0 (char*) ;
 scalar_t__ VAR_0 ;
 scalar_t__ VAR_1 ;
 scalar_t__ VAR_2 ;
 scalar_t__ VAR_3 ;
 scalar_t__ VAR_4 ;
 scalar_t__ VAR_5 ;
 scalar_t__ VAR_6 ;
 scalar_t__ VAR_7 ;
 scalar_t__ VAR_8 ;
 scalar_t__ VAR_9 ;
 scalar_t__ VAR_10 ;
 scalar_t__ VAR_11 ;
 scalar_t__ VAR_12 ;
 scalar_t__ VAR_13 ;
 scalar_t__ VAR_14 ;
 scalar_t__ VAR_15 ;
 scalar_t__ VAR_16 ;
 scalar_t__ VAR_17 ;
 scalar_t__ VAR_18 ;
 scalar_t__ VAR_19 ;
 scalar_t__ VAR_20 ;
 scalar_t__ VAR_21 ;
 scalar_t__ VAR_22 ;
 scalar_t__ VAR_23 ;
 scalar_t__ VAR_24 ;
 scalar_t__ VAR_25 ;
 scalar_t__ VAR_26 ;
 scalar_t__ VAR_27 ;
 scalar_t__ VAR_28 ;
 scalar_t__ VAR_29 ;
 scalar_t__ VAR_30 ;
 scalar_t__ VAR_31 ;
 scalar_t__ VAR_32 ;
 scalar_t__ VAR_33 ;
 scalar_t__ VAR_34 ;
 scalar_t__ VAR_35 ;
 scalar_t__ VAR_36 ;
 scalar_t__ VAR_37 ;
 scalar_t__ VAR_38 ;

__attribute__((used)) static int FUNC_1()
{
 int VAR_39 = 0;
 VAR_0 = (PFNGLATTACHOBJECTARBPROC)FUNC_0("glAttachObjectARB");
 if(!VAR_0) ++VAR_39;
 VAR_1 = (PFNGLCOMPILESHADERARBPROC)FUNC_0("glCompileShaderARB");
 if(!VAR_1) ++VAR_39;
 VAR_2 = (PFNGLCREATEPROGRAMOBJECTARBPROC)FUNC_0("glCreateProgramObjectARB");
 if(!VAR_2) ++VAR_39;
 VAR_3 = (PFNGLCREATESHADEROBJECTARBPROC)FUNC_0("glCreateShaderObjectARB");
 if(!VAR_3) ++VAR_39;
 VAR_4 = (PFNGLDELETEOBJECTARBPROC)FUNC_0("glDeleteObjectARB");
 if(!VAR_4) ++VAR_39;
 VAR_5 = (PFNGLDETACHOBJECTARBPROC)FUNC_0("glDetachObjectARB");
 if(!VAR_5) ++VAR_39;
 VAR_6 = (PFNGLGETACTIVEUNIFORMARBPROC)FUNC_0("glGetActiveUniformARB");
 if(!VAR_6) ++VAR_39;
 VAR_7 = (PFNGLGETATTACHEDOBJECTSARBPROC)FUNC_0("glGetAttachedObjectsARB");
 if(!VAR_7) ++VAR_39;
 VAR_8 = (PFNGLGETHANDLEARBPROC)FUNC_0("glGetHandleARB");
 if(!VAR_8) ++VAR_39;
 VAR_9 = (PFNGLGETINFOLOGARBPROC)FUNC_0("glGetInfoLogARB");
 if(!VAR_9) ++VAR_39;
 VAR_10 = (PFNGLGETOBJECTPARAMETERFVARBPROC)FUNC_0("glGetObjectParameterfvARB");
 if(!VAR_10) ++VAR_39;
 VAR_11 = (PFNGLGETOBJECTPARAMETERIVARBPROC)FUNC_0("glGetObjectParameterivARB");
 if(!VAR_11) ++VAR_39;
 VAR_12 = (PFNGLGETSHADERSOURCEARBPROC)FUNC_0("glGetShaderSourceARB");
 if(!VAR_12) ++VAR_39;
 VAR_13 = (PFNGLGETUNIFORMLOCATIONARBPROC)FUNC_0("glGetUniformLocationARB");
 if(!VAR_13) ++VAR_39;
 VAR_14 = (PFNGLGETUNIFORMFVARBPROC)FUNC_0("glGetUniformfvARB");
 if(!VAR_14) ++VAR_39;
 VAR_15 = (PFNGLGETUNIFORMIVARBPROC)FUNC_0("glGetUniformivARB");
 if(!VAR_15) ++VAR_39;
 VAR_16 = (PFNGLLINKPROGRAMARBPROC)FUNC_0("glLinkProgramARB");
 if(!VAR_16) ++VAR_39;
 VAR_17 = (PFNGLSHADERSOURCEARBPROC)FUNC_0("glShaderSourceARB");
 if(!VAR_17) ++VAR_39;
 VAR_18 = (PFNGLUNIFORM1FARBPROC)FUNC_0("glUniform1fARB");
 if(!VAR_18) ++VAR_39;
 VAR_19 = (PFNGLUNIFORM1FVARBPROC)FUNC_0("glUniform1fvARB");
 if(!VAR_19) ++VAR_39;
 VAR_20 = (PFNGLUNIFORM1IARBPROC)FUNC_0("glUniform1iARB");
 if(!VAR_20) ++VAR_39;
 VAR_21 = (PFNGLUNIFORM1IVARBPROC)FUNC_0("glUniform1ivARB");
 if(!VAR_21) ++VAR_39;
 VAR_22 = (PFNGLUNIFORM2FARBPROC)FUNC_0("glUniform2fARB");
 if(!VAR_22) ++VAR_39;
 VAR_23 = (PFNGLUNIFORM2FVARBPROC)FUNC_0("glUniform2fvARB");
 if(!VAR_23) ++VAR_39;
 VAR_24 = (PFNGLUNIFORM2IARBPROC)FUNC_0("glUniform2iARB");
 if(!VAR_24) ++VAR_39;
 VAR_25 = (PFNGLUNIFORM2IVARBPROC)FUNC_0("glUniform2ivARB");
 if(!VAR_25) ++VAR_39;
 VAR_26 = (PFNGLUNIFORM3FARBPROC)FUNC_0("glUniform3fARB");
 if(!VAR_26) ++VAR_39;
 VAR_27 = (PFNGLUNIFORM3FVARBPROC)FUNC_0("glUniform3fvARB");
 if(!VAR_27) ++VAR_39;
 VAR_28 = (PFNGLUNIFORM3IARBPROC)FUNC_0("glUniform3iARB");
 if(!VAR_28) ++VAR_39;
 VAR_29 = (PFNGLUNIFORM3IVARBPROC)FUNC_0("glUniform3ivARB");
 if(!VAR_29) ++VAR_39;
 VAR_30 = (PFNGLUNIFORM4FARBPROC)FUNC_0("glUniform4fARB");
 if(!VAR_30) ++VAR_39;
 VAR_31 = (PFNGLUNIFORM4FVARBPROC)FUNC_0("glUniform4fvARB");
 if(!VAR_31) ++VAR_39;
 VAR_32 = (PFNGLUNIFORM4IARBPROC)FUNC_0("glUniform4iARB");
 if(!VAR_32) ++VAR_39;
 VAR_33 = (PFNGLUNIFORM4IVARBPROC)FUNC_0("glUniform4ivARB");
 if(!VAR_33) ++VAR_39;
 VAR_34 = (PFNGLUNIFORMMATRIX2FVARBPROC)FUNC_0("glUniformMatrix2fvARB");
 if(!VAR_34) ++VAR_39;
 VAR_35 = (PFNGLUNIFORMMATRIX3FVARBPROC)FUNC_0("glUniformMatrix3fvARB");
 if(!VAR_35) ++VAR_39;
 VAR_36 = (PFNGLUNIFORMMATRIX4FVARBPROC)FUNC_0("glUniformMatrix4fvARB");
 if(!VAR_36) ++VAR_39;
 VAR_37 = (PFNGLUSEPROGRAMOBJECTARBPROC)FUNC_0("glUseProgramObjectARB");
 if(!VAR_37) ++VAR_39;
 VAR_38 = (PFNGLVALIDATEPROGRAMARBPROC)FUNC_0("glValidateProgramARB");
 if(!VAR_38) ++VAR_39;
 return VAR_39;
}
