
typedef unsigned long size_t;
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;

typedef int bool;






typedef scalar_t__ PFNGLUNIFORMSUBROUTINESUIVPROC ;
typedef scalar_t__ PFNGLUNIFORMMATRIX4X3DVPROC ;
typedef scalar_t__ PFNGLUNIFORMMATRIX4X2DVPROC ;
typedef scalar_t__ PFNGLUNIFORMMATRIX4DVPROC ;
typedef scalar_t__ PFNGLUNIFORMMATRIX3X4DVPROC ;
typedef scalar_t__ PFNGLUNIFORMMATRIX3X2DVPROC ;
typedef scalar_t__ PFNGLUNIFORMMATRIX3DVPROC ;
typedef scalar_t__ PFNGLUNIFORMMATRIX2X4DVPROC ;
typedef scalar_t__ PFNGLUNIFORMMATRIX2X3DVPROC ;
typedef scalar_t__ PFNGLUNIFORMMATRIX2DVPROC ;
typedef scalar_t__ PFNGLUNIFORM4DVPROC ;
typedef scalar_t__ PFNGLUNIFORM4DPROC ;
typedef scalar_t__ PFNGLUNIFORM3DVPROC ;
typedef scalar_t__ PFNGLUNIFORM3DPROC ;
typedef scalar_t__ PFNGLUNIFORM2DVPROC ;
typedef scalar_t__ PFNGLUNIFORM2DPROC ;
typedef scalar_t__ PFNGLUNIFORM1DVPROC ;
typedef scalar_t__ PFNGLUNIFORM1DPROC ;
typedef scalar_t__ PFNGLRESUMETRANSFORMFEEDBACKPROC ;
typedef scalar_t__ PFNGLPAUSETRANSFORMFEEDBACKPROC ;
typedef scalar_t__ PFNGLPATCHPARAMETERIPROC ;
typedef scalar_t__ PFNGLPATCHPARAMETERFVPROC ;
typedef scalar_t__ PFNGLMINSAMPLESHADINGPROC ;
typedef scalar_t__ PFNGLISTRANSFORMFEEDBACKPROC ;
typedef scalar_t__ PFNGLGETUNIFORMSUBROUTINEUIVPROC ;
typedef scalar_t__ PFNGLGETUNIFORMDVPROC ;
typedef scalar_t__ PFNGLGETSUBROUTINEUNIFORMLOCATIONPROC ;
typedef scalar_t__ PFNGLGETSUBROUTINEINDEXPROC ;
typedef scalar_t__ PFNGLGETQUERYINDEXEDIVPROC ;
typedef scalar_t__ PFNGLGETPROGRAMSTAGEIVPROC ;
typedef scalar_t__ PFNGLGETACTIVESUBROUTINEUNIFORMNAMEPROC ;
typedef scalar_t__ PFNGLGETACTIVESUBROUTINEUNIFORMIVPROC ;
typedef scalar_t__ PFNGLGETACTIVESUBROUTINENAMEPROC ;
typedef scalar_t__ PFNGLGENTRANSFORMFEEDBACKSPROC ;
typedef scalar_t__ PFNGLENDQUERYINDEXEDPROC ;
typedef scalar_t__ PFNGLDRAWTRANSFORMFEEDBACKSTREAMPROC ;
typedef scalar_t__ PFNGLDRAWTRANSFORMFEEDBACKPROC ;
typedef scalar_t__ PFNGLDRAWELEMENTSINDIRECTPROC ;
typedef scalar_t__ PFNGLDRAWARRAYSINDIRECTPROC ;
typedef scalar_t__ PFNGLDELETETRANSFORMFEEDBACKSPROC ;
typedef scalar_t__ PFNGLBLENDFUNCSEPARATEIPROC ;
typedef scalar_t__ PFNGLBLENDFUNCIPROC ;
typedef scalar_t__ PFNGLBLENDEQUATIONSEPARATEIPROC ;
typedef scalar_t__ PFNGLBLENDEQUATIONIPROC ;
typedef scalar_t__ PFNGLBINDTRANSFORMFEEDBACKPROC ;
typedef scalar_t__ PFNGLBEGINQUERYINDEXEDPROC ;


 scalar_t__ FUNC_0 (char*) ;
 scalar_t__ VAR_0 ;
 scalar_t__ VAR_1 ;
 scalar_t__ VAR_2 ;
 scalar_t__ VAR_3 ;
 scalar_t__ VAR_4 ;
 scalar_t__ VAR_5 ;
 scalar_t__ VAR_6 ;
 scalar_t__ VAR_7 ;
 scalar_t__ VAR_8 ;
 scalar_t__ VAR_9 ;
 scalar_t__ VAR_10 ;
 scalar_t__ VAR_11 ;
 scalar_t__ VAR_12 ;
 scalar_t__ VAR_13 ;
 scalar_t__ VAR_14 ;
 scalar_t__ VAR_15 ;
 scalar_t__ VAR_16 ;
 scalar_t__ VAR_17 ;
 scalar_t__ VAR_18 ;
 scalar_t__ VAR_19 ;
 scalar_t__ VAR_20 ;
 scalar_t__ VAR_21 ;
 scalar_t__ VAR_22 ;
 scalar_t__ VAR_23 ;
 scalar_t__ VAR_24 ;
 scalar_t__ VAR_25 ;
 scalar_t__ VAR_26 ;
 scalar_t__ VAR_27 ;
 scalar_t__ VAR_28 ;
 scalar_t__ VAR_29 ;
 scalar_t__ VAR_30 ;
 scalar_t__ VAR_31 ;
 scalar_t__ VAR_32 ;
 scalar_t__ VAR_33 ;
 scalar_t__ VAR_34 ;
 scalar_t__ VAR_35 ;
 scalar_t__ VAR_36 ;
 scalar_t__ VAR_37 ;
 scalar_t__ VAR_38 ;
 scalar_t__ VAR_39 ;
 scalar_t__ VAR_40 ;
 scalar_t__ VAR_41 ;
 scalar_t__ VAR_42 ;
 scalar_t__ VAR_43 ;
 scalar_t__ VAR_44 ;
 scalar_t__ VAR_45 ;

__attribute__((used)) static int FUNC_1()
{
 int VAR_46 = 0;
 VAR_0 = (PFNGLBEGINQUERYINDEXEDPROC)FUNC_0("glBeginQueryIndexed");
 if(!VAR_0) ++VAR_46;
 VAR_1 = (PFNGLBINDTRANSFORMFEEDBACKPROC)FUNC_0("glBindTransformFeedback");
 if(!VAR_1) ++VAR_46;
 VAR_2 = (PFNGLBLENDEQUATIONSEPARATEIPROC)FUNC_0("glBlendEquationSeparatei");
 if(!VAR_2) ++VAR_46;
 VAR_3 = (PFNGLBLENDEQUATIONIPROC)FUNC_0("glBlendEquationi");
 if(!VAR_3) ++VAR_46;
 VAR_4 = (PFNGLBLENDFUNCSEPARATEIPROC)FUNC_0("glBlendFuncSeparatei");
 if(!VAR_4) ++VAR_46;
 VAR_5 = (PFNGLBLENDFUNCIPROC)FUNC_0("glBlendFunci");
 if(!VAR_5) ++VAR_46;
 VAR_6 = (PFNGLDELETETRANSFORMFEEDBACKSPROC)FUNC_0("glDeleteTransformFeedbacks");
 if(!VAR_6) ++VAR_46;
 VAR_7 = (PFNGLDRAWARRAYSINDIRECTPROC)FUNC_0("glDrawArraysIndirect");
 if(!VAR_7) ++VAR_46;
 VAR_8 = (PFNGLDRAWELEMENTSINDIRECTPROC)FUNC_0("glDrawElementsIndirect");
 if(!VAR_8) ++VAR_46;
 VAR_9 = (PFNGLDRAWTRANSFORMFEEDBACKPROC)FUNC_0("glDrawTransformFeedback");
 if(!VAR_9) ++VAR_46;
 VAR_10 = (PFNGLDRAWTRANSFORMFEEDBACKSTREAMPROC)FUNC_0("glDrawTransformFeedbackStream");
 if(!VAR_10) ++VAR_46;
 VAR_11 = (PFNGLENDQUERYINDEXEDPROC)FUNC_0("glEndQueryIndexed");
 if(!VAR_11) ++VAR_46;
 VAR_12 = (PFNGLGENTRANSFORMFEEDBACKSPROC)FUNC_0("glGenTransformFeedbacks");
 if(!VAR_12) ++VAR_46;
 VAR_13 = (PFNGLGETACTIVESUBROUTINENAMEPROC)FUNC_0("glGetActiveSubroutineName");
 if(!VAR_13) ++VAR_46;
 VAR_14 = (PFNGLGETACTIVESUBROUTINEUNIFORMNAMEPROC)FUNC_0("glGetActiveSubroutineUniformName");
 if(!VAR_14) ++VAR_46;
 VAR_15 = (PFNGLGETACTIVESUBROUTINEUNIFORMIVPROC)FUNC_0("glGetActiveSubroutineUniformiv");
 if(!VAR_15) ++VAR_46;
 VAR_16 = (PFNGLGETPROGRAMSTAGEIVPROC)FUNC_0("glGetProgramStageiv");
 if(!VAR_16) ++VAR_46;
 VAR_17 = (PFNGLGETQUERYINDEXEDIVPROC)FUNC_0("glGetQueryIndexediv");
 if(!VAR_17) ++VAR_46;
 VAR_18 = (PFNGLGETSUBROUTINEINDEXPROC)FUNC_0("glGetSubroutineIndex");
 if(!VAR_18) ++VAR_46;
 VAR_19 = (PFNGLGETSUBROUTINEUNIFORMLOCATIONPROC)FUNC_0("glGetSubroutineUniformLocation");
 if(!VAR_19) ++VAR_46;
 VAR_20 = (PFNGLGETUNIFORMSUBROUTINEUIVPROC)FUNC_0("glGetUniformSubroutineuiv");
 if(!VAR_20) ++VAR_46;
 VAR_21 = (PFNGLGETUNIFORMDVPROC)FUNC_0("glGetUniformdv");
 if(!VAR_21) ++VAR_46;
 VAR_22 = (PFNGLISTRANSFORMFEEDBACKPROC)FUNC_0("glIsTransformFeedback");
 if(!VAR_22) ++VAR_46;
 VAR_23 = (PFNGLMINSAMPLESHADINGPROC)FUNC_0("glMinSampleShading");
 if(!VAR_23) ++VAR_46;
 VAR_24 = (PFNGLPATCHPARAMETERFVPROC)FUNC_0("glPatchParameterfv");
 if(!VAR_24) ++VAR_46;
 VAR_25 = (PFNGLPATCHPARAMETERIPROC)FUNC_0("glPatchParameteri");
 if(!VAR_25) ++VAR_46;
 VAR_26 = (PFNGLPAUSETRANSFORMFEEDBACKPROC)FUNC_0("glPauseTransformFeedback");
 if(!VAR_26) ++VAR_46;
 VAR_27 = (PFNGLRESUMETRANSFORMFEEDBACKPROC)FUNC_0("glResumeTransformFeedback");
 if(!VAR_27) ++VAR_46;
 VAR_28 = (PFNGLUNIFORM1DPROC)FUNC_0("glUniform1d");
 if(!VAR_28) ++VAR_46;
 VAR_29 = (PFNGLUNIFORM1DVPROC)FUNC_0("glUniform1dv");
 if(!VAR_29) ++VAR_46;
 VAR_30 = (PFNGLUNIFORM2DPROC)FUNC_0("glUniform2d");
 if(!VAR_30) ++VAR_46;
 VAR_31 = (PFNGLUNIFORM2DVPROC)FUNC_0("glUniform2dv");
 if(!VAR_31) ++VAR_46;
 VAR_32 = (PFNGLUNIFORM3DPROC)FUNC_0("glUniform3d");
 if(!VAR_32) ++VAR_46;
 VAR_33 = (PFNGLUNIFORM3DVPROC)FUNC_0("glUniform3dv");
 if(!VAR_33) ++VAR_46;
 VAR_34 = (PFNGLUNIFORM4DPROC)FUNC_0("glUniform4d");
 if(!VAR_34) ++VAR_46;
 VAR_35 = (PFNGLUNIFORM4DVPROC)FUNC_0("glUniform4dv");
 if(!VAR_35) ++VAR_46;
 VAR_36 = (PFNGLUNIFORMMATRIX2DVPROC)FUNC_0("glUniformMatrix2dv");
 if(!VAR_36) ++VAR_46;
 VAR_37 = (PFNGLUNIFORMMATRIX2X3DVPROC)FUNC_0("glUniformMatrix2x3dv");
 if(!VAR_37) ++VAR_46;
 VAR_38 = (PFNGLUNIFORMMATRIX2X4DVPROC)FUNC_0("glUniformMatrix2x4dv");
 if(!VAR_38) ++VAR_46;
 VAR_39 = (PFNGLUNIFORMMATRIX3DVPROC)FUNC_0("glUniformMatrix3dv");
 if(!VAR_39) ++VAR_46;
 VAR_40 = (PFNGLUNIFORMMATRIX3X2DVPROC)FUNC_0("glUniformMatrix3x2dv");
 if(!VAR_40) ++VAR_46;
 VAR_41 = (PFNGLUNIFORMMATRIX3X4DVPROC)FUNC_0("glUniformMatrix3x4dv");
 if(!VAR_41) ++VAR_46;
 VAR_42 = (PFNGLUNIFORMMATRIX4DVPROC)FUNC_0("glUniformMatrix4dv");
 if(!VAR_42) ++VAR_46;
 VAR_43 = (PFNGLUNIFORMMATRIX4X2DVPROC)FUNC_0("glUniformMatrix4x2dv");
 if(!VAR_43) ++VAR_46;
 VAR_44 = (PFNGLUNIFORMMATRIX4X3DVPROC)FUNC_0("glUniformMatrix4x3dv");
 if(!VAR_44) ++VAR_46;
 VAR_45 = (PFNGLUNIFORMSUBROUTINESUIVPROC)FUNC_0("glUniformSubroutinesuiv");
 if(!VAR_45) ++VAR_46;
 return VAR_46;
}
