
typedef unsigned long size_t;
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;

typedef int bool;






typedef scalar_t__ PFNGLVERTEXATTRIBIPOINTERPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIBI4USVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIBI4UIVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIBI4UIPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIBI4UBVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIBI4SVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIBI4IVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIBI4IPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIBI4BVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIBI3UIVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIBI3UIPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIBI3IVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIBI3IPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIBI2UIVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIBI2UIPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIBI2IVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIBI2IPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIBI1UIVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIBI1UIPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIBI1IVPROC ;
typedef scalar_t__ PFNGLVERTEXATTRIBI1IPROC ;
typedef scalar_t__ PFNGLUNIFORM4UIVPROC ;
typedef scalar_t__ PFNGLUNIFORM4UIPROC ;
typedef scalar_t__ PFNGLUNIFORM3UIVPROC ;
typedef scalar_t__ PFNGLUNIFORM3UIPROC ;
typedef scalar_t__ PFNGLUNIFORM2UIVPROC ;
typedef scalar_t__ PFNGLUNIFORM2UIPROC ;
typedef scalar_t__ PFNGLUNIFORM1UIVPROC ;
typedef scalar_t__ PFNGLUNIFORM1UIPROC ;
typedef scalar_t__ PFNGLTRANSFORMFEEDBACKVARYINGSPROC ;
typedef scalar_t__ PFNGLTEXPARAMETERIUIVPROC ;
typedef scalar_t__ PFNGLTEXPARAMETERIIVPROC ;
typedef scalar_t__ PFNGLRENDERBUFFERSTORAGEPROC ;
typedef scalar_t__ PFNGLRENDERBUFFERSTORAGEMULTISAMPLEPROC ;
typedef scalar_t__ PFNGLMAPBUFFERRANGEPROC ;
typedef scalar_t__ PFNGLISVERTEXARRAYPROC ;
typedef scalar_t__ PFNGLISRENDERBUFFERPROC ;
typedef scalar_t__ PFNGLISFRAMEBUFFERPROC ;
typedef scalar_t__ PFNGLISENABLEDIPROC ;
typedef scalar_t__ PFNGLGETVERTEXATTRIBIUIVPROC ;
typedef scalar_t__ PFNGLGETVERTEXATTRIBIIVPROC ;
typedef scalar_t__ PFNGLGETUNIFORMUIVPROC ;
typedef scalar_t__ PFNGLGETTRANSFORMFEEDBACKVARYINGPROC ;
typedef scalar_t__ PFNGLGETTEXPARAMETERIUIVPROC ;
typedef scalar_t__ PFNGLGETTEXPARAMETERIIVPROC ;
typedef scalar_t__ PFNGLGETSTRINGIPROC ;
typedef scalar_t__ PFNGLGETRENDERBUFFERPARAMETERIVPROC ;
typedef scalar_t__ PFNGLGETINTEGERI_VPROC ;
typedef scalar_t__ PFNGLGETFRAMEBUFFERATTACHMENTPARAMETERIVPROC ;
typedef scalar_t__ PFNGLGETFRAGDATALOCATIONPROC ;
typedef scalar_t__ PFNGLGETBOOLEANI_VPROC ;
typedef scalar_t__ PFNGLGENVERTEXARRAYSPROC ;
typedef scalar_t__ PFNGLGENRENDERBUFFERSPROC ;
typedef scalar_t__ PFNGLGENFRAMEBUFFERSPROC ;
typedef scalar_t__ PFNGLGENERATEMIPMAPPROC ;
typedef scalar_t__ PFNGLFRAMEBUFFERTEXTURELAYERPROC ;
typedef scalar_t__ PFNGLFRAMEBUFFERTEXTURE3DPROC ;
typedef scalar_t__ PFNGLFRAMEBUFFERTEXTURE2DPROC ;
typedef scalar_t__ PFNGLFRAMEBUFFERTEXTURE1DPROC ;
typedef scalar_t__ PFNGLFRAMEBUFFERRENDERBUFFERPROC ;
typedef scalar_t__ PFNGLFLUSHMAPPEDBUFFERRANGEPROC ;
typedef scalar_t__ PFNGLENDTRANSFORMFEEDBACKPROC ;
typedef scalar_t__ PFNGLENDCONDITIONALRENDERPROC ;
typedef scalar_t__ PFNGLENABLEIPROC ;
typedef scalar_t__ PFNGLDISABLEIPROC ;
typedef scalar_t__ PFNGLDELETEVERTEXARRAYSPROC ;
typedef scalar_t__ PFNGLDELETERENDERBUFFERSPROC ;
typedef scalar_t__ PFNGLDELETEFRAMEBUFFERSPROC ;
typedef scalar_t__ PFNGLCOLORMASKIPROC ;
typedef scalar_t__ PFNGLCLEARBUFFERUIVPROC ;
typedef scalar_t__ PFNGLCLEARBUFFERIVPROC ;
typedef scalar_t__ PFNGLCLEARBUFFERFVPROC ;
typedef scalar_t__ PFNGLCLEARBUFFERFIPROC ;
typedef scalar_t__ PFNGLCLAMPCOLORPROC ;
typedef scalar_t__ PFNGLCHECKFRAMEBUFFERSTATUSPROC ;
typedef scalar_t__ PFNGLBLITFRAMEBUFFERPROC ;
typedef scalar_t__ PFNGLBINDVERTEXARRAYPROC ;
typedef scalar_t__ PFNGLBINDRENDERBUFFERPROC ;
typedef scalar_t__ PFNGLBINDFRAMEBUFFERPROC ;
typedef scalar_t__ PFNGLBINDFRAGDATALOCATIONPROC ;
typedef scalar_t__ PFNGLBINDBUFFERRANGEPROC ;
typedef scalar_t__ PFNGLBINDBUFFERBASEPROC ;
typedef scalar_t__ PFNGLBEGINTRANSFORMFEEDBACKPROC ;
typedef scalar_t__ PFNGLBEGINCONDITIONALRENDERPROC ;


 scalar_t__ FUNC_0 (char*) ;
 scalar_t__ VAR_0 ;
 scalar_t__ VAR_1 ;
 scalar_t__ VAR_2 ;
 scalar_t__ VAR_3 ;
 scalar_t__ VAR_4 ;
 scalar_t__ VAR_5 ;
 scalar_t__ VAR_6 ;
 scalar_t__ VAR_7 ;
 scalar_t__ VAR_8 ;
 scalar_t__ VAR_9 ;
 scalar_t__ VAR_10 ;
 scalar_t__ VAR_11 ;
 scalar_t__ VAR_12 ;
 scalar_t__ VAR_13 ;
 scalar_t__ VAR_14 ;
 scalar_t__ VAR_15 ;
 scalar_t__ VAR_16 ;
 scalar_t__ VAR_17 ;
 scalar_t__ VAR_18 ;
 scalar_t__ VAR_19 ;
 scalar_t__ VAR_20 ;
 scalar_t__ VAR_21 ;
 scalar_t__ VAR_22 ;
 scalar_t__ VAR_23 ;
 scalar_t__ VAR_24 ;
 scalar_t__ VAR_25 ;
 scalar_t__ VAR_26 ;
 scalar_t__ VAR_27 ;
 scalar_t__ VAR_28 ;
 scalar_t__ VAR_29 ;
 scalar_t__ VAR_30 ;
 scalar_t__ VAR_31 ;
 scalar_t__ VAR_32 ;
 scalar_t__ VAR_33 ;
 scalar_t__ VAR_34 ;
 scalar_t__ VAR_35 ;
 scalar_t__ VAR_36 ;
 scalar_t__ VAR_37 ;
 scalar_t__ VAR_38 ;
 scalar_t__ VAR_39 ;
 scalar_t__ VAR_40 ;
 scalar_t__ VAR_41 ;
 scalar_t__ VAR_42 ;
 scalar_t__ VAR_43 ;
 scalar_t__ VAR_44 ;
 scalar_t__ VAR_45 ;
 scalar_t__ VAR_46 ;
 scalar_t__ VAR_47 ;
 scalar_t__ VAR_48 ;
 scalar_t__ VAR_49 ;
 scalar_t__ VAR_50 ;
 scalar_t__ VAR_51 ;
 scalar_t__ VAR_52 ;
 scalar_t__ VAR_53 ;
 scalar_t__ VAR_54 ;
 scalar_t__ VAR_55 ;
 scalar_t__ VAR_56 ;
 scalar_t__ VAR_57 ;
 scalar_t__ VAR_58 ;
 scalar_t__ VAR_59 ;
 scalar_t__ VAR_60 ;
 scalar_t__ VAR_61 ;
 scalar_t__ VAR_62 ;
 scalar_t__ VAR_63 ;
 scalar_t__ VAR_64 ;
 scalar_t__ VAR_65 ;
 scalar_t__ VAR_66 ;
 scalar_t__ VAR_67 ;
 scalar_t__ VAR_68 ;
 scalar_t__ VAR_69 ;
 scalar_t__ VAR_70 ;
 scalar_t__ VAR_71 ;
 scalar_t__ VAR_72 ;
 scalar_t__ VAR_73 ;
 scalar_t__ VAR_74 ;
 scalar_t__ VAR_75 ;
 scalar_t__ VAR_76 ;
 scalar_t__ VAR_77 ;
 scalar_t__ VAR_78 ;
 scalar_t__ VAR_79 ;
 scalar_t__ VAR_80 ;
 scalar_t__ VAR_81 ;
 scalar_t__ VAR_82 ;
 scalar_t__ VAR_83 ;

__attribute__((used)) static int FUNC_1()
{
 int VAR_84 = 0;
 VAR_0 = (PFNGLBEGINCONDITIONALRENDERPROC)FUNC_0("glBeginConditionalRender");
 if(!VAR_0) ++VAR_84;
 VAR_1 = (PFNGLBEGINTRANSFORMFEEDBACKPROC)FUNC_0("glBeginTransformFeedback");
 if(!VAR_1) ++VAR_84;
 VAR_2 = (PFNGLBINDBUFFERBASEPROC)FUNC_0("glBindBufferBase");
 if(!VAR_2) ++VAR_84;
 VAR_3 = (PFNGLBINDBUFFERRANGEPROC)FUNC_0("glBindBufferRange");
 if(!VAR_3) ++VAR_84;
 VAR_4 = (PFNGLBINDFRAGDATALOCATIONPROC)FUNC_0("glBindFragDataLocation");
 if(!VAR_4) ++VAR_84;
 VAR_5 = (PFNGLBINDFRAMEBUFFERPROC)FUNC_0("glBindFramebuffer");
 if(!VAR_5) ++VAR_84;
 VAR_6 = (PFNGLBINDRENDERBUFFERPROC)FUNC_0("glBindRenderbuffer");
 if(!VAR_6) ++VAR_84;
 VAR_7 = (PFNGLBINDVERTEXARRAYPROC)FUNC_0("glBindVertexArray");
 if(!VAR_7) ++VAR_84;
 VAR_8 = (PFNGLBLITFRAMEBUFFERPROC)FUNC_0("glBlitFramebuffer");
 if(!VAR_8) ++VAR_84;
 VAR_9 = (PFNGLCHECKFRAMEBUFFERSTATUSPROC)FUNC_0("glCheckFramebufferStatus");
 if(!VAR_9) ++VAR_84;
 VAR_10 = (PFNGLCLAMPCOLORPROC)FUNC_0("glClampColor");
 if(!VAR_10) ++VAR_84;
 VAR_11 = (PFNGLCLEARBUFFERFIPROC)FUNC_0("glClearBufferfi");
 if(!VAR_11) ++VAR_84;
 VAR_12 = (PFNGLCLEARBUFFERFVPROC)FUNC_0("glClearBufferfv");
 if(!VAR_12) ++VAR_84;
 VAR_13 = (PFNGLCLEARBUFFERIVPROC)FUNC_0("glClearBufferiv");
 if(!VAR_13) ++VAR_84;
 VAR_14 = (PFNGLCLEARBUFFERUIVPROC)FUNC_0("glClearBufferuiv");
 if(!VAR_14) ++VAR_84;
 VAR_15 = (PFNGLCOLORMASKIPROC)FUNC_0("glColorMaski");
 if(!VAR_15) ++VAR_84;
 VAR_16 = (PFNGLDELETEFRAMEBUFFERSPROC)FUNC_0("glDeleteFramebuffers");
 if(!VAR_16) ++VAR_84;
 VAR_17 = (PFNGLDELETERENDERBUFFERSPROC)FUNC_0("glDeleteRenderbuffers");
 if(!VAR_17) ++VAR_84;
 VAR_18 = (PFNGLDELETEVERTEXARRAYSPROC)FUNC_0("glDeleteVertexArrays");
 if(!VAR_18) ++VAR_84;
 VAR_19 = (PFNGLDISABLEIPROC)FUNC_0("glDisablei");
 if(!VAR_19) ++VAR_84;
 VAR_20 = (PFNGLENABLEIPROC)FUNC_0("glEnablei");
 if(!VAR_20) ++VAR_84;
 VAR_21 = (PFNGLENDCONDITIONALRENDERPROC)FUNC_0("glEndConditionalRender");
 if(!VAR_21) ++VAR_84;
 VAR_22 = (PFNGLENDTRANSFORMFEEDBACKPROC)FUNC_0("glEndTransformFeedback");
 if(!VAR_22) ++VAR_84;
 VAR_23 = (PFNGLFLUSHMAPPEDBUFFERRANGEPROC)FUNC_0("glFlushMappedBufferRange");
 if(!VAR_23) ++VAR_84;
 VAR_24 = (PFNGLFRAMEBUFFERRENDERBUFFERPROC)FUNC_0("glFramebufferRenderbuffer");
 if(!VAR_24) ++VAR_84;
 VAR_25 = (PFNGLFRAMEBUFFERTEXTURE1DPROC)FUNC_0("glFramebufferTexture1D");
 if(!VAR_25) ++VAR_84;
 VAR_26 = (PFNGLFRAMEBUFFERTEXTURE2DPROC)FUNC_0("glFramebufferTexture2D");
 if(!VAR_26) ++VAR_84;
 VAR_27 = (PFNGLFRAMEBUFFERTEXTURE3DPROC)FUNC_0("glFramebufferTexture3D");
 if(!VAR_27) ++VAR_84;
 VAR_28 = (PFNGLFRAMEBUFFERTEXTURELAYERPROC)FUNC_0("glFramebufferTextureLayer");
 if(!VAR_28) ++VAR_84;
 VAR_29 = (PFNGLGENFRAMEBUFFERSPROC)FUNC_0("glGenFramebuffers");
 if(!VAR_29) ++VAR_84;
 VAR_30 = (PFNGLGENRENDERBUFFERSPROC)FUNC_0("glGenRenderbuffers");
 if(!VAR_30) ++VAR_84;
 VAR_31 = (PFNGLGENVERTEXARRAYSPROC)FUNC_0("glGenVertexArrays");
 if(!VAR_31) ++VAR_84;
 VAR_32 = (PFNGLGENERATEMIPMAPPROC)FUNC_0("glGenerateMipmap");
 if(!VAR_32) ++VAR_84;
 VAR_33 = (PFNGLGETBOOLEANI_VPROC)FUNC_0("glGetBooleani_v");
 if(!VAR_33) ++VAR_84;
 VAR_34 = (PFNGLGETFRAGDATALOCATIONPROC)FUNC_0("glGetFragDataLocation");
 if(!VAR_34) ++VAR_84;
 VAR_35 = (PFNGLGETFRAMEBUFFERATTACHMENTPARAMETERIVPROC)FUNC_0("glGetFramebufferAttachmentParameteriv");
 if(!VAR_35) ++VAR_84;
 VAR_36 = (PFNGLGETINTEGERI_VPROC)FUNC_0("glGetIntegeri_v");
 if(!VAR_36) ++VAR_84;
 VAR_37 = (PFNGLGETRENDERBUFFERPARAMETERIVPROC)FUNC_0("glGetRenderbufferParameteriv");
 if(!VAR_37) ++VAR_84;
 VAR_38 = (PFNGLGETSTRINGIPROC)FUNC_0("glGetStringi");
 if(!VAR_38) ++VAR_84;
 VAR_39 = (PFNGLGETTEXPARAMETERIIVPROC)FUNC_0("glGetTexParameterIiv");
 if(!VAR_39) ++VAR_84;
 VAR_40 = (PFNGLGETTEXPARAMETERIUIVPROC)FUNC_0("glGetTexParameterIuiv");
 if(!VAR_40) ++VAR_84;
 VAR_41 = (PFNGLGETTRANSFORMFEEDBACKVARYINGPROC)FUNC_0("glGetTransformFeedbackVarying");
 if(!VAR_41) ++VAR_84;
 VAR_42 = (PFNGLGETUNIFORMUIVPROC)FUNC_0("glGetUniformuiv");
 if(!VAR_42) ++VAR_84;
 VAR_43 = (PFNGLGETVERTEXATTRIBIIVPROC)FUNC_0("glGetVertexAttribIiv");
 if(!VAR_43) ++VAR_84;
 VAR_44 = (PFNGLGETVERTEXATTRIBIUIVPROC)FUNC_0("glGetVertexAttribIuiv");
 if(!VAR_44) ++VAR_84;
 VAR_45 = (PFNGLISENABLEDIPROC)FUNC_0("glIsEnabledi");
 if(!VAR_45) ++VAR_84;
 VAR_46 = (PFNGLISFRAMEBUFFERPROC)FUNC_0("glIsFramebuffer");
 if(!VAR_46) ++VAR_84;
 VAR_47 = (PFNGLISRENDERBUFFERPROC)FUNC_0("glIsRenderbuffer");
 if(!VAR_47) ++VAR_84;
 VAR_48 = (PFNGLISVERTEXARRAYPROC)FUNC_0("glIsVertexArray");
 if(!VAR_48) ++VAR_84;
 VAR_49 = (PFNGLMAPBUFFERRANGEPROC)FUNC_0("glMapBufferRange");
 if(!VAR_49) ++VAR_84;
 VAR_50 = (PFNGLRENDERBUFFERSTORAGEPROC)FUNC_0("glRenderbufferStorage");
 if(!VAR_50) ++VAR_84;
 VAR_51 = (PFNGLRENDERBUFFERSTORAGEMULTISAMPLEPROC)FUNC_0("glRenderbufferStorageMultisample");
 if(!VAR_51) ++VAR_84;
 VAR_52 = (PFNGLTEXPARAMETERIIVPROC)FUNC_0("glTexParameterIiv");
 if(!VAR_52) ++VAR_84;
 VAR_53 = (PFNGLTEXPARAMETERIUIVPROC)FUNC_0("glTexParameterIuiv");
 if(!VAR_53) ++VAR_84;
 VAR_54 = (PFNGLTRANSFORMFEEDBACKVARYINGSPROC)FUNC_0("glTransformFeedbackVaryings");
 if(!VAR_54) ++VAR_84;
 VAR_55 = (PFNGLUNIFORM1UIPROC)FUNC_0("glUniform1ui");
 if(!VAR_55) ++VAR_84;
 VAR_56 = (PFNGLUNIFORM1UIVPROC)FUNC_0("glUniform1uiv");
 if(!VAR_56) ++VAR_84;
 VAR_57 = (PFNGLUNIFORM2UIPROC)FUNC_0("glUniform2ui");
 if(!VAR_57) ++VAR_84;
 VAR_58 = (PFNGLUNIFORM2UIVPROC)FUNC_0("glUniform2uiv");
 if(!VAR_58) ++VAR_84;
 VAR_59 = (PFNGLUNIFORM3UIPROC)FUNC_0("glUniform3ui");
 if(!VAR_59) ++VAR_84;
 VAR_60 = (PFNGLUNIFORM3UIVPROC)FUNC_0("glUniform3uiv");
 if(!VAR_60) ++VAR_84;
 VAR_61 = (PFNGLUNIFORM4UIPROC)FUNC_0("glUniform4ui");
 if(!VAR_61) ++VAR_84;
 VAR_62 = (PFNGLUNIFORM4UIVPROC)FUNC_0("glUniform4uiv");
 if(!VAR_62) ++VAR_84;
 VAR_63 = (PFNGLVERTEXATTRIBI1IPROC)FUNC_0("glVertexAttribI1i");
 if(!VAR_63) ++VAR_84;
 VAR_64 = (PFNGLVERTEXATTRIBI1IVPROC)FUNC_0("glVertexAttribI1iv");
 if(!VAR_64) ++VAR_84;
 VAR_65 = (PFNGLVERTEXATTRIBI1UIPROC)FUNC_0("glVertexAttribI1ui");
 if(!VAR_65) ++VAR_84;
 VAR_66 = (PFNGLVERTEXATTRIBI1UIVPROC)FUNC_0("glVertexAttribI1uiv");
 if(!VAR_66) ++VAR_84;
 VAR_67 = (PFNGLVERTEXATTRIBI2IPROC)FUNC_0("glVertexAttribI2i");
 if(!VAR_67) ++VAR_84;
 VAR_68 = (PFNGLVERTEXATTRIBI2IVPROC)FUNC_0("glVertexAttribI2iv");
 if(!VAR_68) ++VAR_84;
 VAR_69 = (PFNGLVERTEXATTRIBI2UIPROC)FUNC_0("glVertexAttribI2ui");
 if(!VAR_69) ++VAR_84;
 VAR_70 = (PFNGLVERTEXATTRIBI2UIVPROC)FUNC_0("glVertexAttribI2uiv");
 if(!VAR_70) ++VAR_84;
 VAR_71 = (PFNGLVERTEXATTRIBI3IPROC)FUNC_0("glVertexAttribI3i");
 if(!VAR_71) ++VAR_84;
 VAR_72 = (PFNGLVERTEXATTRIBI3IVPROC)FUNC_0("glVertexAttribI3iv");
 if(!VAR_72) ++VAR_84;
 VAR_73 = (PFNGLVERTEXATTRIBI3UIPROC)FUNC_0("glVertexAttribI3ui");
 if(!VAR_73) ++VAR_84;
 VAR_74 = (PFNGLVERTEXATTRIBI3UIVPROC)FUNC_0("glVertexAttribI3uiv");
 if(!VAR_74) ++VAR_84;
 VAR_75 = (PFNGLVERTEXATTRIBI4BVPROC)FUNC_0("glVertexAttribI4bv");
 if(!VAR_75) ++VAR_84;
 VAR_76 = (PFNGLVERTEXATTRIBI4IPROC)FUNC_0("glVertexAttribI4i");
 if(!VAR_76) ++VAR_84;
 VAR_77 = (PFNGLVERTEXATTRIBI4IVPROC)FUNC_0("glVertexAttribI4iv");
 if(!VAR_77) ++VAR_84;
 VAR_78 = (PFNGLVERTEXATTRIBI4SVPROC)FUNC_0("glVertexAttribI4sv");
 if(!VAR_78) ++VAR_84;
 VAR_79 = (PFNGLVERTEXATTRIBI4UBVPROC)FUNC_0("glVertexAttribI4ubv");
 if(!VAR_79) ++VAR_84;
 VAR_80 = (PFNGLVERTEXATTRIBI4UIPROC)FUNC_0("glVertexAttribI4ui");
 if(!VAR_80) ++VAR_84;
 VAR_81 = (PFNGLVERTEXATTRIBI4UIVPROC)FUNC_0("glVertexAttribI4uiv");
 if(!VAR_81) ++VAR_84;
 VAR_82 = (PFNGLVERTEXATTRIBI4USVPROC)FUNC_0("glVertexAttribI4usv");
 if(!VAR_82) ++VAR_84;
 VAR_83 = (PFNGLVERTEXATTRIBIPOINTERPROC)FUNC_0("glVertexAttribIPointer");
 if(!VAR_83) ++VAR_84;
 return VAR_84;
}
