
typedef unsigned long size_t;
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;

typedef int bool;






typedef scalar_t__ PFNGLWINDOWPOS3SVPROC ;
typedef scalar_t__ PFNGLWINDOWPOS3SPROC ;
typedef scalar_t__ PFNGLWINDOWPOS3IVPROC ;
typedef scalar_t__ PFNGLWINDOWPOS3IPROC ;
typedef scalar_t__ PFNGLWINDOWPOS3FVPROC ;
typedef scalar_t__ PFNGLWINDOWPOS3FPROC ;
typedef scalar_t__ PFNGLWINDOWPOS3DVPROC ;
typedef scalar_t__ PFNGLWINDOWPOS3DPROC ;
typedef scalar_t__ PFNGLWINDOWPOS2SVPROC ;
typedef scalar_t__ PFNGLWINDOWPOS2SPROC ;
typedef scalar_t__ PFNGLWINDOWPOS2IVPROC ;
typedef scalar_t__ PFNGLWINDOWPOS2IPROC ;
typedef scalar_t__ PFNGLWINDOWPOS2FVPROC ;
typedef scalar_t__ PFNGLWINDOWPOS2FPROC ;
typedef scalar_t__ PFNGLWINDOWPOS2DVPROC ;
typedef scalar_t__ PFNGLWINDOWPOS2DPROC ;
typedef scalar_t__ PFNGLSECONDARYCOLORPOINTERPROC ;
typedef scalar_t__ PFNGLSECONDARYCOLOR3USVPROC ;
typedef scalar_t__ PFNGLSECONDARYCOLOR3USPROC ;
typedef scalar_t__ PFNGLSECONDARYCOLOR3UIVPROC ;
typedef scalar_t__ PFNGLSECONDARYCOLOR3UIPROC ;
typedef scalar_t__ PFNGLSECONDARYCOLOR3UBVPROC ;
typedef scalar_t__ PFNGLSECONDARYCOLOR3UBPROC ;
typedef scalar_t__ PFNGLSECONDARYCOLOR3SVPROC ;
typedef scalar_t__ PFNGLSECONDARYCOLOR3SPROC ;
typedef scalar_t__ PFNGLSECONDARYCOLOR3IVPROC ;
typedef scalar_t__ PFNGLSECONDARYCOLOR3IPROC ;
typedef scalar_t__ PFNGLSECONDARYCOLOR3FVPROC ;
typedef scalar_t__ PFNGLSECONDARYCOLOR3FPROC ;
typedef scalar_t__ PFNGLSECONDARYCOLOR3DVPROC ;
typedef scalar_t__ PFNGLSECONDARYCOLOR3DPROC ;
typedef scalar_t__ PFNGLSECONDARYCOLOR3BVPROC ;
typedef scalar_t__ PFNGLSECONDARYCOLOR3BPROC ;
typedef scalar_t__ PFNGLFOGCOORDPOINTERPROC ;
typedef scalar_t__ PFNGLFOGCOORDFVPROC ;
typedef scalar_t__ PFNGLFOGCOORDFPROC ;
typedef scalar_t__ PFNGLFOGCOORDDVPROC ;
typedef scalar_t__ PFNGLFOGCOORDDPROC ;


 scalar_t__ FUNC_0 (char*) ;
 scalar_t__ VAR_0 ;
 scalar_t__ VAR_1 ;
 scalar_t__ VAR_2 ;
 scalar_t__ VAR_3 ;
 scalar_t__ VAR_4 ;
 scalar_t__ VAR_5 ;
 scalar_t__ VAR_6 ;
 scalar_t__ VAR_7 ;
 scalar_t__ VAR_8 ;
 scalar_t__ VAR_9 ;
 scalar_t__ VAR_10 ;
 scalar_t__ VAR_11 ;
 scalar_t__ VAR_12 ;
 scalar_t__ VAR_13 ;
 scalar_t__ VAR_14 ;
 scalar_t__ VAR_15 ;
 scalar_t__ VAR_16 ;
 scalar_t__ VAR_17 ;
 scalar_t__ VAR_18 ;
 scalar_t__ VAR_19 ;
 scalar_t__ VAR_20 ;
 scalar_t__ VAR_21 ;
 scalar_t__ VAR_22 ;
 scalar_t__ VAR_23 ;
 scalar_t__ VAR_24 ;
 scalar_t__ VAR_25 ;
 scalar_t__ VAR_26 ;
 scalar_t__ VAR_27 ;
 scalar_t__ VAR_28 ;
 scalar_t__ VAR_29 ;
 scalar_t__ VAR_30 ;
 scalar_t__ VAR_31 ;
 scalar_t__ VAR_32 ;
 scalar_t__ VAR_33 ;
 scalar_t__ VAR_34 ;
 scalar_t__ VAR_35 ;
 scalar_t__ VAR_36 ;
 scalar_t__ VAR_37 ;

__attribute__((used)) static int FUNC_1()
{
 int VAR_38 = 0;
 VAR_0 = (PFNGLFOGCOORDPOINTERPROC)FUNC_0("glFogCoordPointer");
 if(!VAR_0) ++VAR_38;
 VAR_1 = (PFNGLFOGCOORDDPROC)FUNC_0("glFogCoordd");
 if(!VAR_1) ++VAR_38;
 VAR_2 = (PFNGLFOGCOORDDVPROC)FUNC_0("glFogCoorddv");
 if(!VAR_2) ++VAR_38;
 VAR_3 = (PFNGLFOGCOORDFPROC)FUNC_0("glFogCoordf");
 if(!VAR_3) ++VAR_38;
 VAR_4 = (PFNGLFOGCOORDFVPROC)FUNC_0("glFogCoordfv");
 if(!VAR_4) ++VAR_38;
 VAR_5 = (PFNGLSECONDARYCOLOR3BPROC)FUNC_0("glSecondaryColor3b");
 if(!VAR_5) ++VAR_38;
 VAR_6 = (PFNGLSECONDARYCOLOR3BVPROC)FUNC_0("glSecondaryColor3bv");
 if(!VAR_6) ++VAR_38;
 VAR_7 = (PFNGLSECONDARYCOLOR3DPROC)FUNC_0("glSecondaryColor3d");
 if(!VAR_7) ++VAR_38;
 VAR_8 = (PFNGLSECONDARYCOLOR3DVPROC)FUNC_0("glSecondaryColor3dv");
 if(!VAR_8) ++VAR_38;
 VAR_9 = (PFNGLSECONDARYCOLOR3FPROC)FUNC_0("glSecondaryColor3f");
 if(!VAR_9) ++VAR_38;
 VAR_10 = (PFNGLSECONDARYCOLOR3FVPROC)FUNC_0("glSecondaryColor3fv");
 if(!VAR_10) ++VAR_38;
 VAR_11 = (PFNGLSECONDARYCOLOR3IPROC)FUNC_0("glSecondaryColor3i");
 if(!VAR_11) ++VAR_38;
 VAR_12 = (PFNGLSECONDARYCOLOR3IVPROC)FUNC_0("glSecondaryColor3iv");
 if(!VAR_12) ++VAR_38;
 VAR_13 = (PFNGLSECONDARYCOLOR3SPROC)FUNC_0("glSecondaryColor3s");
 if(!VAR_13) ++VAR_38;
 VAR_14 = (PFNGLSECONDARYCOLOR3SVPROC)FUNC_0("glSecondaryColor3sv");
 if(!VAR_14) ++VAR_38;
 VAR_15 = (PFNGLSECONDARYCOLOR3UBPROC)FUNC_0("glSecondaryColor3ub");
 if(!VAR_15) ++VAR_38;
 VAR_16 = (PFNGLSECONDARYCOLOR3UBVPROC)FUNC_0("glSecondaryColor3ubv");
 if(!VAR_16) ++VAR_38;
 VAR_17 = (PFNGLSECONDARYCOLOR3UIPROC)FUNC_0("glSecondaryColor3ui");
 if(!VAR_17) ++VAR_38;
 VAR_18 = (PFNGLSECONDARYCOLOR3UIVPROC)FUNC_0("glSecondaryColor3uiv");
 if(!VAR_18) ++VAR_38;
 VAR_19 = (PFNGLSECONDARYCOLOR3USPROC)FUNC_0("glSecondaryColor3us");
 if(!VAR_19) ++VAR_38;
 VAR_20 = (PFNGLSECONDARYCOLOR3USVPROC)FUNC_0("glSecondaryColor3usv");
 if(!VAR_20) ++VAR_38;
 VAR_21 = (PFNGLSECONDARYCOLORPOINTERPROC)FUNC_0("glSecondaryColorPointer");
 if(!VAR_21) ++VAR_38;
 VAR_22 = (PFNGLWINDOWPOS2DPROC)FUNC_0("glWindowPos2d");
 if(!VAR_22) ++VAR_38;
 VAR_23 = (PFNGLWINDOWPOS2DVPROC)FUNC_0("glWindowPos2dv");
 if(!VAR_23) ++VAR_38;
 VAR_24 = (PFNGLWINDOWPOS2FPROC)FUNC_0("glWindowPos2f");
 if(!VAR_24) ++VAR_38;
 VAR_25 = (PFNGLWINDOWPOS2FVPROC)FUNC_0("glWindowPos2fv");
 if(!VAR_25) ++VAR_38;
 VAR_26 = (PFNGLWINDOWPOS2IPROC)FUNC_0("glWindowPos2i");
 if(!VAR_26) ++VAR_38;
 VAR_27 = (PFNGLWINDOWPOS2IVPROC)FUNC_0("glWindowPos2iv");
 if(!VAR_27) ++VAR_38;
 VAR_28 = (PFNGLWINDOWPOS2SPROC)FUNC_0("glWindowPos2s");
 if(!VAR_28) ++VAR_38;
 VAR_29 = (PFNGLWINDOWPOS2SVPROC)FUNC_0("glWindowPos2sv");
 if(!VAR_29) ++VAR_38;
 VAR_30 = (PFNGLWINDOWPOS3DPROC)FUNC_0("glWindowPos3d");
 if(!VAR_30) ++VAR_38;
 VAR_31 = (PFNGLWINDOWPOS3DVPROC)FUNC_0("glWindowPos3dv");
 if(!VAR_31) ++VAR_38;
 VAR_32 = (PFNGLWINDOWPOS3FPROC)FUNC_0("glWindowPos3f");
 if(!VAR_32) ++VAR_38;
 VAR_33 = (PFNGLWINDOWPOS3FVPROC)FUNC_0("glWindowPos3fv");
 if(!VAR_33) ++VAR_38;
 VAR_34 = (PFNGLWINDOWPOS3IPROC)FUNC_0("glWindowPos3i");
 if(!VAR_34) ++VAR_38;
 VAR_35 = (PFNGLWINDOWPOS3IVPROC)FUNC_0("glWindowPos3iv");
 if(!VAR_35) ++VAR_38;
 VAR_36 = (PFNGLWINDOWPOS3SPROC)FUNC_0("glWindowPos3s");
 if(!VAR_36) ++VAR_38;
 VAR_37 = (PFNGLWINDOWPOS3SVPROC)FUNC_0("glWindowPos3sv");
 if(!VAR_37) ++VAR_38;
 return VAR_38;
}
