
typedef unsigned long size_t;
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;

typedef int bool;






typedef scalar_t__ PFNGLVALIDATEPROGRAMPIPELINEPROC ;
typedef scalar_t__ PFNGLUSEPROGRAMSTAGESPROC ;
typedef scalar_t__ PFNGLPROGRAMUNIFORMMATRIX4X3FVPROC ;
typedef scalar_t__ PFNGLPROGRAMUNIFORMMATRIX4X3DVPROC ;
typedef scalar_t__ PFNGLPROGRAMUNIFORMMATRIX4X2FVPROC ;
typedef scalar_t__ PFNGLPROGRAMUNIFORMMATRIX4X2DVPROC ;
typedef scalar_t__ PFNGLPROGRAMUNIFORMMATRIX4FVPROC ;
typedef scalar_t__ PFNGLPROGRAMUNIFORMMATRIX4DVPROC ;
typedef scalar_t__ PFNGLPROGRAMUNIFORMMATRIX3X4FVPROC ;
typedef scalar_t__ PFNGLPROGRAMUNIFORMMATRIX3X4DVPROC ;
typedef scalar_t__ PFNGLPROGRAMUNIFORMMATRIX3X2FVPROC ;
typedef scalar_t__ PFNGLPROGRAMUNIFORMMATRIX3X2DVPROC ;
typedef scalar_t__ PFNGLPROGRAMUNIFORMMATRIX3FVPROC ;
typedef scalar_t__ PFNGLPROGRAMUNIFORMMATRIX3DVPROC ;
typedef scalar_t__ PFNGLPROGRAMUNIFORMMATRIX2X4FVPROC ;
typedef scalar_t__ PFNGLPROGRAMUNIFORMMATRIX2X4DVPROC ;
typedef scalar_t__ PFNGLPROGRAMUNIFORMMATRIX2X3FVPROC ;
typedef scalar_t__ PFNGLPROGRAMUNIFORMMATRIX2X3DVPROC ;
typedef scalar_t__ PFNGLPROGRAMUNIFORMMATRIX2FVPROC ;
typedef scalar_t__ PFNGLPROGRAMUNIFORMMATRIX2DVPROC ;
typedef scalar_t__ PFNGLPROGRAMUNIFORM4UIVPROC ;
typedef scalar_t__ PFNGLPROGRAMUNIFORM4UIPROC ;
typedef scalar_t__ PFNGLPROGRAMUNIFORM4IVPROC ;
typedef scalar_t__ PFNGLPROGRAMUNIFORM4IPROC ;
typedef scalar_t__ PFNGLPROGRAMUNIFORM4FVPROC ;
typedef scalar_t__ PFNGLPROGRAMUNIFORM4FPROC ;
typedef scalar_t__ PFNGLPROGRAMUNIFORM4DVPROC ;
typedef scalar_t__ PFNGLPROGRAMUNIFORM4DPROC ;
typedef scalar_t__ PFNGLPROGRAMUNIFORM3UIVPROC ;
typedef scalar_t__ PFNGLPROGRAMUNIFORM3UIPROC ;
typedef scalar_t__ PFNGLPROGRAMUNIFORM3IVPROC ;
typedef scalar_t__ PFNGLPROGRAMUNIFORM3IPROC ;
typedef scalar_t__ PFNGLPROGRAMUNIFORM3FVPROC ;
typedef scalar_t__ PFNGLPROGRAMUNIFORM3FPROC ;
typedef scalar_t__ PFNGLPROGRAMUNIFORM3DVPROC ;
typedef scalar_t__ PFNGLPROGRAMUNIFORM3DPROC ;
typedef scalar_t__ PFNGLPROGRAMUNIFORM2UIVPROC ;
typedef scalar_t__ PFNGLPROGRAMUNIFORM2UIPROC ;
typedef scalar_t__ PFNGLPROGRAMUNIFORM2IVPROC ;
typedef scalar_t__ PFNGLPROGRAMUNIFORM2IPROC ;
typedef scalar_t__ PFNGLPROGRAMUNIFORM2FVPROC ;
typedef scalar_t__ PFNGLPROGRAMUNIFORM2FPROC ;
typedef scalar_t__ PFNGLPROGRAMUNIFORM2DVPROC ;
typedef scalar_t__ PFNGLPROGRAMUNIFORM2DPROC ;
typedef scalar_t__ PFNGLPROGRAMUNIFORM1UIVPROC ;
typedef scalar_t__ PFNGLPROGRAMUNIFORM1UIPROC ;
typedef scalar_t__ PFNGLPROGRAMUNIFORM1IVPROC ;
typedef scalar_t__ PFNGLPROGRAMUNIFORM1IPROC ;
typedef scalar_t__ PFNGLPROGRAMUNIFORM1FVPROC ;
typedef scalar_t__ PFNGLPROGRAMUNIFORM1FPROC ;
typedef scalar_t__ PFNGLPROGRAMUNIFORM1DVPROC ;
typedef scalar_t__ PFNGLPROGRAMUNIFORM1DPROC ;
typedef scalar_t__ PFNGLISPROGRAMPIPELINEPROC ;
typedef scalar_t__ PFNGLGETPROGRAMPIPELINEIVPROC ;
typedef scalar_t__ PFNGLGETPROGRAMPIPELINEINFOLOGPROC ;
typedef scalar_t__ PFNGLGENPROGRAMPIPELINESPROC ;
typedef scalar_t__ PFNGLDELETEPROGRAMPIPELINESPROC ;
typedef scalar_t__ PFNGLCREATESHADERPROGRAMVPROC ;
typedef scalar_t__ PFNGLBINDPROGRAMPIPELINEPROC ;
typedef scalar_t__ PFNGLACTIVESHADERPROGRAMPROC ;


 scalar_t__ FUNC_0 (char*) ;
 scalar_t__ VAR_0 ;
 scalar_t__ VAR_1 ;
 scalar_t__ VAR_2 ;
 scalar_t__ VAR_3 ;
 scalar_t__ VAR_4 ;
 scalar_t__ VAR_5 ;
 scalar_t__ VAR_6 ;
 scalar_t__ VAR_7 ;
 scalar_t__ VAR_8 ;
 scalar_t__ VAR_9 ;
 scalar_t__ VAR_10 ;
 scalar_t__ VAR_11 ;
 scalar_t__ VAR_12 ;
 scalar_t__ VAR_13 ;
 scalar_t__ VAR_14 ;
 scalar_t__ VAR_15 ;
 scalar_t__ VAR_16 ;
 scalar_t__ VAR_17 ;
 scalar_t__ VAR_18 ;
 scalar_t__ VAR_19 ;
 scalar_t__ VAR_20 ;
 scalar_t__ VAR_21 ;
 scalar_t__ VAR_22 ;
 scalar_t__ VAR_23 ;
 scalar_t__ VAR_24 ;
 scalar_t__ VAR_25 ;
 scalar_t__ VAR_26 ;
 scalar_t__ VAR_27 ;
 scalar_t__ VAR_28 ;
 scalar_t__ VAR_29 ;
 scalar_t__ VAR_30 ;
 scalar_t__ VAR_31 ;
 scalar_t__ VAR_32 ;
 scalar_t__ VAR_33 ;
 scalar_t__ VAR_34 ;
 scalar_t__ VAR_35 ;
 scalar_t__ VAR_36 ;
 scalar_t__ VAR_37 ;
 scalar_t__ VAR_38 ;
 scalar_t__ VAR_39 ;
 scalar_t__ VAR_40 ;
 scalar_t__ VAR_41 ;
 scalar_t__ VAR_42 ;
 scalar_t__ VAR_43 ;
 scalar_t__ VAR_44 ;
 scalar_t__ VAR_45 ;
 scalar_t__ VAR_46 ;
 scalar_t__ VAR_47 ;
 scalar_t__ VAR_48 ;
 scalar_t__ VAR_49 ;
 scalar_t__ VAR_50 ;
 scalar_t__ VAR_51 ;
 scalar_t__ VAR_52 ;
 scalar_t__ VAR_53 ;
 scalar_t__ VAR_54 ;
 scalar_t__ VAR_55 ;
 scalar_t__ VAR_56 ;
 scalar_t__ VAR_57 ;
 scalar_t__ VAR_58 ;
 scalar_t__ VAR_59 ;

__attribute__((used)) static int FUNC_1()
{
 int VAR_60 = 0;
 VAR_0 = (PFNGLACTIVESHADERPROGRAMPROC)FUNC_0("glActiveShaderProgram");
 if(!VAR_0) ++VAR_60;
 VAR_1 = (PFNGLBINDPROGRAMPIPELINEPROC)FUNC_0("glBindProgramPipeline");
 if(!VAR_1) ++VAR_60;
 VAR_2 = (PFNGLCREATESHADERPROGRAMVPROC)FUNC_0("glCreateShaderProgramv");
 if(!VAR_2) ++VAR_60;
 VAR_3 = (PFNGLDELETEPROGRAMPIPELINESPROC)FUNC_0("glDeleteProgramPipelines");
 if(!VAR_3) ++VAR_60;
 VAR_4 = (PFNGLGENPROGRAMPIPELINESPROC)FUNC_0("glGenProgramPipelines");
 if(!VAR_4) ++VAR_60;
 VAR_5 = (PFNGLGETPROGRAMPIPELINEINFOLOGPROC)FUNC_0("glGetProgramPipelineInfoLog");
 if(!VAR_5) ++VAR_60;
 VAR_6 = (PFNGLGETPROGRAMPIPELINEIVPROC)FUNC_0("glGetProgramPipelineiv");
 if(!VAR_6) ++VAR_60;
 VAR_7 = (PFNGLISPROGRAMPIPELINEPROC)FUNC_0("glIsProgramPipeline");
 if(!VAR_7) ++VAR_60;
 VAR_8 = (PFNGLPROGRAMUNIFORM1DPROC)FUNC_0("glProgramUniform1d");
 if(!VAR_8) ++VAR_60;
 VAR_9 = (PFNGLPROGRAMUNIFORM1DVPROC)FUNC_0("glProgramUniform1dv");
 if(!VAR_9) ++VAR_60;
 VAR_10 = (PFNGLPROGRAMUNIFORM1FPROC)FUNC_0("glProgramUniform1f");
 if(!VAR_10) ++VAR_60;
 VAR_11 = (PFNGLPROGRAMUNIFORM1FVPROC)FUNC_0("glProgramUniform1fv");
 if(!VAR_11) ++VAR_60;
 VAR_12 = (PFNGLPROGRAMUNIFORM1IPROC)FUNC_0("glProgramUniform1i");
 if(!VAR_12) ++VAR_60;
 VAR_13 = (PFNGLPROGRAMUNIFORM1IVPROC)FUNC_0("glProgramUniform1iv");
 if(!VAR_13) ++VAR_60;
 VAR_14 = (PFNGLPROGRAMUNIFORM1UIPROC)FUNC_0("glProgramUniform1ui");
 if(!VAR_14) ++VAR_60;
 VAR_15 = (PFNGLPROGRAMUNIFORM1UIVPROC)FUNC_0("glProgramUniform1uiv");
 if(!VAR_15) ++VAR_60;
 VAR_16 = (PFNGLPROGRAMUNIFORM2DPROC)FUNC_0("glProgramUniform2d");
 if(!VAR_16) ++VAR_60;
 VAR_17 = (PFNGLPROGRAMUNIFORM2DVPROC)FUNC_0("glProgramUniform2dv");
 if(!VAR_17) ++VAR_60;
 VAR_18 = (PFNGLPROGRAMUNIFORM2FPROC)FUNC_0("glProgramUniform2f");
 if(!VAR_18) ++VAR_60;
 VAR_19 = (PFNGLPROGRAMUNIFORM2FVPROC)FUNC_0("glProgramUniform2fv");
 if(!VAR_19) ++VAR_60;
 VAR_20 = (PFNGLPROGRAMUNIFORM2IPROC)FUNC_0("glProgramUniform2i");
 if(!VAR_20) ++VAR_60;
 VAR_21 = (PFNGLPROGRAMUNIFORM2IVPROC)FUNC_0("glProgramUniform2iv");
 if(!VAR_21) ++VAR_60;
 VAR_22 = (PFNGLPROGRAMUNIFORM2UIPROC)FUNC_0("glProgramUniform2ui");
 if(!VAR_22) ++VAR_60;
 VAR_23 = (PFNGLPROGRAMUNIFORM2UIVPROC)FUNC_0("glProgramUniform2uiv");
 if(!VAR_23) ++VAR_60;
 VAR_24 = (PFNGLPROGRAMUNIFORM3DPROC)FUNC_0("glProgramUniform3d");
 if(!VAR_24) ++VAR_60;
 VAR_25 = (PFNGLPROGRAMUNIFORM3DVPROC)FUNC_0("glProgramUniform3dv");
 if(!VAR_25) ++VAR_60;
 VAR_26 = (PFNGLPROGRAMUNIFORM3FPROC)FUNC_0("glProgramUniform3f");
 if(!VAR_26) ++VAR_60;
 VAR_27 = (PFNGLPROGRAMUNIFORM3FVPROC)FUNC_0("glProgramUniform3fv");
 if(!VAR_27) ++VAR_60;
 VAR_28 = (PFNGLPROGRAMUNIFORM3IPROC)FUNC_0("glProgramUniform3i");
 if(!VAR_28) ++VAR_60;
 VAR_29 = (PFNGLPROGRAMUNIFORM3IVPROC)FUNC_0("glProgramUniform3iv");
 if(!VAR_29) ++VAR_60;
 VAR_30 = (PFNGLPROGRAMUNIFORM3UIPROC)FUNC_0("glProgramUniform3ui");
 if(!VAR_30) ++VAR_60;
 VAR_31 = (PFNGLPROGRAMUNIFORM3UIVPROC)FUNC_0("glProgramUniform3uiv");
 if(!VAR_31) ++VAR_60;
 VAR_32 = (PFNGLPROGRAMUNIFORM4DPROC)FUNC_0("glProgramUniform4d");
 if(!VAR_32) ++VAR_60;
 VAR_33 = (PFNGLPROGRAMUNIFORM4DVPROC)FUNC_0("glProgramUniform4dv");
 if(!VAR_33) ++VAR_60;
 VAR_34 = (PFNGLPROGRAMUNIFORM4FPROC)FUNC_0("glProgramUniform4f");
 if(!VAR_34) ++VAR_60;
 VAR_35 = (PFNGLPROGRAMUNIFORM4FVPROC)FUNC_0("glProgramUniform4fv");
 if(!VAR_35) ++VAR_60;
 VAR_36 = (PFNGLPROGRAMUNIFORM4IPROC)FUNC_0("glProgramUniform4i");
 if(!VAR_36) ++VAR_60;
 VAR_37 = (PFNGLPROGRAMUNIFORM4IVPROC)FUNC_0("glProgramUniform4iv");
 if(!VAR_37) ++VAR_60;
 VAR_38 = (PFNGLPROGRAMUNIFORM4UIPROC)FUNC_0("glProgramUniform4ui");
 if(!VAR_38) ++VAR_60;
 VAR_39 = (PFNGLPROGRAMUNIFORM4UIVPROC)FUNC_0("glProgramUniform4uiv");
 if(!VAR_39) ++VAR_60;
 VAR_40 = (PFNGLPROGRAMUNIFORMMATRIX2DVPROC)FUNC_0("glProgramUniformMatrix2dv");
 if(!VAR_40) ++VAR_60;
 VAR_41 = (PFNGLPROGRAMUNIFORMMATRIX2FVPROC)FUNC_0("glProgramUniformMatrix2fv");
 if(!VAR_41) ++VAR_60;
 VAR_42 = (PFNGLPROGRAMUNIFORMMATRIX2X3DVPROC)FUNC_0("glProgramUniformMatrix2x3dv");
 if(!VAR_42) ++VAR_60;
 VAR_43 = (PFNGLPROGRAMUNIFORMMATRIX2X3FVPROC)FUNC_0("glProgramUniformMatrix2x3fv");
 if(!VAR_43) ++VAR_60;
 VAR_44 = (PFNGLPROGRAMUNIFORMMATRIX2X4DVPROC)FUNC_0("glProgramUniformMatrix2x4dv");
 if(!VAR_44) ++VAR_60;
 VAR_45 = (PFNGLPROGRAMUNIFORMMATRIX2X4FVPROC)FUNC_0("glProgramUniformMatrix2x4fv");
 if(!VAR_45) ++VAR_60;
 VAR_46 = (PFNGLPROGRAMUNIFORMMATRIX3DVPROC)FUNC_0("glProgramUniformMatrix3dv");
 if(!VAR_46) ++VAR_60;
 VAR_47 = (PFNGLPROGRAMUNIFORMMATRIX3FVPROC)FUNC_0("glProgramUniformMatrix3fv");
 if(!VAR_47) ++VAR_60;
 VAR_48 = (PFNGLPROGRAMUNIFORMMATRIX3X2DVPROC)FUNC_0("glProgramUniformMatrix3x2dv");
 if(!VAR_48) ++VAR_60;
 VAR_49 = (PFNGLPROGRAMUNIFORMMATRIX3X2FVPROC)FUNC_0("glProgramUniformMatrix3x2fv");
 if(!VAR_49) ++VAR_60;
 VAR_50 = (PFNGLPROGRAMUNIFORMMATRIX3X4DVPROC)FUNC_0("glProgramUniformMatrix3x4dv");
 if(!VAR_50) ++VAR_60;
 VAR_51 = (PFNGLPROGRAMUNIFORMMATRIX3X4FVPROC)FUNC_0("glProgramUniformMatrix3x4fv");
 if(!VAR_51) ++VAR_60;
 VAR_52 = (PFNGLPROGRAMUNIFORMMATRIX4DVPROC)FUNC_0("glProgramUniformMatrix4dv");
 if(!VAR_52) ++VAR_60;
 VAR_53 = (PFNGLPROGRAMUNIFORMMATRIX4FVPROC)FUNC_0("glProgramUniformMatrix4fv");
 if(!VAR_53) ++VAR_60;
 VAR_54 = (PFNGLPROGRAMUNIFORMMATRIX4X2DVPROC)FUNC_0("glProgramUniformMatrix4x2dv");
 if(!VAR_54) ++VAR_60;
 VAR_55 = (PFNGLPROGRAMUNIFORMMATRIX4X2FVPROC)FUNC_0("glProgramUniformMatrix4x2fv");
 if(!VAR_55) ++VAR_60;
 VAR_56 = (PFNGLPROGRAMUNIFORMMATRIX4X3DVPROC)FUNC_0("glProgramUniformMatrix4x3dv");
 if(!VAR_56) ++VAR_60;
 VAR_57 = (PFNGLPROGRAMUNIFORMMATRIX4X3FVPROC)FUNC_0("glProgramUniformMatrix4x3fv");
 if(!VAR_57) ++VAR_60;
 VAR_58 = (PFNGLUSEPROGRAMSTAGESPROC)FUNC_0("glUseProgramStages");
 if(!VAR_58) ++VAR_60;
 VAR_59 = (PFNGLVALIDATEPROGRAMPIPELINEPROC)FUNC_0("glValidateProgramPipeline");
 if(!VAR_59) ++VAR_60;
 return VAR_60;
}
