
typedef unsigned long size_t;
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;

typedef int bool;




typedef struct TYPE_2__ TYPE_1__ ;


typedef int u16 ;
struct snd_bt87x {int pci_parity_errors; int interrupt_mask; TYPE_1__* card; int pci; } ;
struct TYPE_2__ {int dev; } ;


 unsigned int VAR_0 ;
 int VAR_1 ;
 int VAR_2 ;
 int VAR_3 ;
 int VAR_4 ;
 int VAR_5 ;
 int VAR_6 ;
 int VAR_7 ;
 int VAR_8 ;
 int VAR_9 ;
 int VAR_10 ;
 int FUNC_0 (int ,char*,...) ;
 int FUNC_1 (int ,int ,int*) ;
 int FUNC_2 (int ,int ,int) ;
 int FUNC_3 (struct snd_bt87x*,int ,int) ;

__attribute__((used)) static void FUNC_4(struct snd_bt87x *VAR_11, unsigned int VAR_12)
{
 u16 VAR_13;

 FUNC_1(VAR_11->pci, VAR_3, &VAR_13);
 VAR_13 &= VAR_5 | VAR_9 |
  VAR_7 | VAR_6 |
  VAR_8 | VAR_4;
 FUNC_2(VAR_11->pci, VAR_3, VAR_13);
 if (VAR_13 != VAR_4)
  FUNC_0(VAR_11->card->dev,
   "Aieee - PCI error! status %#08x, PCI status %#04x\n",
      VAR_12 & VAR_0, VAR_13);
 else {
  FUNC_0(VAR_11->card->dev,
   "Aieee - PCI parity error detected!\n");

  VAR_11->pci_parity_errors++;
  if (VAR_11->pci_parity_errors > 20) {
   FUNC_0(VAR_11->card->dev,
    "Too many PCI parity errors observed.\n");
   FUNC_0(VAR_11->card->dev,
    "Some device on this bus is generating bad parity.\n");
   FUNC_0(VAR_11->card->dev,
    "This is an error *observed by*, not *generated by*, this card.\n");
   FUNC_0(VAR_11->card->dev,
    "PCI parity error checking has been disabled.\n");
   VAR_11->interrupt_mask &= ~(VAR_1 | VAR_2);
   FUNC_3(VAR_11, VAR_10, VAR_11->interrupt_mask);
  }
 }
}
