
typedef unsigned long size_t;
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;

typedef int bool;
 scalar_t__ FUNC_0 (scalar_t__,char*) ;
 scalar_t__ FUNC_1 (char*) ;
 scalar_t__ VAR_0 ;
 scalar_t__ VAR_1 ;
 int FUNC_2 (int,char*) ;
 void* VAR_2 ;
 void* VAR_3 ;
 void* VAR_4 ;
 void* VAR_5 ;
 void* VAR_6 ;
 void* VAR_7 ;
 void* VAR_8 ;
 void* VAR_9 ;
 void* VAR_10 ;
 void* VAR_11 ;
 void* VAR_12 ;
 void* VAR_13 ;
 void* VAR_14 ;
 void* VAR_15 ;
 void* VAR_16 ;
 void* VAR_17 ;
 void* VAR_18 ;
 void* VAR_19 ;
 void* VAR_20 ;
 void* VAR_21 ;
 void* VAR_22 ;
 void* VAR_23 ;
 void* VAR_24 ;
 void* VAR_25 ;
 void* VAR_26 ;
 void* VAR_27 ;
 void* VAR_28 ;
 void* VAR_29 ;
 void* VAR_30 ;
 void* VAR_31 ;
 void* VAR_32 ;
 void* VAR_33 ;
 void* VAR_34 ;
 void* VAR_35 ;
 void* VAR_36 ;
 void* VAR_37 ;
 void* VAR_38 ;
 void* VAR_39 ;
 void* VAR_40 ;
 void* VAR_41 ;
 void* VAR_42 ;
 void* VAR_43 ;
 void* VAR_44 ;
 void* VAR_45 ;
 void* VAR_46 ;
 void* VAR_47 ;
 void* VAR_48 ;
 void* VAR_49 ;
 void* VAR_50 ;
 void* VAR_51 ;
 void* VAR_52 ;
 int VAR_53 ;
 scalar_t__ VAR_54 ;
 int VAR_55 ;
 int FUNC_3 (char*,int ) ;
 int FUNC_4 (int ) ;

__attribute__((used)) static void FUNC_5(void)
{
    VAR_1 = FUNC_1("ntdll.dll");
    FUNC_2(VAR_1 != 0, "LoadLibrary failed\n");
    if (VAR_1) {
 VAR_15 = (void *)FUNC_0(VAR_1, "RtlCompareMemory");
 VAR_16 = (void *)FUNC_0(VAR_1, "RtlCompareMemoryUlong");
        VAR_21 = (void *)FUNC_0(VAR_1, "RtlDeleteTimer");
 VAR_45 = (void *)FUNC_0(VAR_1, "RtlMoveMemory");
 VAR_23 = (void *)FUNC_0(VAR_1, "RtlFillMemory");
 VAR_24 = (void *)FUNC_0(VAR_1, "RtlFillMemoryUlong");
 VAR_52 = (void *)FUNC_0(VAR_1, "RtlZeroMemory");
 VAR_50 = (void *)FUNC_0(VAR_1, "RtlUlonglongByteSwap");
 VAR_51 = (void *)FUNC_0(VAR_1, "RtlUniform");
 VAR_48 = (void *)FUNC_0(VAR_1, "RtlRandom");
 VAR_13 = (void *)FUNC_0(VAR_1, "RtlAreAllAccessesGranted");
 VAR_14 = (void *)FUNC_0(VAR_1, "RtlAreAnyAccessesGranted");
 VAR_18 = (void *)FUNC_0(VAR_1, "RtlComputeCrc32");
 VAR_30 = (void *)FUNC_0(VAR_1, "RtlInitializeHandleTable");
 VAR_43 = (void *)FUNC_0(VAR_1, "RtlIsValidIndexHandle");
 VAR_22 = (void *)FUNC_0(VAR_1, "RtlDestroyHandleTable");
 VAR_12 = (void *)FUNC_0(VAR_1, "RtlAllocateHandle");
 VAR_25 = (void *)FUNC_0(VAR_1, "RtlFreeHandle");
        VAR_11 = (void *)FUNC_0(VAR_1, "RtlAllocateAndInitializeSid");
        VAR_26 = (void *)FUNC_0(VAR_1, "RtlFreeSid");
        VAR_28 = (void *)FUNC_0(VAR_1, "RtlGetThreadErrorMode");
        VAR_49 = (void *)FUNC_0(VAR_1, "RtlSetThreadErrorMode");
        VAR_6 = (void *)FUNC_0(VAR_1, "LdrProcessRelocationBlock");
        VAR_31 = (void *)FUNC_0(VAR_1, "RtlIpv4AddressToStringA");
        VAR_32 = (void *)FUNC_0(VAR_1, "RtlIpv4AddressToStringExA");
        VAR_33 = (void *)FUNC_0(VAR_1, "RtlIpv4StringToAddressA");
        VAR_34 = (void *)FUNC_0(VAR_1, "RtlIpv4StringToAddressExA");
        VAR_35 = (void *)FUNC_0(VAR_1, "RtlIpv6AddressToStringA");
        VAR_36 = (void *)FUNC_0(VAR_1, "RtlIpv6AddressToStringExA");
        VAR_37 = (void *)FUNC_0(VAR_1, "RtlIpv6StringToAddressA");
        VAR_40 = (void *)FUNC_0(VAR_1, "RtlIpv6StringToAddressW");
        VAR_38 = (void *)FUNC_0(VAR_1, "RtlIpv6StringToAddressExA");
        VAR_39 = (void *)FUNC_0(VAR_1, "RtlIpv6StringToAddressExW");
        VAR_3 = (void *)FUNC_0(VAR_1, "LdrAddRefDll");
        VAR_5 = (void *)FUNC_0(VAR_1, "LdrLockLoaderLock");
        VAR_8 = (void *)FUNC_0(VAR_1, "LdrUnlockLoaderLock");
        VAR_46 = (void *)FUNC_0(VAR_1, "RtlMultiByteToUnicodeN");
        VAR_27 = (void *)FUNC_0(VAR_1, "RtlGetCompressionWorkSpaceSize");
        VAR_19 = (void *)FUNC_0(VAR_1, "RtlDecompressBuffer");
        VAR_20 = (void *)FUNC_0(VAR_1, "RtlDecompressFragment");
        VAR_17 = (void *)FUNC_0(VAR_1, "RtlCompressBuffer");
        VAR_41 = (void *)FUNC_0(VAR_1, "RtlIsCriticalSectionLocked");
        VAR_42 = (void *)FUNC_0(VAR_1, "RtlIsCriticalSectionLockedByThread");
        VAR_29 = (void *)FUNC_0(VAR_1, "RtlInitializeCriticalSectionEx");
        VAR_4 = (void *)FUNC_0(VAR_1, "LdrEnumerateLoadedModules");
        VAR_47 = (void *)FUNC_0(VAR_1, "RtlQueryPackageIdentity");
        VAR_44 = (void *)FUNC_0(VAR_1, "RtlMakeSelfRelativeSD");
        VAR_10 = (void *)FUNC_0(VAR_1, "RtlAbsoluteToSelfRelativeSD");
        VAR_7 = (void *)FUNC_0(VAR_1, "LdrRegisterDllNotification");
        VAR_9 = (void *)FUNC_0(VAR_1, "LdrUnregisterDllNotification");
    }
    VAR_0 = FUNC_1("kernel32.dll");
    FUNC_2(VAR_0 != 0, "LoadLibrary failed\n");
    if (VAR_0) {
        VAR_2 = (void *)FUNC_0(VAR_0, "IsWow64Process");
    }
    FUNC_3((char*)VAR_54, VAR_55);
    FUNC_2(FUNC_4(VAR_53) == 15, "Source must be 16 bytes long!\n");
}
