
typedef unsigned long size_t;
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;

typedef int bool;






typedef int u_int ;
struct ahc_softc {scalar_t__ pci_target_perr_count; int seqctl; int dev_softc; } ;


 scalar_t__ VAR_0 ;
 int VAR_1 ;
 int VAR_2 ;
 int VAR_3 ;
 int VAR_4 ;
 int VAR_5 ;
 int VAR_6 ;
 int VAR_7 ;
 scalar_t__ VAR_8 ;
 int VAR_9 ;
 int VAR_10 ;
 int VAR_11 ;
 int VAR_12 ;
 int VAR_13 ;
 int VAR_14 ;
 int VAR_15 ;
 int FUNC_0 (struct ahc_softc*,int ) ;
 char* FUNC_1 (struct ahc_softc*) ;
 int FUNC_2 (struct ahc_softc*,int ,int ) ;
 int FUNC_3 (int ,scalar_t__,int) ;
 int FUNC_4 (int ,scalar_t__,int,int) ;
 int FUNC_5 (struct ahc_softc*) ;
 int FUNC_6 (char*,char*,...) ;

__attribute__((used)) static void
FUNC_7(struct ahc_softc *VAR_16)
{
 u_int VAR_17;
 u_int VAR_18;

 VAR_17 = FUNC_0(VAR_16, VAR_5);
 if ((VAR_17 & VAR_7) == 0)
  return;

 VAR_18 = FUNC_3(VAR_16->dev_softc,
          VAR_8 + 1, 1);

 FUNC_6("%s: PCI error Interrupt at seqaddr = 0x%x\n",
       FUNC_1(VAR_16),
       FUNC_0(VAR_16, VAR_11) | (FUNC_0(VAR_16, VAR_12) << 8));

 if (VAR_18 & VAR_3) {
  VAR_16->pci_target_perr_count++;
  FUNC_6("%s: Data Parity Error Detected during address "
         "or write data phase\n", FUNC_1(VAR_16));
 }
 if (VAR_18 & VAR_14) {
  FUNC_6("%s: Signal System Error Detected\n", FUNC_1(VAR_16));
 }
 if (VAR_18 & VAR_9) {
  FUNC_6("%s: Received a Master Abort\n", FUNC_1(VAR_16));
 }
 if (VAR_18 & VAR_10) {
  FUNC_6("%s: Received a Target Abort\n", FUNC_1(VAR_16));
 }
 if (VAR_18 & VAR_15) {
  FUNC_6("%s: Signaled a Target Abort\n", FUNC_1(VAR_16));
 }
 if (VAR_18 & VAR_4) {
  FUNC_6("%s: Data Parity Error has been reported via PERR#\n",
         FUNC_1(VAR_16));
 }


 FUNC_4(VAR_16->dev_softc, VAR_8 + 1,
        VAR_18, 1);

 if ((VAR_18 & (VAR_3|VAR_14|VAR_9|VAR_10|VAR_15|VAR_4)) == 0) {
  FUNC_6("%s: Latched PCIERR interrupt with "
         "no status bits set\n", FUNC_1(VAR_16));
 } else {
  FUNC_2(VAR_16, VAR_1, VAR_2);
 }

 if (VAR_16->pci_target_perr_count > VAR_0) {
  FUNC_6(
"%s: WARNING WARNING WARNING WARNING\n"
"%s: Too many PCI parity errors observed as a target.\n"
"%s: Some device on this bus is generating bad parity.\n"
"%s: This is an error *observed by*, not *generated by*, this controller.\n"
"%s: PCI parity error checking has been disabled.\n"
"%s: WARNING WARNING WARNING WARNING\n",
         FUNC_1(VAR_16), FUNC_1(VAR_16), FUNC_1(VAR_16),
         FUNC_1(VAR_16), FUNC_1(VAR_16), FUNC_1(VAR_16));
  VAR_16->seqctl |= VAR_6;
  FUNC_2(VAR_16, VAR_13, VAR_16->seqctl);
 }
 FUNC_5(VAR_16);
}
