
typedef unsigned long size_t;
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;

typedef int bool;
 int FUNC_0 () ;
 int FUNC_1 (int,char*) ;
 int FUNC_2 (int,char*) ;
 int FUNC_3 (int) ;
 int FUNC_4 (int,char*) ;

void
FUNC_5()
{
    int VAR_0 = FUNC_0();
    int VAR_1 = FUNC_3(VAR_0);
    FUNC_4(VAR_1, "use tubea\r\n");
    FUNC_1(VAR_1, "USING tubea\r\n");
    FUNC_4(VAR_1, "put 0 0 0 1\r\n");
    FUNC_4(VAR_1, "x\r\n");
    FUNC_1(VAR_1, "INSERTED 1\r\n");
    FUNC_4(VAR_1, "delete 1\r\n");
    FUNC_1(VAR_1, "DELETED\r\n");

    FUNC_4(VAR_1, "stats-tube tubea\r\n");
    FUNC_2(VAR_1, "OK ");
    FUNC_2(VAR_1, "\nname: tubea\n");
    FUNC_4(VAR_1, "stats-tube tubea\r\n");
    FUNC_2(VAR_1, "OK ");
    FUNC_2(VAR_1, "\ncurrent-jobs-urgent: 0\n");
    FUNC_4(VAR_1, "stats-tube tubea\r\n");
    FUNC_2(VAR_1, "OK ");
    FUNC_2(VAR_1, "\ncurrent-jobs-ready: 0\n");
    FUNC_4(VAR_1, "stats-tube tubea\r\n");
    FUNC_2(VAR_1, "OK ");
    FUNC_2(VAR_1, "\ncurrent-jobs-reserved: 0\n");
    FUNC_4(VAR_1, "stats-tube tubea\r\n");
    FUNC_2(VAR_1, "OK ");
    FUNC_2(VAR_1, "\ncurrent-jobs-delayed: 0\n");
    FUNC_4(VAR_1, "stats-tube tubea\r\n");
    FUNC_2(VAR_1, "OK ");
    FUNC_2(VAR_1, "\ncurrent-jobs-buried: 0\n");
    FUNC_4(VAR_1, "stats-tube tubea\r\n");
    FUNC_2(VAR_1, "OK ");
    FUNC_2(VAR_1, "\ntotal-jobs: 1\n");
    FUNC_4(VAR_1, "stats-tube tubea\r\n");
    FUNC_2(VAR_1, "OK ");
    FUNC_2(VAR_1, "\ncurrent-using: 1\n");
    FUNC_4(VAR_1, "stats-tube tubea\r\n");
    FUNC_2(VAR_1, "OK ");
    FUNC_2(VAR_1, "\ncurrent-watching: 0\n");
    FUNC_4(VAR_1, "stats-tube tubea\r\n");
    FUNC_2(VAR_1, "OK ");
    FUNC_2(VAR_1, "\ncurrent-waiting: 0\n");
    FUNC_4(VAR_1, "stats-tube tubea\r\n");
    FUNC_2(VAR_1, "OK ");
    FUNC_2(VAR_1, "\ncmd-delete: 1\n");
    FUNC_4(VAR_1, "stats-tube tubea\r\n");
    FUNC_2(VAR_1, "OK ");
    FUNC_2(VAR_1, "\ncmd-pause-tube: 0\n");
    FUNC_4(VAR_1, "stats-tube tubea\r\n");
    FUNC_2(VAR_1, "OK ");
    FUNC_2(VAR_1, "\npause: 0\n");
    FUNC_4(VAR_1, "stats-tube tubea\r\n");
    FUNC_2(VAR_1, "OK ");
    FUNC_2(VAR_1, "\npause-time-left: 0\n");

    FUNC_4(VAR_1, "stats-tube default\r\n");
    FUNC_2(VAR_1, "OK ");
    FUNC_2(VAR_1, "\nname: default\n");
    FUNC_4(VAR_1, "stats-tube default\r\n");
    FUNC_2(VAR_1, "OK ");
    FUNC_2(VAR_1, "\ncurrent-jobs-urgent: 0\n");
    FUNC_4(VAR_1, "stats-tube default\r\n");
    FUNC_2(VAR_1, "OK ");
    FUNC_2(VAR_1, "\ncurrent-jobs-ready: 0\n");
    FUNC_4(VAR_1, "stats-tube default\r\n");
    FUNC_2(VAR_1, "OK ");
    FUNC_2(VAR_1, "\ncurrent-jobs-reserved: 0\n");
    FUNC_4(VAR_1, "stats-tube default\r\n");
    FUNC_2(VAR_1, "OK ");
    FUNC_2(VAR_1, "\ncurrent-jobs-delayed: 0\n");
    FUNC_4(VAR_1, "stats-tube default\r\n");
    FUNC_2(VAR_1, "OK ");
    FUNC_2(VAR_1, "\ncurrent-jobs-buried: 0\n");
    FUNC_4(VAR_1, "stats-tube default\r\n");
    FUNC_2(VAR_1, "OK ");
    FUNC_2(VAR_1, "\ntotal-jobs: 0\n");
    FUNC_4(VAR_1, "stats-tube default\r\n");
    FUNC_2(VAR_1, "OK ");
    FUNC_2(VAR_1, "\ncurrent-using: 0\n");
    FUNC_4(VAR_1, "stats-tube default\r\n");
    FUNC_2(VAR_1, "OK ");
    FUNC_2(VAR_1, "\ncurrent-watching: 1\n");
    FUNC_4(VAR_1, "stats-tube default\r\n");
    FUNC_2(VAR_1, "OK ");
    FUNC_2(VAR_1, "\ncurrent-waiting: 0\n");
    FUNC_4(VAR_1, "stats-tube default\r\n");
    FUNC_2(VAR_1, "OK ");
    FUNC_2(VAR_1, "\ncmd-delete: 0\n");
    FUNC_4(VAR_1, "stats-tube default\r\n");
    FUNC_2(VAR_1, "OK ");
    FUNC_2(VAR_1, "\ncmd-pause-tube: 0\n");
    FUNC_4(VAR_1, "stats-tube default\r\n");
    FUNC_2(VAR_1, "OK ");
    FUNC_2(VAR_1, "\npause: 0\n");
    FUNC_4(VAR_1, "stats-tube default\r\n");
    FUNC_2(VAR_1, "OK ");
    FUNC_2(VAR_1, "\npause-time-left: 0\n");
}
