
typedef unsigned long size_t;
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;

typedef int bool;
const char* FUNC_0(int VAR_0)
{
    switch (VAR_0)
    {
    case 128: return "NFS4_OK";
    case 161: return "NFS4ERR_PERM";
    case 176: return "NFS4ERR_NOENT";
    case 189: return "NFS4ERR_IO";
    case 166: return "NFS4ERR_NXIO";
    case 231: return "NFS4ERR_ACCESS";
    case 197: return "NFS4ERR_EXIST";
    case 129: return "NFS4ERR_XDEV";
    case 172: return "NFS4ERR_NOTDIR";
    case 188: return "NFS4ERR_ISDIR";
    case 190: return "NFS4ERR_INVAL";
    case 195: return "NFS4ERR_FBIG";
    case 173: return "NFS4ERR_NOSPC";
    case 147: return "NFS4ERR_ROFS";
    case 179: return "NFS4ERR_MLINK";
    case 177: return "NFS4ERR_NAMETOOLONG";
    case 171: return "NFS4ERR_NOTEMPTY";
    case 199: return "NFS4ERR_DQUOT";
    case 140: return "NFS4ERR_STALE";
    case 226: return "NFS4ERR_BADHANDLE";
    case 217: return "NFS4ERR_BAD_COOKIE";
    case 170: return "NFS4ERR_NOTSUPP";
    case 136: return "NFS4ERR_TOOSMALL";
    case 142: return "NFS4ERR_SERVERFAULT";
    case 219: return "NFS4ERR_BADTYPE";
    case 204: return "NFS4ERR_DELAY";
    case 146: return "NFS4ERR_SAME";
    case 201: return "NFS4ERR_DENIED";
    case 196: return "NFS4ERR_EXPIRED";
    case 184: return "NFS4ERR_LOCKED";
    case 192: return "NFS4ERR_GRACE";
    case 194: return "NFS4ERR_FHEXPIRED";
    case 141: return "NFS4ERR_SHARE_DENIED";
    case 132: return "NFS4ERR_WRONGSEC";
    case 210: return "NFS4ERR_CLID_INUSE";
    case 151: return "NFS4ERR_RESOURCE";
    case 178: return "NFS4ERR_MOVED";
    case 175: return "NFS4ERR_NOFILEHANDLE";
    case 180: return "NFS4ERR_MINOR_VERS_MISMATCH";
    case 139: return "NFS4ERR_STALE_CLIENTID";
    case 138: return "NFS4ERR_STALE_STATEID";
    case 165: return "NFS4ERR_OLD_STATEID";
    case 212: return "NFS4ERR_BAD_STATEID";
    case 214: return "NFS4ERR_BAD_SEQID";
    case 168: return "NFS4ERR_NOT_SAME";
    case 181: return "NFS4ERR_LOCK_RANGE";
    case 137: return "NFS4ERR_SYMLINK";
    case 150: return "NFS4ERR_RESTOREFH";
    case 185: return "NFS4ERR_LEASE_MOVED";
    case 229: return "NFS4ERR_ATTRNOTSUPP";
    case 167: return "NFS4ERR_NO_GRACE";
    case 157: return "NFS4ERR_RECLAIM_BAD";
    case 156: return "NFS4ERR_RECLAIM_CONFLICT";
    case 218: return "NFS4ERR_BADXDR";
    case 183: return "NFS4ERR_LOCKS_HELD";
    case 164: return "NFS4ERR_OPENMODE";
    case 222: return "NFS4ERR_BADOWNER";
    case 227: return "NFS4ERR_BADCHAR";
    case 223: return "NFS4ERR_BADNAME";
    case 215: return "NFS4ERR_BAD_RANGE";
    case 182: return "NFS4ERR_LOCK_NOTSUPP";
    case 163: return "NFS4ERR_OP_ILLEGAL";
    case 206: return "NFS4ERR_DEADLOCK";
    case 193: return "NFS4ERR_FILE_OPEN";
    case 230: return "NFS4ERR_ADMIN_REVOKED";
    case 211: return "NFS4ERR_CB_PATH_DOWN";
    case 225: return "NFS4ERR_BADIOMODE";
    case 224: return "NFS4ERR_BADLAYOUT";
    case 213: return "NFS4ERR_BAD_SESSION_DIGEST";
    case 221: return "NFS4ERR_BADSESSION";
    case 220: return "NFS4ERR_BADSLOT";
    case 208: return "NFS4ERR_COMPLETE_ALREADY";
    case 207: return "NFS4ERR_CONN_NOT_BOUND_TO_SESSION";
    case 203: return "NFS4ERR_DELEG_ALREADY_WANTED";
    case 228: return "NFS4ERR_BACK_CHAN_BUSY";
    case 187: return "NFS4ERR_LAYOUTTRYLATER";
    case 186: return "NFS4ERR_LAYOUTUNAVAILABLE";
    case 174: return "NFS4ERR_NOMATCHING_LAYOUT";
    case 158: return "NFS4ERR_RECALLCONFLICT";
    case 134: return "NFS4ERR_UNKNOWN_LAYOUTTYPE";
    case 143: return "NFS4ERR_SEQ_MISORDERED";
    case 145: return "NFS4ERR_SEQUENCE_POS";
    case 152: return "NFS4ERR_REQ_TOO_BIG";
    case 154: return "NFS4ERR_REP_TOO_BIG";
    case 153: return "NFS4ERR_REP_TOO_BIG_TO_CACHE";
    case 149: return "NFS4ERR_RETRY_UNCACHED_REP";
    case 133: return "NFS4ERR_UNSAFE_COMPOUND";
    case 135: return "NFS4ERR_TOO_MANY_OPS";
    case 162: return "NFS4ERR_OP_NOT_IN_SESSION";
    case 191: return "NFS4ERR_HASH_ALG_UNSUPP";
    case 209: return "NFS4ERR_CLIENTID_BUSY";
    case 160: return "NFS4ERR_PNFS_IO_HOLE";
    case 144: return "NFS4ERR_SEQ_FALSE_RETRY";
    case 216: return "NFS4ERR_BAD_HIGH_SLOT";
    case 205: return "NFS4ERR_DEADSESSION";
    case 198: return "NFS4ERR_ENCR_ALG_UNSUPP";
    case 159: return "NFS4ERR_PNFS_NO_LAYOUT";
    case 169: return "NFS4ERR_NOT_ONLY_OP";
    case 131: return "NFS4ERR_WRONG_CRED";
    case 130: return "NFS4ERR_WRONG_TYPE";
    case 200: return "NFS4ERR_DIRDELEG_UNAVAIL";
    case 155: return "NFS4ERR_REJECT_DELEG";
    case 148: return "NFS4ERR_RETURNCONFLICT";
    case 202: return "NFS4ERR_DELEG_REVOKED";
    default: return "invalid nfs error code";
    }
}
