
typedef unsigned long size_t;
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;

typedef int bool;






typedef char const* u32 ;
struct adapter {int dummy; } ;


 int FUNC_0 (char const* const*) ;






 int FUNC_1 (struct adapter*,char*,unsigned int) ;
 int FUNC_2 (struct adapter*,char*,...) ;
 unsigned int FUNC_3 (struct adapter*) ;
 int FUNC_4 (struct adapter*,char const* const) ;

void FUNC_5(struct adapter *VAR_0, int VAR_1)
{
 static const char * const VAR_2[] = {
  "IDMA_IDLE",
  "IDMA_PUSH_MORE_CPL_FIFO",
  "IDMA_PUSH_CPL_MSG_HEADER_TO_FIFO",
  "Not used",
  "IDMA_PHYSADDR_SEND_PCIEHDR",
  "IDMA_PHYSADDR_SEND_PAYLOAD_FIRST",
  "IDMA_PHYSADDR_SEND_PAYLOAD",
  "IDMA_SEND_FIFO_TO_IMSG",
  "IDMA_FL_REQ_DATA_FL_PREP",
  "IDMA_FL_REQ_DATA_FL",
  "IDMA_FL_DROP",
  "IDMA_FL_H_REQ_HEADER_FL",
  "IDMA_FL_H_SEND_PCIEHDR",
  "IDMA_FL_H_PUSH_CPL_FIFO",
  "IDMA_FL_H_SEND_CPL",
  "IDMA_FL_H_SEND_IP_HDR_FIRST",
  "IDMA_FL_H_SEND_IP_HDR",
  "IDMA_FL_H_REQ_NEXT_HEADER_FL",
  "IDMA_FL_H_SEND_NEXT_PCIEHDR",
  "IDMA_FL_H_SEND_IP_HDR_PADDING",
  "IDMA_FL_D_SEND_PCIEHDR",
  "IDMA_FL_D_SEND_CPL_AND_IP_HDR",
  "IDMA_FL_D_REQ_NEXT_DATA_FL",
  "IDMA_FL_SEND_PCIEHDR",
  "IDMA_FL_PUSH_CPL_FIFO",
  "IDMA_FL_SEND_CPL",
  "IDMA_FL_SEND_PAYLOAD_FIRST",
  "IDMA_FL_SEND_PAYLOAD",
  "IDMA_FL_REQ_NEXT_DATA_FL",
  "IDMA_FL_SEND_NEXT_PCIEHDR",
  "IDMA_FL_SEND_PADDING",
  "IDMA_FL_SEND_COMPLETION_TO_IMSG",
  "IDMA_FL_SEND_FIFO_TO_IMSG",
  "IDMA_FL_REQ_DATAFL_DONE",
  "IDMA_FL_REQ_HEADERFL_DONE",
 };
 static const char * const VAR_3[] = {
  "IDMA_IDLE",
  "IDMA_ALMOST_IDLE",
  "IDMA_PUSH_MORE_CPL_FIFO",
  "IDMA_PUSH_CPL_MSG_HEADER_TO_FIFO",
  "IDMA_SGEFLRFLUSH_SEND_PCIEHDR",
  "IDMA_PHYSADDR_SEND_PCIEHDR",
  "IDMA_PHYSADDR_SEND_PAYLOAD_FIRST",
  "IDMA_PHYSADDR_SEND_PAYLOAD",
  "IDMA_SEND_FIFO_TO_IMSG",
  "IDMA_FL_REQ_DATA_FL",
  "IDMA_FL_DROP",
  "IDMA_FL_DROP_SEND_INC",
  "IDMA_FL_H_REQ_HEADER_FL",
  "IDMA_FL_H_SEND_PCIEHDR",
  "IDMA_FL_H_PUSH_CPL_FIFO",
  "IDMA_FL_H_SEND_CPL",
  "IDMA_FL_H_SEND_IP_HDR_FIRST",
  "IDMA_FL_H_SEND_IP_HDR",
  "IDMA_FL_H_REQ_NEXT_HEADER_FL",
  "IDMA_FL_H_SEND_NEXT_PCIEHDR",
  "IDMA_FL_H_SEND_IP_HDR_PADDING",
  "IDMA_FL_D_SEND_PCIEHDR",
  "IDMA_FL_D_SEND_CPL_AND_IP_HDR",
  "IDMA_FL_D_REQ_NEXT_DATA_FL",
  "IDMA_FL_SEND_PCIEHDR",
  "IDMA_FL_PUSH_CPL_FIFO",
  "IDMA_FL_SEND_CPL",
  "IDMA_FL_SEND_PAYLOAD_FIRST",
  "IDMA_FL_SEND_PAYLOAD",
  "IDMA_FL_REQ_NEXT_DATA_FL",
  "IDMA_FL_SEND_NEXT_PCIEHDR",
  "IDMA_FL_SEND_PADDING",
  "IDMA_FL_SEND_COMPLETION_TO_IMSG",
 };
 static const char * const VAR_4[] = {
  "IDMA_IDLE",
  "IDMA_PUSH_MORE_CPL_FIFO",
  "IDMA_PUSH_CPL_MSG_HEADER_TO_FIFO",
  "IDMA_SGEFLRFLUSH_SEND_PCIEHDR",
  "IDMA_PHYSADDR_SEND_PCIEHDR",
  "IDMA_PHYSADDR_SEND_PAYLOAD_FIRST",
  "IDMA_PHYSADDR_SEND_PAYLOAD",
  "IDMA_FL_REQ_DATA_FL",
  "IDMA_FL_DROP",
  "IDMA_FL_DROP_SEND_INC",
  "IDMA_FL_H_REQ_HEADER_FL",
  "IDMA_FL_H_SEND_PCIEHDR",
  "IDMA_FL_H_PUSH_CPL_FIFO",
  "IDMA_FL_H_SEND_CPL",
  "IDMA_FL_H_SEND_IP_HDR_FIRST",
  "IDMA_FL_H_SEND_IP_HDR",
  "IDMA_FL_H_REQ_NEXT_HEADER_FL",
  "IDMA_FL_H_SEND_NEXT_PCIEHDR",
  "IDMA_FL_H_SEND_IP_HDR_PADDING",
  "IDMA_FL_D_SEND_PCIEHDR",
  "IDMA_FL_D_SEND_CPL_AND_IP_HDR",
  "IDMA_FL_D_REQ_NEXT_DATA_FL",
  "IDMA_FL_SEND_PCIEHDR",
  "IDMA_FL_PUSH_CPL_FIFO",
  "IDMA_FL_SEND_CPL",
  "IDMA_FL_SEND_PAYLOAD_FIRST",
  "IDMA_FL_SEND_PAYLOAD",
  "IDMA_FL_REQ_NEXT_DATA_FL",
  "IDMA_FL_SEND_NEXT_PCIEHDR",
  "IDMA_FL_SEND_PADDING",
  "IDMA_FL_SEND_COMPLETION_TO_IMSG",
 };
 static const u32 VAR_5[] = {
  132,
  131,
  133,
 };
 const char * const *VAR_6;
 int VAR_7;
 int VAR_8;
 unsigned int VAR_9 = FUNC_3(VAR_0);




 switch (VAR_9) {
 case 130:
  VAR_6 = (const char * const *)VAR_2;
  VAR_7 = FUNC_0(VAR_2);
  break;

 case 129:
  VAR_6 = (const char * const *)VAR_3;
  VAR_7 = FUNC_0(VAR_3);
  break;

 case 128:
  VAR_6 = (const char * const *)VAR_4;
  VAR_7 = FUNC_0(VAR_4);
  break;

 default:
  FUNC_1(VAR_0, "Unsupported chip version %d\n", VAR_9);
  return;
 }

 if (VAR_1 < VAR_7)
  FUNC_2(VAR_0, "idma state %s\n", VAR_6[VAR_1]);
 else
  FUNC_2(VAR_0, "idma state %d unknown\n", VAR_1);

 for (VAR_8 = 0; VAR_8 < FUNC_0(VAR_5); VAR_8++)
  FUNC_2(VAR_0, "SGE register %#x value %#x\n",
   VAR_5[VAR_8], FUNC_4(VAR_0, VAR_5[VAR_8]));
}
