
typedef unsigned long size_t;
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;

typedef int bool;
 int VAR_0 ;
 int VAR_1 ;
 int FUNC_0 (int) ;
 int FUNC_1 (int ,char*,...) ;
 int FUNC_2 (char,char*) ;
 int VAR_2 ;

__attribute__((used)) static void
FUNC_3(void)
{
 (void) FUNC_1(VAR_2,
     "Usage: lockstat [options] command [args]\n"
     "\nGeneral options:\n\n"
     "  -V              print the corresponding D program\n"
     "\nEvent selection options:\n\n"
     "  -C              watch contention events [on by default]\n"
     "  -E              watch error events [off by default]\n"
     "  -H              watch hold events [off by default]\n"
     "  -I              watch interrupt events [off by default]\n"
     "  -A              watch all lock events [equivalent to -CH]\n"
     "  -e event_list   only watch the specified events (shown below);\n"
     "                  <event_list> is a comma-separated list of\n"
     "                  events or ranges of events, e.g. 1,4-7,35\n"
     "  -i rate         interrupt rate for -I [default: %d Hz]\n"
     "\nData gathering options:\n\n"
     "  -b              basic statistics (lock, caller, event count)\n"
     "  -t              timing for all events [default]\n"
     "  -h              histograms for event times\n"
     "  -s depth        stack traces <depth> deep\n"
     "  -x opt[=val]    enable or modify DTrace options\n"
     "\nData filtering options:\n\n"
     "  -n nrecords     maximum number of data records [default: %d]\n"
     "  -l lock[,size]  only watch <lock>, which can be specified as a\n"
     "                  symbolic name or hex address; <size> defaults\n"
     "                  to the ELF symbol size if available, 1 if not\n"
     "  -f func[,size]  only watch events generated by <func>\n"
     "  -d duration     only watch events longer than <duration>\n"
     "  -T              trace (rather than sample) events\n"
     "\nData reporting options:\n\n"



     "  -k              coalesce PCs within functions\n"
     "  -g              show total events generated by function\n"
     "  -w              wherever: don't distinguish events by caller\n"
     "  -W              whichever: don't distinguish events by lock\n"
     "  -R              display rates rather than counts\n"
     "  -p              parsable output format (awk(1)-friendly)\n"
     "  -P              sort lock data by (count * avg_time) product\n"
     "  -D n            only display top <n> events of each type\n"
     "  -o filename     send output to <filename>\n",
     VAR_0, VAR_1);

 FUNC_2('C', "Contention");
 FUNC_2('H', "Hold-time");
 FUNC_2('I', "Interrupt");
 FUNC_2('E', "Error");
 (void) FUNC_1(VAR_2, "\n");

 FUNC_0(1);
}
