
typedef unsigned long size_t;
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;

typedef int bool;






typedef int timestamp ;
typedef int time_t ;


 int FUNC_0 (int *) ;
 int FUNC_1 (char*,char*) ;
 int FUNC_2 (char*,int,char*,int ) ;
 int FUNC_3 (int *) ;

__attribute__((used)) static void
FUNC_4(void)
{
 time_t VAR_0;
 char VAR_1[128];
 char VAR_2[] =
"/*\n"
" * ntp_keyword.h\n"
" * \n"
" * NOTE: edit this file with caution, it is generated by keyword-gen.c\n"
" *\t Generated %s UTC	  diff_ignore_line\n"
" *\n"
" */\n"
"#include \"ntp_scanner.h\"\n"
"#include \"ntp_parser.h\"\n"
"\n";

 FUNC_3(&VAR_0);
 if (!FUNC_2(VAR_1, sizeof(VAR_1),
        "%Y-%m-%d %H:%M:%S", FUNC_0(&VAR_0)))
  VAR_1[0] = '\0';

 FUNC_1(VAR_2, VAR_1);
}
