
typedef unsigned long size_t;
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;

typedef int bool;






typedef int u_int ;
struct ahc_softc {int flags; scalar_t__ pci_target_perr_count; int seqctl; int dev_softc; } ;


 int VAR_0 ;
 scalar_t__ VAR_1 ;
 int VAR_2 ;
 int VAR_3 ;
 int VAR_4 ;
 int VAR_5 ;
 int VAR_6 ;
 int VAR_7 ;
 int VAR_8 ;
 scalar_t__ VAR_9 ;
 int VAR_10 ;
 int VAR_11 ;
 int VAR_12 ;
 int VAR_13 ;
 int VAR_14 ;
 int VAR_15 ;
 int VAR_16 ;
 int FUNC_0 (struct ahc_softc*,int ) ;
 char* FUNC_1 (struct ahc_softc*) ;
 int FUNC_2 (struct ahc_softc*,int ,int ) ;
 int FUNC_3 (struct ahc_softc*) ;
 int FUNC_4 (int ,scalar_t__,int) ;
 int FUNC_5 (int ,scalar_t__,int,int) ;
 int FUNC_6 (char*,char*,...) ;

__attribute__((used)) static void
FUNC_7(struct ahc_softc *VAR_17)
{
 u_int VAR_18;
 u_int VAR_19;

 VAR_18 = FUNC_0(VAR_17, VAR_6);
 if ((VAR_18 & VAR_8) == 0)
  return;

 VAR_19 = FUNC_4(VAR_17->dev_softc,
          VAR_9 + 1, 1);

 if ((VAR_19 & ~VAR_4) != 0
  || (VAR_17->flags & VAR_0) == 0) {
  FUNC_6("%s: PCI error Interrupt at seqaddr = 0x%x\n",
         FUNC_1(VAR_17),
         FUNC_0(VAR_17, VAR_12) | (FUNC_0(VAR_17, VAR_13) << 8));
 }

 if (VAR_19 & VAR_4
  && (VAR_17->flags & VAR_0) == 0) {
  VAR_17->pci_target_perr_count++;
  FUNC_6("%s: Data Parity Error Detected during address "
         "or write data phase\n", FUNC_1(VAR_17));
 }
 if (VAR_19 & VAR_15) {
  FUNC_6("%s: Signal System Error Detected\n", FUNC_1(VAR_17));
 }
 if (VAR_19 & VAR_10) {
  FUNC_6("%s: Received a Master Abort\n", FUNC_1(VAR_17));
 }
 if (VAR_19 & VAR_11) {
  FUNC_6("%s: Received a Target Abort\n", FUNC_1(VAR_17));
 }
 if (VAR_19 & VAR_16) {
  FUNC_6("%s: Signaled a Target Abort\n", FUNC_1(VAR_17));
 }
 if (VAR_19 & VAR_5) {
  FUNC_6("%s: Data Parity Error has been reported via PERR#\n",
         FUNC_1(VAR_17));
 }


 FUNC_5(VAR_17->dev_softc, VAR_9 + 1,
        VAR_19, 1);

 if ((VAR_19 & (VAR_4|VAR_15|VAR_10|VAR_11|VAR_16|VAR_5)) == 0) {
  FUNC_6("%s: Latched PCIERR interrupt with "
         "no status bits set\n", FUNC_1(VAR_17));
 } else {
  FUNC_2(VAR_17, VAR_2, VAR_3);
 }

 if (VAR_17->pci_target_perr_count > VAR_1
  && (VAR_17->flags & VAR_0) == 0) {
  FUNC_6(
"%s: WARNING WARNING WARNING WARNING\n"
"%s: Too many PCI parity errors observed as a target.\n"
"%s: Some device on this PCI bus is generating bad parity.\n"
"%s: This is an error *observed by*, not *generated by*, %s.\n"
"%s: PCI parity error checking has been disabled.\n"
"%s: WARNING WARNING WARNING WARNING\n",
         FUNC_1(VAR_17), FUNC_1(VAR_17), FUNC_1(VAR_17),
         FUNC_1(VAR_17), FUNC_1(VAR_17), FUNC_1(VAR_17),
         FUNC_1(VAR_17));
  VAR_17->seqctl |= VAR_7;
  VAR_17->flags |= VAR_0;
  FUNC_2(VAR_17, VAR_14, VAR_17->seqctl);
 }
 FUNC_3(VAR_17);
}
